### ISSUE TITLE
specify required dependencies in setup.py

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#100]
currently, setup.py does not have `install_requires` & the user must `$ pip install -r requirements.txt` to install dependencies.

- `setup.py` should specify minimal dependencies so that `pip` can install pynwb and its dependencies
- `requirements.txt` should specify the precise environment that the package is tested against

**Comment by kotfic** [comment]
FWIW after adding:

```python
    'install_requires': [
        'h5py',
        'scipy',
        'numpy',
        'ruamel.yaml',
        'python-dateutil',
        'unittest2',
        'six',
        'requests'
    ]
```
to ```setup.py``` I was unable to install following the instructions (e.g.  ```python setup.py build```,  ```python setup.py install```). I received the following exception:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 62, in <module>
    setup(**setup_args)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 411, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 653, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 700, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 745, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/pkg_resources/__init__.py", line 863, in resolve
    replace_conflicting=replace_conflicting
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1141, in best_match
    return self.obtain(req, installer)
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1153, in obtain
    return installer(requirement)
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 698, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1104, in run_setup
    run_setup(setup_script, args)
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/sandbox.py", line 170, in save_modules
    saved_exc.resume()
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/sandbox.py", line 145, in resume
    six.reraise(type, exc, self._tb)
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/home/kotfic/.venvs/pynwb_clean/lib/python3.6/site-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-nwptkkv4/scipy-1.0.0b1/setup.py", line 418, in <module>
  File "/tmp/easy_install-nwptkkv4/scipy-1.0.0b1/setup.py", line 398, in setup_package
ModuleNotFoundError: No module named 'numpy'
```

I was, however, able to successfully install with pip.   Python 3.6.2, pip 9.0.1.  

I was going to put in a PR that added this change,  but i can't get it to work with out adding pip to the tool chain (which would necessitate changing the docs and the Dockerfiles). If that isn't an issue i'm happy to open a PR.

Cheers!
