### ISSUE TITLE
Reading NWB file with single experimenter causes error

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1034]
```
Traceback (most recent call last):
  File "test_read_gratings_data.py", line 4, in <module>
    read_file = io.read()
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\backends\hdf5\h5tools.py", line 246, in read
    return call_docval_func(super(HDF5IO, self).read, kwargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 327, in call_docval_func
    return func(*fargs, **fkwargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\backends\io.py", line 35, in read
    container = self.__manager.construct(f_builder)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\map.py", line 207, in construct
    result = self.__type_map.construct(builder, self, None)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\map.py", line 1669, in construct
    return attr_map.construct(builder, build_manager, parent)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\map.py", line 1178, in construct
    override = self.__get_override_carg(argname, builder, manager)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\map.py", line 689, in __get_override_carg
    return func(self, *remaining_args)
  File "c:\users\ryan\documents\nwb\pynwb\src\pynwb\io\file.py", line 81, in experimenter_carg
    ret = (builder.data,)
AttributeError: 'GroupBuilder' object has no attribute 'data'
```

**Comment by oruebel** [comment]
@rly, looking at it, I think the fix is simply to change ```ret = (builder.data,)``` to ```ret = (exp_bldr.data,)``` in:

https://github.com/NeurodataWithoutBorders/pynwb/blob/6b2a628f4af18417a66f3daacb3770ce6131ae9a/src/pynwb/io/file.py#L113-L122

**Comment by rly** [comment]
Already got it ;) https://github.com/NeurodataWithoutBorders/pynwb/pull/1035
