### ISSUE TITLE
Can't read indy_20160622_01.nwb in https://zenodo.org/record/1488441

### ISSUE THREAD

**Issue by KimUyen** [NeurodataWithoutBorders/pynwb#1051]
### Script to read the  indy_20160622_01.nwb
```python
import numpy as np
from pynwb import NWBHDF5IO

io = NWBHDF5IO('indy_20160622_01.nwb', mode='r')
nwbfile_in = io.read()
```

### Environment
- **Python Executable:** Conda
- **Python Version:** Python 3.6
- **Operating System:** Ubuntu 16.04
- **PyNWB Version:** 1.0.3.post0.dev26

### Error Log
```cmd
(base) kimuyen@kimuyen:/media/kimuyen/JAMIE/KIMUYEN/BCI/CODE$ python ./analyzedata.py 
Traceback (most recent call last):
  File "./analyzedata.py", line 5, in <module>
    nwbfile_in = io.read()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/hdmf/backends/hdf5/h5tools.py", line 246, in read
    return call_docval_func(super(HDF5IO, self).read, kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/hdmf/utils.py", line 325, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/hdmf/utils.py", line 436, in func_call
    return func(self, **parsed['args'])
  File "/usr/local/anaconda3/lib/python3.6/site-packages/hdmf/backends/io.py", line 35, in read
    container = self.__manager.construct(f_builder)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/hdmf/utils.py", line 436, in func_call
    return func(self, **parsed['args'])
  File "/usr/local/anaconda3/lib/python3.6/site-packages/hdmf/build/map.py", line 207, in construct
    result = self.__type_map.construct(builder, self, None)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/hdmf/utils.py", line 436, in func_call
    return func(self, **parsed['args'])
  File "/usr/local/anaconda3/lib/python3.6/site-packages/hdmf/build/map.py", line 1668, in construct
    attr_map = self.get_map(builder)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/hdmf/utils.py", line 436, in func_call
    return func(self, **parsed['args'])
  File "/usr/local/anaconda3/lib/python3.6/site-packages/hdmf/build/map.py", line 1595, in get_map
    container_cls = self.get_cls(obj)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/hdmf/utils.py", line 436, in func_call
    return func(self, **parsed['args'])
  File "/usr/local/anaconda3/lib/python3.6/site-packages/hdmf/build/map.py", line 1522, in get_cls
    raise ValueError("No data_type found for builder %s" % builder.path)
ValueError: No data_type found for builder root

```

**Comment by bendichter** [comment]
The description page says that the data is in 1.0.6 format. This package supports reading NWB:N version 2.0 and up

**Comment by rly** [comment]
This tutorial may be useful for reading the NWB 1.0 data: https://smackesey.github.io/nwb_tutorial/assets/tutorial.html

**Comment by KimUyen** [comment]
> 
> 
> This tutorial may be useful for reading the NWB 1.0 data: https://smackesey.github.io/nwb_tutorial/assets/tutorial.html

Wow, thank you very much for helpful link.

**Comment by jeffteeters** [comment]
There is also documentation about the NWB 1.0 format at:
https://github.com/NeurodataWithoutBorders/specification_nwbn_1_0_x/tree/master/version_1.0.6
And at:
http://neurodatawithoutborders.github.io/api-python/build/html/index.html

**Comment by mckarthik7** [comment]
You may be able to read the file by directly opening the nwb file using h5py (or any HDF reader). For the same file (indy_20160622_01) I was able to extract most of what I needed using this method.
