### ISSUE TITLE
validator fails for the extensions tutorial when namespace file provided

### ISSUE THREAD

**Issue by lvsltz** [NeurodataWithoutBorders/pynwb#1058]
### Steps to Reproduce
The code I am running is the extensions tutorial found here: [https://pynwb.readthedocs.io/en/stable/tutorials/general/extensions.html#sphx-glr-tutorials-general-extensions-py](url)

When I try to validate against the specifications referenced in the namespace file (which is created by the tutorial), the validation fails:
```python -m pynwb.validate cache_spec_example.nwb``` [validates correctly]
```python -m pynwb.validate -p mylab.namespace.yaml cache_spec_example.nwb``` [fails with the error below]

```
Turning off validation against cached namespace informationas --nspath was passed.
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/nwb/lib/python3.7/site-packages/hdmf/spec/namespace.py", line 408, in __load_namespace
    inc_ns = self.get_namespace(s['namespace'])
  File "/home/username/miniconda3/envs/nwb/lib/python3.7/site-packages/hdmf/utils.py", line 436, in func_call
    return func(self, **parsed['args'])
  File "/home/username/miniconda3/envs/nwb/lib/python3.7/site-packages/hdmf/spec/namespace.py", line 289, in get_namespace
    raise KeyError("'%s' not a namespace" % name)
KeyError: "'core' not a namespace"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/username/miniconda3/envs/nwb/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/username/miniconda3/envs/nwb/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/username/miniconda3/envs/nwb/lib/python3.7/site-packages/pynwb/validate.py", line 117, in <module>
    main()
  File "/home/username/miniconda3/envs/nwb/lib/python3.7/site-packages/pynwb/validate.py", line 86, in main
    namespaces = catalog.load_namespaces(args.nspath)
  File "/home/username/miniconda3/envs/nwb/lib/python3.7/site-packages/hdmf/utils.py", line 436, in func_call
    return func(self, **parsed['args'])
  File "/home/username/miniconda3/envs/nwb/lib/python3.7/site-packages/hdmf/spec/namespace.py", line 457, in load_namespaces
    ret[ns['name']] = self.__load_namespace(ns, reader, types_key, resolve=resolve)
  File "/home/username/miniconda3/envs/nwb/lib/python3.7/site-packages/hdmf/spec/namespace.py", line 410, in __load_namespace
    raise_from(ValueError("Could not load namespace '%s'" % s['namespace']), e)
  File "<string>", line 3, in raise_from
ValueError: Could not load namespace 'core
```

### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda
- **Python Version:** Python 3.7
- **Operating System:** Linux
- **PyNWB Version:** 1.0.3

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by bendichter** [comment]
@lvsltz thanks for the report. It looks like something has gone wrong with our validation of extensions. @ajtritt, do you know what might be going on here?

**Comment by bendichter** [comment]
It looks like this was caused by #944. I am having trouble validating any file that does not contain the specification. Does #944 *require* that the schema is stored for validation?

**Comment by oruebel** [comment]
Adding @t-b , I believe he was leading #944

**Comment by t-b** [comment]
I think I never tried validating adainst a passed namepace file. I'll have a look.

**Comment by oruebel** [comment]
@t-b did you have a chance to check on this. I was just wondering, because I started going through isses on the ICEphys extension proposal and I think https://github.com/oruebel/ndx-icephys-meta/issues/21 is the actually the same issue

CC @ajtritt

**Comment by t-b** [comment]
@oruebel Not yet, sorry.

**Comment by t-b** [comment]
Okay so I've starting looking into that.

Using  pynwb `a41eaee7 (Fix test runner double printing in non-verbose mode (#1158), 2020-01-27)` and hdmf `13721688 (hdmf/backends/hdf5/h5tools.py: Add mode property to access the file mode (#280), 2020-01-30)` I can still reproduce the issue

```
$python -m pynwb.validate --nspath test_multicontainerinterface.namespace.yaml test_multicontainerinterface.nwb 
Turning off validation against cached namespace information as --nspath was passed.
Traceback (most recent call last):
  File "/home/firma/devel/hdmf/src/hdmf/spec/namespace.py", line 408, in __load_namespace
    inc_ns = self.get_namespace(s['namespace'])
  File "/home/firma/devel/hdmf/src/hdmf/utils.py", line 453, in func_call
    return func(args[0], **parsed['args'])
  File "/home/firma/devel/hdmf/src/hdmf/spec/namespace.py", line 289, in get_namespace
    raise KeyError("'%s' not a namespace" % name)
KeyError: "'core' not a namespace"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/firma/.pyenv/versions/3.6.7/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/firma/.pyenv/versions/3.6.7/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/firma/devel/pynwb/src/pynwb/validate.py", line 128, in <module>
    main()
  File "/home/firma/devel/pynwb/src/pynwb/validate.py", line 89, in main
    namespaces = catalog.load_namespaces(args.nspath)
  File "/home/firma/devel/hdmf/src/hdmf/utils.py", line 453, in func_call
    return func(args[0], **parsed['args'])
  File "/home/firma/devel/hdmf/src/hdmf/spec/namespace.py", line 461, in load_namespaces
    ret[ns['name']] = self.__load_namespace(ns, reader, types_key, resolve=resolve)
  File "/home/firma/devel/hdmf/src/hdmf/spec/namespace.py", line 410, in __load_namespace
    raise ValueError("Could not load namespace '%s'" % s['namespace']) from e
ValueError: Could not load namespace 'core'
```

but this error has nothing to do with extensions as the following does fail as well

```
python -m pynwb.validate --nspath src/pynwb/nwb-schema/hdmf-common-schema/common/namespace.yaml icephys_example.nwb
```

and also

```
$python -m pynwb.validate --nspath src/pynwb/nwb-schema/core/nwb.namespace.yaml icephys_example.nwb
```

**Comment by t-b** [comment]
So from some playing around I think we need to discuss first what we want to validate against if a namespace file is provided.

The error message states that the core namespace could not be found, this seems to be the case because https://github.com/hdmf-dev/hdmf/blob/594d45ad3094b9f6545a208943b02c22c580c91d/src/hdmf/spec/namespace.py#L436 does try to resolve parent namespaces by default.

Maybe the validator should load the core/cached namespaces in addition to the one given with the nspath?

**Comment by t-b** [comment]
@yarikoptic Can you make a draft PR with the changes from yesterday.

**Comment by yarikoptic** [comment]
There are some sad patches which are in a branch I won't even disclose here in public in my clones of hdmf and pynwb, and which I sent to @ajtritt  . I will leave their destiny in his trustworthy hands ;-)

**Comment by t-b** [comment]
@yarikoptic @ajtritt Any chance that these patches can be made publishable? I hate to write an extension and don't have it validated.

**Comment by yarikoptic** [comment]
I will stand my grounds of ignorance and blissfully point to @ajtritt ;-)
