### ISSUE TITLE
fail to `import pywnb` upon `pip install -e` in a virtualenv

### ISSUE THREAD

**Issue by yarikoptic** [NeurodataWithoutBorders/pynwb#1076]
#  Description

To troubleshoot #1075 I thought to try current `dev` (1.0.3-29-g6a76a7a7) and followed typical/standard virtualenv/pip -e route to get me going, but then pynwb is not importable:

```shell
(git)hopa:~exppsy/pynwb[dev]git
$> virtualenv --python=python3 venvs/dev3-pure                                                                     
Already using interpreter /usr/bin/python3    
Using base prefix '/usr'
New python executable in /home/yoh/deb/gits/pkg-exppsy/pynwb/venvs/dev3-pure/bin/python3
Also creating executable in /home/yoh/deb/gits/pkg-exppsy/pynwb/venvs/dev3-pure/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

$> source venvs/dev3-pure/bin/activate

$> pip install -e .
Obtaining file:///home/yoh/deb/gits/pkg-exppsy/pynwb
Collecting chardet (from pynwb==1.0.3.post0.dev29)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting h5py (from pynwb==1.0.3.post0.dev29)
  Downloading https://files.pythonhosted.org/packages/3f/c0/abde58b837e066bca19a3f7332d9d0493521d7dd6b48248451a9e3fe2214/h5py-2.10.0-cp37-cp37m-manylinux1_x86_64.whl (2.9MB)
     |████████████████████████████████| 2.9MB 2.8MB/s 
Collecting hdmf (from pynwb==1.0.3.post0.dev29)
  Downloading https://files.pythonhosted.org/packages/88/64/22c262e1a5b3a82c7c62fdcaa9f7712f167437ea1370ab8cc2b2cbde23f8/hdmf-1.3.2-py2.py3-none-any.whl (101kB)
     |████████████████████████████████| 102kB 3.2MB/s 
Collecting numpy (from pynwb==1.0.3.post0.dev29)
  Downloading https://files.pythonhosted.org/packages/ba/e0/46e2f0540370f2661b044647fa447fef2ecbcc8f7cdb4329ca2feb03fb23/numpy-1.17.2-cp37-cp37m-manylinux1_x86_64.whl (20.3MB)
     |████████████████████████████████| 20.3MB 2.5MB/s 
Collecting pandas (from pynwb==1.0.3.post0.dev29)
  Downloading https://files.pythonhosted.org/packages/7e/ab/ea76361f9d3e732e114adcd801d2820d5319c23d0ac5482fa3b412db217e/pandas-0.25.1-cp37-cp37m-manylinux1_x86_64.whl (10.4MB)
     |████████████████████████████████| 10.4MB 2.3MB/s 
Collecting python-dateutil (from pynwb==1.0.3.post0.dev29)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting ruamel.yaml (from pynwb==1.0.3.post0.dev29)
  Downloading https://files.pythonhosted.org/packages/fa/90/ecff85a2e9c497e2fa7142496e10233556b5137db5bd46f3f3b006935ca8/ruamel.yaml-0.16.5-py2.py3-none-any.whl (123kB)
     |████████████████████████████████| 133kB 2.3MB/s 
Collecting six (from pynwb==1.0.3.post0.dev29)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting scipy (from hdmf->pynwb==1.0.3.post0.dev29)
  Using cached https://files.pythonhosted.org/packages/94/7f/b535ec711cbcc3246abea4385d17e1b325d4c3404dd86f15fc4f3dba1dbb/scipy-1.3.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting pytz>=2017.2 (from pandas->pynwb==1.0.3.post0.dev29)
  Using cached https://files.pythonhosted.org/packages/87/76/46d697698a143e05f77bec5a526bf4e56a0be61d63425b68f4ba553b51f2/pytz-2019.2-py2.py3-none-any.whl
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" (from ruamel.yaml->pynwb==1.0.3.post0.dev29)
  Downloading https://files.pythonhosted.org/packages/40/80/da16b691d5e259dd9919a10628e541fca321cb4b078fbb88e1c7c22aa42d/ruamel.yaml.clib-0.2.0-cp37-cp37m-manylinux1_x86_64.whl (547kB)
     |████████████████████████████████| 552kB 1.1MB/s 
Installing collected packages: chardet, six, numpy, h5py, scipy, python-dateutil, pytz, pandas, ruamel.yaml.clib, ruamel.yaml, hdmf, pynwb
  Running setup.py develop for pynwb
Successfully installed chardet-3.0.4 h5py-2.10.0 hdmf-1.3.2 numpy-1.17.2 pandas-0.25.1 

(git)hopa:~exppsy/pynwb[dev]git
$> python -c 'import pynwb'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/__init__.py", line 223, in <module>
    from . import io as __io  # noqa: F401,E402
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/io/__init__.py", line 1, in <module>
    from . import base as __base
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/io/base.py", line 1, in <module>
    from .core import NWBContainerMapper
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/io/core.py", line 7, in <module>
    from pynwb.file import NWBFile
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/file.py", line 16, in <module>
    from .base import TimeSeries, ProcessingModule
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/base.py", line 11, in <module>
    from .core import NWBDataInterface, MultiContainerInterface, NWBData
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/core.py", line 205, in <module>
    class NWBContainer(NWBBaseType, Container):
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/__init__.py", line 125, in _dec
    __TYPE_MAP.register_container_type(namespace, neurodata_type, cls)
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/venvs/dev3-pure/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/venvs/dev3-pure/lib/python3.7/site-packages/hdmf/build/map.py", line 1655, in register_container_type
    spec = self.__ns_catalog.get_spec(namespace, data_type)    # make sure the spec exists
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/venvs/dev3-pure/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/venvs/dev3-pure/lib/python3.7/site-packages/hdmf/spec/namespace.py", line 302, in get_spec
    raise KeyError("'%s' not a namespace" % namespace)
KeyError: "'core' not a namespace"
```
## Environment

    Python Executable: Python
    Python Version:  3.7
    Operating System: Linux
    HDMF Version: Version of PyNWB used is `dev`, hdmf whatever installed by pip see above

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [ ] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
Please update to the latest `dev` branch of PyNWB. It looks like you are running 1.0.3, which is not compatible with the latest version of HDMF, 1.3.2. The latest PyNWB version is two commits past 1.1.0.

**Comment by yarikoptic** [comment]
<details>
<summary>The same story with 1.1.0-2-gb7cc9530</summary> 

```shell
$> pip install --upgrade -e .
Obtaining file:///home/yoh/deb/gits/pkg-exppsy/pynwb
Requirement already satisfied, skipping upgrade: chardet in ./venvs/dev3-pure/lib/python3.7/site-packages (from pynwb==1.1.0.post0.dev2) (3.0.4)
Requirement already satisfied, skipping upgrade: h5py in ./venvs/dev3-pure/lib/python3.7/site-packages (from pynwb==1.1.0.post0.dev2) (2.10.0)
Requirement already satisfied, skipping upgrade: hdmf in ./venvs/dev3-pure/lib/python3.7/site-packages (from pynwb==1.1.0.post0.dev2) (1.3.2)
Requirement already satisfied, skipping upgrade: numpy in ./venvs/dev3-pure/lib/python3.7/site-packages (from pynwb==1.1.0.post0.dev2) (1.17.2)
Requirement already satisfied, skipping upgrade: pandas in ./venvs/dev3-pure/lib/python3.7/site-packages (from pynwb==1.1.0.post0.dev2) (0.25.1)
Requirement already satisfied, skipping upgrade: python-dateutil in ./venvs/dev3-pure/lib/python3.7/site-packages (from pynwb==1.1.0.post0.dev2) (2.8.0)
Requirement already satisfied, skipping upgrade: ruamel.yaml in ./venvs/dev3-pure/lib/python3.7/site-packages (from pynwb==1.1.0.post0.dev2) (0.16.5)
Requirement already satisfied, skipping upgrade: six in ./venvs/dev3-pure/lib/python3.7/site-packages (from pynwb==1.1.0.post0.dev2) (1.12.0)
Requirement already satisfied, skipping upgrade: scipy in ./venvs/dev3-pure/lib/python3.7/site-packages (from hdmf->pynwb==1.1.0.post0.dev2) (1.3.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in ./venvs/dev3-pure/lib/python3.7/site-packages (from pandas->pynwb==1.1.0.post0.dev2) (2019.2)
Requirement already satisfied, skipping upgrade: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" in ./venvs/dev3-pure/lib/python3.7/site-packages (from ruamel.yaml->pynwb==1.1.0.post0.dev2) (0.2.0)
Installing collected packages: pynwb
  Found existing installation: pynwb 1.1.0.post0.dev2
    Uninstalling pynwb-1.1.0.post0.dev2:
      Successfully uninstalled pynwb-1.1.0.post0.dev2
  Running setup.py develop for pynwb
Successfully installed pynwb
(dev3-pure) 1 31943 [1].....................................:Mon 30 Sep 2019 08:45:36 AM EDT:.
(git)hopa:~exppsy/pynwb[dev]git
$> git describe              
1.1.0-2-gb7cc9530
(dev3-pure) 1 31944 [1].....................................:Mon 30 Sep 2019 08:45:41 AM EDT:.
(git)hopa:~exppsy/pynwb[dev]git
$> python -c 'import pynwb'  
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/__init__.py", line 229, in <module>
    from . import io as __io  # noqa: F401,E402
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/io/__init__.py", line 1, in <module>
    from . import base as __base
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/io/base.py", line 1, in <module>
    from .core import NWBContainerMapper
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/io/core.py", line 5, in <module>
    from pynwb.file import NWBFile
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/file.py", line 16, in <module>
    from .base import TimeSeries, ProcessingModule
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/base.py", line 13, in <module>
    from .core import NWBDataInterface, MultiContainerInterface, NWBData
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/core.py", line 34, in <module>
    class NWBContainer(NWBMixin, Container):
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/src/pynwb/__init__.py", line 131, in _dec
    __TYPE_MAP.register_container_type(namespace, neurodata_type, cls)
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/venvs/dev3-pure/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/venvs/dev3-pure/lib/python3.7/site-packages/hdmf/build/map.py", line 1655, in register_container_type
    spec = self.__ns_catalog.get_spec(namespace, data_type)    # make sure the spec exists
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/venvs/dev3-pure/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/home/yoh/deb/gits/pkg-exppsy/pynwb/venvs/dev3-pure/lib/python3.7/site-packages/hdmf/spec/namespace.py", line 302, in get_spec
    raise KeyError("'%s' not a namespace" % namespace)
KeyError: "'core' not a namespace"
```
</details>

<details>
<summary>and here is a full oneliner example to demonstrate "as of now"</summary> 

```shell
hopa:/tmp
$> git clone -b dev http://github.com/NeurodataWithoutBorders/pynwb && cd pynwb && virtualenv --python=python3 venvs/dev3-pure && source venvs/dev3-pure/bin/activate && pip install -e . && python -c "import pynwb"
Cloning into 'pynwb'...
warning: redirecting to https://github.com/NeurodataWithoutBorders/pynwb/
remote: Enumerating objects: 47, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 20192 (delta 17), reused 12 (delta 10), pack-reused 20145
Receiving objects: 100% (20192/20192), 21.02 MiB | 1.18 MiB/s, done.
Resolving deltas: 100% (13313/13313), done.
Legal.txt    Makefile    azure-pipelines.yml  license.txt           requirements-doc.txt  scripts/   setup.py*  test.py*  tox.ini
MANIFEST.in  README.rst  docs/                requirements-dev.txt  requirements.txt      setup.cfg  src/       tests/    versioneer.py
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /tmp/pynwb/venvs/dev3-pure/bin/python3
Also creating executable in /tmp/pynwb/venvs/dev3-pure/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Obtaining file:///tmp/pynwb
Collecting chardet (from pynwb==1.1.0.post0.dev2)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting h5py (from pynwb==1.1.0.post0.dev2)
  Using cached https://files.pythonhosted.org/packages/3f/c0/abde58b837e066bca19a3f7332d9d0493521d7dd6b48248451a9e3fe2214/h5py-2.10.0-cp37-cp37m-manylinux1_x86_64.whl
Collecting hdmf (from pynwb==1.1.0.post0.dev2)
  Using cached https://files.pythonhosted.org/packages/88/64/22c262e1a5b3a82c7c62fdcaa9f7712f167437ea1370ab8cc2b2cbde23f8/hdmf-1.3.2-py2.py3-none-any.whl
Collecting numpy (from pynwb==1.1.0.post0.dev2)
  Using cached https://files.pythonhosted.org/packages/ba/e0/46e2f0540370f2661b044647fa447fef2ecbcc8f7cdb4329ca2feb03fb23/numpy-1.17.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting pandas (from pynwb==1.1.0.post0.dev2)
  Using cached https://files.pythonhosted.org/packages/7e/ab/ea76361f9d3e732e114adcd801d2820d5319c23d0ac5482fa3b412db217e/pandas-0.25.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting python-dateutil (from pynwb==1.1.0.post0.dev2)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting ruamel.yaml (from pynwb==1.1.0.post0.dev2)
  Using cached https://files.pythonhosted.org/packages/fa/90/ecff85a2e9c497e2fa7142496e10233556b5137db5bd46f3f3b006935ca8/ruamel.yaml-0.16.5-py2.py3-none-any.whl
Collecting six (from pynwb==1.1.0.post0.dev2)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting scipy (from hdmf->pynwb==1.1.0.post0.dev2)
  Using cached https://files.pythonhosted.org/packages/94/7f/b535ec711cbcc3246abea4385d17e1b325d4c3404dd86f15fc4f3dba1dbb/scipy-1.3.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting pytz>=2017.2 (from pandas->pynwb==1.1.0.post0.dev2)
  Using cached https://files.pythonhosted.org/packages/87/76/46d697698a143e05f77bec5a526bf4e56a0be61d63425b68f4ba553b51f2/pytz-2019.2-py2.py3-none-any.whl
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" (from ruamel.yaml->pynwb==1.1.0.post0.dev2)
  Using cached https://files.pythonhosted.org/packages/40/80/da16b691d5e259dd9919a10628e541fca321cb4b078fbb88e1c7c22aa42d/ruamel.yaml.clib-0.2.0-cp37-cp37m-manylinux1_x86_64.whl
Installing collected packages: chardet, numpy, six, h5py, ruamel.yaml.clib, ruamel.yaml, python-dateutil, pytz, pandas, scipy, hdmf, pynwb
  Running setup.py develop for pynwb
Successfully installed chardet-3.0.4 h5py-2.10.0 hdmf-1.3.2 numpy-1.17.2 pandas-0.25.1 pynwb python-dateutil-2.8.0 pytz-2019.2 ruamel.yaml-0.16.5 ruamel.yaml.clib-0.2.0 scipy-1.3.1 six-1.12.0
pip install -e .  10.59s user 1.59s system 88% cpu 13.814 total
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pynwb/src/pynwb/__init__.py", line 229, in <module>
    from . import io as __io  # noqa: F401,E402
  File "/tmp/pynwb/src/pynwb/io/__init__.py", line 1, in <module>
    from . import base as __base
  File "/tmp/pynwb/src/pynwb/io/base.py", line 1, in <module>
    from .core import NWBContainerMapper
  File "/tmp/pynwb/src/pynwb/io/core.py", line 5, in <module>
    from pynwb.file import NWBFile
  File "/tmp/pynwb/src/pynwb/file.py", line 16, in <module>
    from .base import TimeSeries, ProcessingModule
  File "/tmp/pynwb/src/pynwb/base.py", line 13, in <module>
    from .core import NWBDataInterface, MultiContainerInterface, NWBData
  File "/tmp/pynwb/src/pynwb/core.py", line 34, in <module>
    class NWBContainer(NWBMixin, Container):
  File "/tmp/pynwb/src/pynwb/__init__.py", line 131, in _dec
    __TYPE_MAP.register_container_type(namespace, neurodata_type, cls)
  File "/tmp/pynwb/venvs/dev3-pure/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/tmp/pynwb/venvs/dev3-pure/lib/python3.7/site-packages/hdmf/build/map.py", line 1655, in register_container_type
    spec = self.__ns_catalog.get_spec(namespace, data_type)    # make sure the spec exists
  File "/tmp/pynwb/venvs/dev3-pure/lib/python3.7/site-packages/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/tmp/pynwb/venvs/dev3-pure/lib/python3.7/site-packages/hdmf/spec/namespace.py", line 302, in get_spec
    raise KeyError("'%s' not a namespace" % namespace)
KeyError: "'core' not a namespace"

```
</details>

**Comment by rly** [comment]
@yarikoptic I found the problem. The submodule needs to be initialized and synced.

From the pynwb folder, please run: `git submodule update --init --recursive`

In your one-liner, instead of `git clone -b dev http://github.com/NeurodataWithoutBorders/pynwb`
please run `git clone --recurse-submodules -b dev http://github.com/NeurodataWithoutBorders/pynwb`

These need to be added to the documentation.

**Comment by yarikoptic** [comment]
Ah, I will try

In the longer run I think this is one of those cases where git subtree would be a better mechanism to include that repo here (and I am not scared by git submodules... eg look at this beast http://datasets.datalad.org, you can clone it), primarily since it always needs to be initialized if I get it right

See eg https://www.atlassian.com/git/tutorials/git-subtree for the reasoning/howto

**Comment by yarikoptic** [comment]
I will leave it to the developers to decide on how to deal with submodules/subtrees (it seems that every new potential contributor runs into them), but as the need for submodules update --init is documented, I guess there is no immediate action to be done, so I will close this one.
Cheers!
