### ISSUE TITLE
issue writing units table with electrodes defined

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1097]
Steps to Reproduce

```python
from datetime import datetime
from dateutil.tz import tzlocal
from pynwb import NWBFile, NWBHDF5IO

nwbfile = NWBFile(session_description='session', identifier='1', session_start_time=datetime.now(tzlocal()))
nwbfile.add_unit(electrodes=(0,))

with NWBHDF5IO('test_file.nwb', 'w') as io:
    io.write(nwbfile)
```

```python
/anaconda3/envs/pynwb/bin/python /Users/bendichter/dev/pynwb/scratch_units.py
Traceback (most recent call last):
  File "/Users/bendichter/dev/pynwb/scratch_units.py", line 9, in <module>
    io.write(nwbfile)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/backends/hdf5/h5tools.py", line 269, in write
    call_docval_func(super(HDF5IO, self).write, kwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 327, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/backends/io.py", line 43, in write
    f_builder = self.__manager.build(container, source=self.__source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 166, in build
    result = self.__type_map.build(container, self, source=source, spec_ext=spec_ext)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 1709, in build
    builder = attr_map.build(container, manager, builder=builder, source=source, spec_ext=spec_ext)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 802, in build
    self.__add_groups(builder, self.__spec.groups, container, manager, source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 1034, in __add_groups
    self.__add_containers(builder, spec, attr_value, build_manager, source, container)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 1045, in __add_containers
    rendered_obj = build_manager.build(value, source=source, spec_ext=spec)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 166, in build
    result = self.__type_map.build(container, self, source=source, spec_ext=spec_ext)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 1709, in build
    builder = attr_map.build(container, manager, builder=builder, source=source, spec_ext=spec_ext)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 801, in build
    self.__add_datasets(builder, self.__spec.datasets, container, manager, source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 994, in __add_datasets
    self.__add_containers(builder, spec, attr_value, build_manager, source, container)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 1045, in __add_containers
    rendered_obj = build_manager.build(value, source=source, spec_ext=spec)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 166, in build
    result = self.__type_map.build(container, self, source=source, spec_ext=spec_ext)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 1709, in build
    builder = attr_map.build(container, manager, builder=builder, source=source, spec_ext=spec_ext)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 853, in build
    self.__add_attributes(builder, self.__spec.attributes, container, manager, source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 944, in __add_attributes
    target_builder = build_manager.build(attr_value, source=source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 166, in build
    result = self.__type_map.build(container, self, source=source, spec_ext=spec_ext)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 1709, in build
    builder = attr_map.build(container, manager, builder=builder, source=source, spec_ext=spec_ext)
  File "/Users/bendichter/dev/hdmf/src/hdmf/utils.py", line 438, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 853, in build
    self.__add_attributes(builder, self.__spec.attributes, container, manager, source)
  File "/Users/bendichter/dev/hdmf/src/hdmf/build/map.py", line 943, in __add_attributes
    raise ValueError(msg)
ValueError: object of data_type DynamicTable not found on DynamicTableRegion 'electrodes'

Process finished with exit code 1
```

## Environment
     hdmf==1.3.3.post0.dev9 (latest dev)
     pynwb==1.1.2.post0.dev5 (latest dev)

**Comment by stephprince** [comment]
Closing this issue because the file will now successfully be written but will warn the user:

```
/Users/smprince/Documents/code/pynwb/src/pynwb/misc.py:214: UserWarning: Reference to electrode table that does not yet exist
  warnings.warn('Reference to electrode table that does not yet exist')
/Users/smprince/Documents/code/hdmf/src/hdmf/build/objectmapper.py:684: MissingRequiredBuildWarning: DynamicTableRegion 'electrodes' is missing required value for attribute 'table'.
  warnings.warn(msg, MissingRequiredBuildWarning)
```
Please reopen if this issue was not fully addressed.
