### ISSUE TITLE
Min requirements CI failing on Windows

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1190]
The Azure test for python 3.5 using the minimum requirements is failing due to the following error. It happens non-deterministically. It is probably a weird interaction between h5py, windows, and pandas.

```
hdf5.test_nwbfile.TestElectrodes
    +----------------+---------------------------------------------------------+-------------+
    |   Test name    |                          Output                         |    Status   |
    +----------------+---------------------------------------------------------+-------------+
    | test_roundtrip | ValueError: cannot expose native-only dtype 'g' in non- | error       |
    |                | native byte order '<' via buffer interface              |             |
    |                |                                                         |             |
    +----------------+---------------------------------------------------------+-------------+
ERROR in test test_roundtrip (hdf5.test_nwbfile.TestElectrodes):
Traceback (most recent call last):
File "D:\a\1\s\tests\integration\hdf5\test_nwbfile.py", line 459, in test_roundtrip
  pd.testing.assert_frame_equal(self.read_container[0].drop('group', axis=1),
File "D:\a\1\s\.tox\py35-min-req\lib\site-packages\pandas\core\frame.py", line 3694, in drop
  errors=errors)
File "D:\a\1\s\.tox\py35-min-req\lib\site-packages\pandas\core\generic.py", line 3108, in drop
  obj = obj._drop_axis(labels, axis, level=level, errors=errors)
File "D:\a\1\s\.tox\py35-min-req\lib\site-packages\pandas\core\generic.py", line 3141, in _drop_axis
  dropped = self.reindex(**{axis_name: new_axis})
File "D:\a\1\s\.tox\py35-min-req\lib\site-packages\pandas\util\_decorators.py", line 186, in wrapper
  return func(*args, **kwargs)
File "D:\a\1\s\.tox\py35-min-req\lib\site-packages\pandas\core\frame.py", line 3563, in reindex
  return super(DataFrame, self).reindex(**kwargs)
File "D:\a\1\s\.tox\py35-min-req\lib\site-packages\pandas\core\generic.py", line 3685, in reindex
  fill_value, copy).__finalize__(self)
File "D:\a\1\s\.tox\py35-min-req\lib\site-packages\pandas\core\frame.py", line 3493, in _reindex_axes
  fill_value, limit, tolerance)
File "D:\a\1\s\.tox\py35-min-req\lib\site-packages\pandas\core\frame.py", line 3518, in _reindex_columns
  allow_dups=False)
File "D:\a\1\s\.tox\py35-min-req\lib\site-packages\pandas\core\generic.py", line 3806, in _reindex_with_indexers
  copy=copy)
File "D:\a\1\s\.tox\py35-min-req\lib\site-packages\pandas\core\internals.py", line 4421, in reindex_indexer
  fill_tuple=(fill_value,))
File "D:\a\1\s\.tox\py35-min-req\lib\site-packages\pandas\core\internals.py", line 4501, in _slice_take_blocks_ax0
  fill_tuple=None))
File "D:\a\1\s\.tox\py35-min-req\lib\site-packages\pandas\core\internals.py", line 1254, in take_nd
  allow_fill=False)
File "D:\a\1\s\.tox\py35-min-req\lib\site-packages\pandas\core\algorithms.py", line 1656, in take_nd
  func(arr, indexer, out, fill_value)
File "pandas\_libs\algos_take_helper.pxi", line 4629, in pandas._libs.algos.take_2d_axis1_float64_float64
File "stringsource", line 653, in View.MemoryView.memoryview_cwrapper
File "stringsource", line 348, in View.MemoryView.memoryview.__cinit__
ValueError: cannot expose native-only dtype 'g' in non-native byte order '<' via buffer interface
```

**Comment by rly** [comment]
This error is apparently resolved in h5py 2.10. It is due (again) to an h5py/Windows on Python 3.5 interaction where floating point values are read stochastically as `np.float128` (dtype code 'g') instead of `np.float64`, and pandas is not happy with that. See https://github.com/h5py/h5py/issues/1051 and https://github.com/h5py/h5py/pull/1134 for more information. 

I cannot think of a clean way to resolve it in HDMF, so in the meantime, I am going to make the minimum requirements CI run on Python 3.6 rather than 3.5. Python 3.5 end of life is [2020-09-13](https://devguide.python.org/#status-of-python-branches). Since Python 3.6 has been out for three years and Python 3.8 is out now, I think we can safely start encouraging users to upgrade from Python 3.5.
