### ISSUE TITLE
error validating nwb file

### ISSUE THREAD

**Issue by neuromusic** [NeurodataWithoutBorders/pynwb#127]
using the example from the docs...

```
(vb) [justink@ibs-justink-ux1 pynwb_ophys_behavior]$ python -m pynwb.validate ophys.nwb 
Traceback (most recent call last):
  File "/local1/miniconda2/envs/vb/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/local1/miniconda2/envs/vb/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/local1/Code/pynwb/src/pynwb/validate.py", line 52, in <module>
    errors = validate(io)
  File "/local1/Code/pynwb/src/form/utils.py", line 280, in func_call
    return func(**parsed['args'])
  File "/local1/Code/pynwb/src/pynwb/__init__.py", line 127, in validate
    return validator.validate(builder)
  File "/local1/Code/pynwb/src/form/utils.py", line 272, in func_call
    return func(self, **parsed['args'])
  File "/local1/Code/pynwb/src/form/validate/validator.py", line 196, in validate
    return validator.validate(builder)
  File "/local1/Code/pynwb/src/form/utils.py", line 272, in func_call
    return func(self, **parsed['args'])
  File "/local1/Code/pynwb/src/form/validate/validator.py", line 304, in validate
    ret.extend(validator.validate(sub_builder))
  File "/local1/Code/pynwb/src/form/utils.py", line 272, in func_call
    return func(self, **parsed['args'])
  File "/local1/Code/pynwb/src/form/validate/validator.py", line 216, in validate
    ret.append(ShapeError(builder.name, self.spec.shape, shape))
  File "/local1/Code/pynwb/src/form/utils.py", line 272, in func_call
    return func(self, **parsed['args'])
  File "/local1/Code/pynwb/src/form/validate/errors.py", line 76, in __init__
    super(ShapeError, self).__init__(name, reason)
TypeError: object.__init__() takes no parameters
(vb) [justink@ibs-justink-ux1 pynwb_ophys_behavior]$ 
```

**Comment by neuromusic** [comment]
a different error on 3.6 with a clean install of the dev branch

```
(pynwb_dev) [justink@ibs-justink-ux1 pynwb_ophys_behavior]$ python -m pynwb.validate ophys.nwb 
Traceback (most recent call last):
  File "/local1/miniconda2/envs/pynwb_dev/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/local1/miniconda2/envs/pynwb_dev/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/local1/miniconda2/envs/pynwb_dev/lib/python3.6/site-packages/pynwb/validate.py", line 52, in <module>
    errors = validate(io)
  File "/local1/miniconda2/envs/pynwb_dev/lib/python3.6/site-packages/form/utils.py", line 280, in func_call
    return func(**parsed['args'])
  File "/local1/miniconda2/envs/pynwb_dev/lib/python3.6/site-packages/pynwb/__init__.py", line 127, in validate
    return validator.validate(builder)
  File "/local1/miniconda2/envs/pynwb_dev/lib/python3.6/site-packages/form/utils.py", line 272, in func_call
    return func(self, **parsed['args'])
  File "/local1/miniconda2/envs/pynwb_dev/lib/python3.6/site-packages/form/validate/validator.py", line 195, in validate
    validator = self.get_validator(dt)
  File "/local1/miniconda2/envs/pynwb_dev/lib/python3.6/site-packages/form/utils.py", line 271, in func_call
    raise_from(TypeError(msg), None)
  File "<string>", line 2, in raise_from
TypeError: incorrect type for 'data_type' (got 'bytes', expected 'BaseStorageSpec or str')

```

**Comment by jcfr** [comment]
xref #152

**Comment by neuromusic** [comment]
bumping this issue. It would be really nice to have a clean way to validate these files.

now getting other errors:
```
    return get_type(data[0])
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/pynwb/form/data_utils.py", line 26, in get_type
    if isinstance(data, str):
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by ajtritt** [comment]
@neuromusic I've made some changes since you created this issue. #314 should have fixed this. Do you still have problems running the validator?

**Comment by neuromusic** [comment]
no, it's still borking.

here's one file...

```
(ophys_nwb) [justink@ibs-justink-ux1 pynwb_ophys_behavior]$ python -m pynwb.validate ophys.nwb
Traceback (most recent call last):
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/local1/Code/pynwb/src/pynwb/validate.py", line 58, in <module>
    main()
  File "/local1/Code/pynwb/src/pynwb/validate.py", line 52, in main
    errors = validate(io)
  File "/local1/Code/pynwb/src/pynwb/form/utils.py", line 354, in func_call
    return func(**parsed['args'])
  File "/local1/Code/pynwb/src/pynwb/__init__.py", line 173, in validate
    builder = io.read_builder()
  File "/local1/Code/pynwb/src/pynwb/form/utils.py", line 346, in func_call
    return func(self, **parsed['args'])
  File "/local1/Code/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 144, in read_builder
    self.open()
  File "/local1/Code/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 257, in open
    self.__file = File(self.__path, open_flag)
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/h5py/_hl/files.py", line 115, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/h5f.c:2290)
IOError: Unable to create file (Unable to open file: name = 'ophys.nwb', errno = 17, error message = 'file exists', flags = 15, o_flags = c2)
```

on another I get another error...

```
eturn get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 33, in get_type
    return get_type(data[0])
  File "/local1/Code/pynwb/src/pynwb/form/data_utils.py", line 26, in get_type
    if isinstance(data, str):
RuntimeError: maximum recursion depth exceeded while calling a Python object
(ophys_nwb) [justink@ibs-justink-ux1 pynwb_ophys_behavior]$
```

note: these errors were on 2.7 fwiw

**Comment by neuromusic** [comment]
if I try to validate something that should be invalid (e.g. a txt file or a ipynb file) I get the following...

```
(ophys_nwb) [justink@ibs-justink-ux1 pynwb_ophys_behavior]$ python -m pynwb.validate create_imaging_plane.ipynb
Traceback (most recent call last):
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/local1/Code/pynwb/src/pynwb/validate.py", line 58, in <module>
    main()
  File "/local1/Code/pynwb/src/pynwb/validate.py", line 52, in main
    errors = validate(io)
  File "/local1/Code/pynwb/src/pynwb/form/utils.py", line 354, in func_call
    return func(**parsed['args'])
  File "/local1/Code/pynwb/src/pynwb/__init__.py", line 173, in validate
    builder = io.read_builder()
  File "/local1/Code/pynwb/src/pynwb/form/utils.py", line 346, in func_call
    return func(self, **parsed['args'])
  File "/local1/Code/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 144, in read_builder
    self.open()
  File "/local1/Code/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 257, in open
    self.__file = File(self.__path, open_flag)
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/local1/miniconda2/envs/ophys_nwb/lib/python2.7/site-packages/h5py/_hl/files.py", line 115, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create (/feedstock_root/build_artefacts/h5py_1491364603221/work/h5py-2.7.0/h5py/h5f.c:2290)
IOError: Unable to create file (Unable to open file: name = 'create_imaging_plane.ipynb', errno = 17, error message = 'file exists', flags = 15, o_flags = c2)
(ophys_nwb) [justink@ibs-justink-ux1 pynwb_ophys_behavior]$
```

**Comment by ajtritt** [comment]
In the first instance it is failing to read in the file, and i think the same for the second instance. Dealing with the third instance, I will add a check for that.

Can you share the files (or the code that generated the files) you used in the first and second examples?

**Comment by t-b** [comment]
This is still broken.

On 613f738d0c635d419af1de8e427c906aa7bb90ea when I do

```
cd docs/gallery/domain && python3 icephys.py && python3 -m pynwb.validate icephys_example.nwb
```

I get

```
(pynwb) firma@debian-notebook-byte-physics:~/devel/pynwb/docs/gallery/domain$ python -m pynwb.validate icephys_example.nwb
/home/firma/pynwb/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/firma/devel/pynwb/src/pynwb/validate.py", line 58, in <module>
    main()
  File "/home/firma/devel/pynwb/src/pynwb/validate.py", line 52, in main
    errors = validate(io)
  File "/home/firma/devel/pynwb/src/pynwb/form/utils.py", line 356, in func_call
    return func(**parsed['args'])
  File "/home/firma/devel/pynwb/src/pynwb/__init__.py", line 175, in validate
    return validator.validate(builder)
  File "/home/firma/devel/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/home/firma/devel/pynwb/src/pynwb/form/validate/validator.py", line 227, in validate
    return validator.validate(builder)
  File "/home/firma/devel/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/home/firma/devel/pynwb/src/pynwb/form/validate/validator.py", line 293, in validate
    for sub_val in self.__vmap.valid_types(dt):
  File "/home/firma/devel/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/home/firma/devel/pynwb/src/pynwb/form/validate/validator.py", line 194, in valid_types
    raise_from(ValueError("no children for '%s'" % spec), None)
  File "<string>", line 3, in raise_from
ValueError: no children for 'Epoch'
```
