### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by CellAssembly** [NeurodataWithoutBorders/pynwb#131]
Hello,

I tried "pip install nwb" and got the error below regarding the license.txt file.

Thank you,

Yazan

---------------------------------------------------------------------------------------------------------------------
```
>>pip install pynwb
Downloading/unpacking pynwb
  Downloading pynwb-0.1.tar.gz (88kB): 88kB downloaded
  Running setup.py (path:/tmp/pip_build_yazanb/pynwb/setup.py) egg_info for package pynwb
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_yazanb/pynwb/setup.py", line 16, in <module>
        with open('license.txt') as f:
    IOError: [Errno 2] No such file or directory: 'license.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_yazanb/pynwb/setup.py", line 16, in <module>

    with open('license.txt') as f:

IOError: [Errno 2] No such file or directory: 'license.txt'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_yazanb/pynwb
Storing debug log for failure in /home/.pip/pip.log

```

**Comment by nicain** [comment]
pip install nwb or pip install pynwb?

**Comment by CellAssembly** [comment]
pip install pynwb... sorry about that

**Comment by jcfr** [comment]
Thanks for the report.

We ll address this shortly.

Jc

**Comment by neuromusic** [comment]
btw, congrats on your first issue @CellAssembly 🎉 😄

**Comment by dorukozturk** [comment]
This is fixed now
