### ISSUE TITLE
Test suite error with Python3.9: AssertionError: UserWarning not triggered

### ISSUE THREAD

**Issue by tillea** [NeurodataWithoutBorders/pynwb#1329]
## Description

I tried to upgrade the Debian packaged pynwb to version 1.4 (in the hope that the test suite error of version 1.3 that is documented in a [Debian bug](https://bugs.debian.org/978257) might be fixed.  Unfortunately the same two failures occurre also with the latest version 1.4.

## Steps to Reproduce

Running the build time test suite with python3.9 results in

    ======================================================================
    FAIL: test_catch_dup_name (tests.unit.test_extension.TestCatchDupNS)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/build/pynwb-1.4.0/.pybuild/cpython3_3.9_pynwb/build/tests/unit/test_extension.py", line 172, in test_catch_dup_name
        type_map.load_namespaces(os.path.join(self.tempdir, self.ns_path2))
    AssertionError: UserWarning not triggered

    ======================================================================
    FAIL: test_simple (tests.unit.test_file.TestCacheSpec)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/build/pynwb-1.4.0/.pybuild/cpython3_3.9_pynwb/build/tests/unit/test_file.py", line 471, in test_simple
        nwbfile = reader.read()
    AssertionError: UserWarning not triggered

    ----------------------------------------------------------------------
    Ran 337 tests in 75.857s

    FAILED (failures=2)
    E: pybuild pybuild:353: test: plugin distutils failed with: exit code=1: cd /build/pynwb-1.4.0/.pybuild/cpython3_3.9_pynwb/build; python3.9 -m unittest discover -v

## Environment

    Python Executable: Python
    Python Version: Python 3.9
    Operating System: Linux (Debian unstable)
    HDMF Version: Sorry, no idea.  Just building the Debian package the build log of [Debian bug](https://bugs.debian.org/978257)  might tell you

Kind regards, Andreas.

**Comment by bendichter** [comment]
@tillea thanks for the bug report. I don't think we support 3.9 yet. You can see what versions of python are supported [here](https://pypi.org/project/pynwb/) on the left panel. Would you be able to work with Python 3.8 instead?

**Comment by tillea** [comment]
On Mon, Jan 04, 2021 at 05:58:44AM -0800, Ben Dichter wrote:
> @tillea thanks for the bug report. I don't think we support 3.9 yet. Would you be able to work with Python 3.8 instead?

No sorry, Debian 11 will be released with Python3.9 only.  It would be really great if you could sort this out.
Kind regards, Andreas.

**Comment by bendichter** [comment]
@tillea I've never used Debian, but would it be possible to use conda to create a Python 3.8 environment? If so, that's what I would recommend. 

Last I checked some of our dependencies still hadn't made the update to Python 3.9 on all of our supported operating systems, and we can't make the update until they do. The situation may have changed now. We'll look into it.

**Comment by tillea** [comment]
On Mon, Jan 04, 2021 at 06:19:10AM -0800, Ben Dichter wrote:
> @tillea I've never used Debian, but would it be possible to use conda to create a Python 3.8 environment? If so, that's what I would recommend. 
Users surely can use Conda under Debian.  But if we are talking about a plain Debian package, no, that's not helpful.

> Last I checked some of our dependencies still hadn't made the update to Python 3.9 on all of our supported operating systems, and we can't make the update until they do. The situation may have changed now. We'll look into it.
Thanks a lot, Andreas.

**Comment by rly** [comment]
The two test failures are fixed in https://github.com/NeurodataWithoutBorders/pynwb/pull/1325 . We will make a new release of PyNWB that includes these changes soon (target: end of January).

**Comment by tillea** [comment]
On Tue, Jan 05, 2021 at 04:59:25PM -0800, Ryan Ly wrote:
> The two test failures are fixed in https://github.com/NeurodataWithoutBorders/pynwb/pull/1325 . We will make a new release of PyNWB that includes these changes soon (target: end of January).

Thanks a lot.  It would be great if you would ping me once such a release has happened.
Kind regards, Andreas.

**Comment by yarikoptic** [comment]
@rly is release with all the goodness'es is coming?
