### ISSUE TITLE
[Bug]: Cannot read file with SpatialSeries with >3 columns

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1479]
### What happened?

An existing NWB file has four columns in its `SpatialSeries` objects. They represent (x1, y1, x2, y2) according to the description. This is technically valid according to NWB 2.0-2.4 but is invalid according to the upcoming NWB 2.5 and dev branch of pynwb. 

### Steps to Reproduce

```python
# create an NWB file using PyNWB 2.0.1 with a SpatialSeries with 4 columns
# and read it with the latest PyNWB dev branch
```

### Traceback

```python
c:\users\ryan\documents\nwb\hdmf\src\hdmf\spec\namespace.py:532: UserWarning: Ignoring cached namespace 'hdmf-common' version 1.1.3 because version 1.5.1 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
c:\users\ryan\documents\nwb\hdmf\src\hdmf\spec\namespace.py:532: UserWarning: Ignoring cached namespace 'core' version 2.2.2 because version 2.5.0-alpha is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
>>> nwbfile = io.read()
Traceback (most recent call last):
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1248, in construct
    obj = self.__new_container__(cls, builder.source, parent, builder.attributes.get(self.__spec.id_key()),
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1258, in __new_container__
    obj.__init__(**kwargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 592, in func_call
    pargs = _check_args(args, kwargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 585, in _check_args
    raise ExceptionType(msg)
ValueError: SpatialSeries.__init__: incorrect shape for 'data' (got '(32658, 4)', expected '((None,), (None, 1), (None, 2), (None, 3))')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\backends\hdf5\h5tools.py", line 447, in read
    return call_docval_func(super().read, kwargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 434, in call_docval_func
    return func(*fargs, **fkwargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 593, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\backends\io.py", line 42, in read
    container = self.__manager.construct(f_builder)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 593, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\manager.py", line 280, in construct
    result = self.__type_map.construct(builder, self, None)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 593, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\manager.py", line 794, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 593, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1218, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1147, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1198, in __get_sub_builders
    ret.update(self.__get_subspec_values(sub_builder, subspec, manager))
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1147, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1190, in __get_sub_builders
    sub_builder = self.__flatten(sub_builder, subspec, manager)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1203, in __flatten
    tmp = [manager.construct(b) for b in sub_builder]
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1203, in <listcomp>
    tmp = [manager.construct(b) for b in sub_builder]
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 593, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\manager.py", line 276, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 593, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\manager.py", line 794, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 593, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1218, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1147, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1190, in __get_sub_builders
    sub_builder = self.__flatten(sub_builder, subspec, manager)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1203, in __flatten
    tmp = [manager.construct(b) for b in sub_builder]
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1203, in <listcomp>
    tmp = [manager.construct(b) for b in sub_builder]
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 593, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\manager.py", line 276, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 593, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\manager.py", line 794, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 593, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1218, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1147, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1190, in __get_sub_builders
    sub_builder = self.__flatten(sub_builder, subspec, manager)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1203, in __flatten
    tmp = [manager.construct(b) for b in sub_builder]
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1203, in <listcomp>
    tmp = [manager.construct(b) for b in sub_builder]
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 593, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\manager.py", line 276, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 593, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\manager.py", line 794, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\utils.py", line 593, in func_call
    return func(args[0], **pargs)
  File "c:\users\ryan\documents\nwb\hdmf\src\hdmf\build\objectmapper.py", line 1252, in construct
    raise ConstructError(builder, msg) from ex
hdmf.build.errors.ConstructError: (root/processing/behavior/position/series_0 GroupBuilder {'attributes': {'comments': 'no comments', 'description': 'xloc, yloc, xloc2, yloc2', 'namespace': 'core', 'neurodata_type': 'SpatialSeries', 'object_id': 'ef3e30b4-ca68-4e0f-aa1a-71d93e0adbc0'}, 'groups': {}, 'datasets': {'data': root/processing/behavior/position/series_0/data DatasetBuilder {'attributes': {'conversion': 0.00055, 'resolution': -1.0, 'unit': 'meters'}, 'data': <HDF5 dataset "data": shape (32658, 4), type "<i2">}, 'reference_frame': root/processing/behavior/position/series_0/reference_frame DatasetBuilder {'attributes': {}, 'data': 'Description defining what the zero-position is'}, 'timestamps': root/processing/behavior/position/series_0/timestamps DatasetBuilder {'attributes': {'interval': 1, 'unit': 'seconds'}, 'data': <HDF5 dataset "timestamps": shape (32658,), type "<f8">}}, 'links': {}}, "Could not construct SpatialSeries object due to: SpatialSeries.__init__: incorrect shape for 'data' (got '(32658, 4)', expected '((None,), (None, 1), (None, 2), (None, 3))')")
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.9

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by bendichter** [comment]
OK, but these files won't pass validation

**Comment by rly** [comment]
Right. The files won't pass validation with the new schema. Based on what we have laid out right now in the [compatibility policy](https://www.nwb.org/versioning-and-compatibility/), we would have to push PyNWB to 3.0 if it cannot read files written by PyNWB 2. Ideally, PyNWB can read all files written with NWB schema 2+. With previous breaking changes, we could convert the non-compliant data to a compliant form (e.g., scalar experimenter to list of experimenters) in the object mapper, but this one is not so straightforward.

As a stopgap, I propose we raise a warning saying that a SpatialSeries with >3 columns is non-compliant. Then, when we are ready to do a major release of PyNWB to 3.0, we can enforce it with an error.

**Comment by oruebel** [comment]
> As a stopgap, I propose we raise a warning saying that a SpatialSeries with >3 columns is non-compliant. Then, when we are ready to do a major release of PyNWB to 3.0, we can enforce it with an error.

@rly I'm not sure if this is easily possible, but I think if we could: 1) raise a warning when reading a file (so that files remain readable) but 2) raise an error when a user creates a new SpatialSeries (to prevent creation of new bad data, then that would solve both issues (maintaining readability of old files while enforcing compliance with the updated schema). I'm not sure what the right way to implement this logic is. For now, the warning logic you added is fine, but we should create an issue to make sure we either change it to an error in the future.
