### ISSUE TITLE
[Bug]: pynwb.validate gives IndexError: Index (0) out of range for empty dimension

### ISSUE THREAD

**Issue by dervinism** [NeurodataWithoutBorders/pynwb#1569]
### What happened?

I get the following error when attempting to validate any NWB file no matter the data that I save or don't save inside the file:
```
IndexError: Index (0) out of range for empty dimension
```
You can download the file using this [link](https://drive.google.com/file/d/1SuBSLjv6QheArbDcYsj9SDIQbUeXknWK/view?usp=sharing).

### Steps to Reproduce

```python
python3 -m pynwb.validate ./nnx_derived_data_nwb/M190114_A_MD/ecephys_session_01.nwb
```

### Traceback

```python
Validating ./nnx_derived_data_nwb/M190114_A_MD/ecephys_session_01.nwb against cached namespace information using namespace 'core'.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/martynas/.local/lib/python3.10/site-packages/pynwb/validate.py", line 137, in <module>
    main()
  File "/home/martynas/.local/lib/python3.10/site-packages/pynwb/validate.py", line 131, in main
    ret = ret or _validate_helper(io=io, namespace=ns)
  File "/home/martynas/.local/lib/python3.10/site-packages/pynwb/validate.py", line 24, in _validate_helper
    errors = validate(**kwargs)
  File "/home/martynas/.local/lib/python3.10/site-packages/hdmf/utils.py", line 649, in func_call
    return func(**pargs)
  File "/home/martynas/.local/lib/python3.10/site-packages/pynwb/__init__.py", line 198, in validate
    return validator.validate(builder)
  File "/home/martynas/.local/lib/python3.10/site-packages/hdmf/utils.py", line 645, in func_call
    return func(args[0], **pargs)
  File "/home/martynas/.local/lib/python3.10/site-packages/hdmf/validate/validator.py", line 248, in validate
    return validator.validate(builder)
  File "/home/martynas/.local/lib/python3.10/site-packages/hdmf/utils.py", line 645, in func_call
    return func(args[0], **pargs)
  File "/home/martynas/.local/lib/python3.10/site-packages/hdmf/validate/validator.py", line 423, in validate
    errors.extend(self.__validate_children(builder))
  File "/home/martynas/.local/lib/python3.10/site-packages/hdmf/validate/validator.py", line 449, in __validate_children
    yield from self.__validate_child_builder(child_spec, child_builder, parent_builder)
  File "/home/martynas/.local/lib/python3.10/site-packages/hdmf/validate/validator.py", line 498, in __validate_child_builder
    yield from child_validator.validate(child_builder)
  File "/home/martynas/.local/lib/python3.10/site-packages/hdmf/utils.py", line 645, in func_call
    return func(args[0], **pargs)
  File "/home/martynas/.local/lib/python3.10/site-packages/hdmf/validate/validator.py", line 423, in validate
    errors.extend(self.__validate_children(builder))
  File "/home/martynas/.local/lib/python3.10/site-packages/hdmf/validate/validator.py", line 449, in __validate_children
    yield from self.__validate_child_builder(child_spec, child_builder, parent_builder)
  File "/home/martynas/.local/lib/python3.10/site-packages/hdmf/validate/validator.py", line 498, in __validate_child_builder
    yield from child_validator.validate(child_builder)
  File "/home/martynas/.local/lib/python3.10/site-packages/hdmf/utils.py", line 645, in func_call
    return func(args[0], **pargs)
  File "/home/martynas/.local/lib/python3.10/site-packages/hdmf/validate/validator.py", line 386, in validate
    dtype = get_type(data)
  File "/home/martynas/.local/lib/python3.10/site-packages/hdmf/validate/validator.py", line 127, in get_type
    return get_type(data[0])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/martynas/.local/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 814, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home/martynas/.local/lib/python3.10/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 276, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 151, in h5py._selector.Selector.apply_args
IndexError: Index (0) out of range for empty dimension
```

### Operating System

Linux

### Python Executable

Python

### Python Version

3.10

### Package Versions

[environment_for_issue.txt](https://github.com/NeurodataWithoutBorders/pynwb/files/9809483/environment_for_issue.txt)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by CodyCBakerPhD** [comment]
Looks to me like it's because the `related_publications` field in the `general` file information is specified, but empty. If I manually remove this from the file (attached) it passes validation without issue.

I'd say this message could be way more informative however, though I'm unsure about the right level at which to try to fix this (PyNWB? HDMF?): to those more knowledgeable @oruebel @rly, it's simply because there's a Dataset attribute of the NWB file that exists but has empty shape.

[ecephys_session_01_related_pub_removed.zip](https://github.com/NeurodataWithoutBorders/pynwb/files/9814417/ecephys_session_01_related_pub_removed.zip)

**Comment by oruebel** [comment]
@rly what do you think, should this be fixed in HDMF or PyNWB?

**Comment by dervinism** [comment]
That worked. Thanks!

**Comment by rly** [comment]
@CodyCBakerPhD @oruebel this is an HDMF issue. I started an issue ticket. @CodyCBakerPhD if you have some bandwidth, it would be great if you could look into it!

**Comment by oruebel** [comment]
Closing this issue here since this issue will be addressed in HDMF https://github.com/hdmf-dev/hdmf/issues/775
