### ISSUE TITLE
[Bug]: python 3.11 ros3 gallery tests failing

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1764]
### What happened?

See https://github.com/NeurodataWithoutBorders/pynwb/actions/runs/5907604795/job/16025806623

```
2023-08-18 22:28:10,019 - INFO - Executing /home/runner/work/pynwb/pynwb/docs/gallery/advanced_io/streaming.py
======================================================================
2023-08-18 22:28:11,095 - WARNING - A newer version (0.56.0) of dandi/dandi-cli is available. You are using 0.55.1
[1. 1. 1. ... 1. 1. 1.]
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/ros3/lib/python3.11/site-packages/hdmf/build/objectmapper.py", line 1256, in construct
    obj = self.__new_container__(cls, builder.source, parent, builder.attributes.get(self.__spec.id_key()),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/ros3/lib/python3.11/site-packages/hdmf/build/objectmapper.py", line 1269, in __new_container__
    obj.__init__(**kwargs)
  File "/usr/share/miniconda/envs/ros3/lib/python3.11/site-packages/hdmf/utils.py", line 644, in func_call
    return func(args[0], **pargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/pynwb/pynwb/src/pynwb/misc.py", line 174, in __init__
    super().__init__(**kwargs)
  File "/usr/share/miniconda/envs/ros3/lib/python3.11/site-packages/hdmf/utils.py", line [64](https://github.com/NeurodataWithoutBorders/pynwb/actions/runs/5907604795/job/16025806623#step:7:65)4, in func_call
    return func(args[0], **pargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/ros3/lib/python3.11/site-packages/hdmf/common/table.py", line 429, in __init__
    tmp.extend(indices[name])
               ~~~~~~~^^^^^^
KeyError: 'quality'
```

### Steps to Reproduce

```python
See tests
```

### Operating System

Linux

### Python Executable

Python

### Python Version

3.11

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by rly** [comment]
I re-ran the test and it passed. Might have been a weird streaming fluke.
