### ISSUE TITLE
Unclear how to add electrodes / bug in nwbf.add_electrode

### ISSUE THREAD

**Issue by lfrank** [NeurodataWithoutBorders/pynwb#195]
First, the current documentation doesn't really explain how to add electrodes (presumably one uses the add_electrode function of NWBFile).

Second, calling that function returns the following
```
Traceback (most recent call last):
  File "/Users/loren/Src/NWB/franklabnwb/convert_nspike.py", line 402, in <module>
    nwbf.add_electrode(tet_ind + 1, coord[0],coord[1], coord[2],np.nan, location, filtering, description, electrode_group[day][tet_ind+1])
  File "/Users/loren/anaconda3/lib/python3.6/site-packages/pynwb-0.post1273+g851f171-py3.6.egg/pynwb/form/utils.py", line 289, in func_call
  File "/Users/loren/anaconda3/lib/python3.6/site-packages/pynwb-0.post1273+g851f171-py3.6.egg/pynwb/file.py", line 360, in add_electrode
AttributeError: 'NWBFile' object has no attribute 'electrodes'
```

**Comment by oruebel** [comment]
@lfrank the refactoring of the organization of the electrode metadata via the ElectrodeTable was added very recently so the documentation may still be a bit behind on this. 

@ajtritt can you take a look at the bug.

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/NeurodataWithoutBorders/pynwb/commit/3a03d4ae63d81d3eb25c1d78d091756db919c659

Cc: @neuromusic  @lfrank @oruebel @ajtritt 

See also https://github.com/NeurodataWithoutBorders/pynwb/issues/260#issuecomment-344694677
