### ISSUE TITLE
Python 3to2 conversion notes

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#20]
Originally reported by: **Oliver Ruebel (Bitbucket: [oruebel](https://bitbucket.org/oruebel), GitHub: [oruebel](https://github.com/oruebel))**

----------------------------------------

When using 3to2 to convert pynwb from Python 3 to2 we see the following issues in the unit tests:

# test_io.TestNested.test_register #

This test seems to fail for several reasons. 1) 3to2 somehow removes the "@self.type_map.neurodata_type('MyNWBContainer')" decorator from the local calls MyNWBContainterMap and 2) because something seems to fail with the registration itself.

======================================================================
FAIL: test_register (test_io.TestNested)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oruebel/Devel/nwb/test_pynwb_py3to2/tests/unit/test_io.py", line 79, in test_register
    self.assertIsInstance(cls, MyNWBContainerMap)
AssertionError: <pynwb.io.build.map.ObjectMapper object at 0x10a5e7cd0> is not an instance of <class 'test_io.MyNWBContainerMap'>

----------------------------------------------------------------------

# core.__type_ok(...) #

The following tests appear to fail because validation of str vs unicode does not happen properly after applying 3to2:

======================================================================
ERROR: test_override (test_io.TestNested)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oruebel/Devel/nwb/test_pynwb_py3to2/tests/unit/test_io.py", line 85, in test_override
    builder = self.type_map.build(container_inst, self.build_manager)
  File "/Users/oruebel/Devel/nwb/test_pynwb_py3to2/pynwb/io/build/map.py", line 76, in build
    attr_map = self.get_map(container)
  File "/Users/oruebel/Devel/nwb/test_pynwb_py3to2/pynwb/io/build/map.py", line 60, in get_map
    spec = self.__catalog.get_spec(ndt)
  File "/Users/oruebel/Devel/nwb/test_pynwb_py3to2/pynwb/core.py", line 214, in func_call
    raise TypeError(u', '.join(parse_err))
TypeError: incorrect type for 'obj_type' (got 'str', expected 'unicode or type')

======================================================================
ERROR: test_register (test_io.TestNested)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oruebel/Devel/nwb/test_pynwb_py3to2/tests/unit/test_io.py", line 78, in test_register
    cls = self.type_map.get_map(container_inst)
  File "/Users/oruebel/Devel/nwb/test_pynwb_py3to2/pynwb/io/build/map.py", line 60, in get_map
    spec = self.__catalog.get_spec(ndt)
  File "/Users/oruebel/Devel/nwb/test_pynwb_py3to2/pynwb/core.py", line 214, in func_call
    raise TypeError(u', '.join(parse_err))
TypeError: incorrect type for 'obj_type' (got 'str', expected 'unicode or type')

======================================================================
ERROR: test_default_mapping (test_io.TestUnNested)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/oruebel/Devel/nwb/test_pynwb_py3to2/tests/unit/test_io.py", line 48, in test_default_mapping
    builder = self.type_map.build(container_inst, self.build_manager)
  File "/Users/oruebel/Devel/nwb/test_pynwb_py3to2/pynwb/io/build/map.py", line 76, in build
    attr_map = self.get_map(container)
  File "/Users/oruebel/Devel/nwb/test_pynwb_py3to2/pynwb/io/build/map.py", line 60, in get_map
    spec = self.__catalog.get_spec(ndt)
  File "/Users/oruebel/Devel/nwb/test_pynwb_py3to2/pynwb/core.py", line 214, in func_call
    raise TypeError(u', '.join(parse_err))
TypeError: incorrect type for 'obj_type' (got 'str', expected 'unicode or type')

----------------------------------------------------------------------

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/20

**Comment by oruebel** [comment]
Superseded by issue #59
