### ISSUE TITLE
ci: pre-release packages fail to be uploaded

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#211]
pre-release packages fail to be uploaded.

It fails with the following message:

```
Checking if HEAD is a release tag
Checking if HEAD is a release tag - no (creating prerelease)

release latest: already exists

uploading 'latest' release asset(s) (found 3):
  uploading dist/pynwb-0.post1311+g936c438-py2-none-any.whl
  download_url: https://github.com/NeurodataWithoutBorders/pynwb/releases/download/latest/pynwb-0.post1311.g936c438-py2-none-any.whl

  uploading dist/pynwb-0.post1311+g936c438.tar.gz
  download_url: https://github.com/NeurodataWithoutBorders/pynwb/releases/download/latest/pynwb-0.post1311.g936c438.tar.gz

  uploading dist/pynwb-0.post1311+g936c438-py3-none-any.whl
  download_url: https://github.com/NeurodataWithoutBorders/pynwb/releases/download/latest/pynwb-0.post1311.g936c438-py3-none-any.whl

updating 'latest' release: 
  target_commitish: '7921bb62e3b3240226acf66a57535219b9c3abac' -> 'master'
  tag_name: 'latest' -> 'latest-tmp'

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/anyci/publish_github_release.py", line 443, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/anyci/publish_github_release.py", line 436, in main
    _upload_prerelease(args)
  File "/usr/local/lib/python2.7/dist-packages/anyci/publish_github_release.py", line 346, in _upload_prerelease
    target_commitish=sha
  File "/usr/local/lib/python2.7/dist-packages/github_release.py", line 116, in with_check_for_credentials
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/github_release.py", line 497, in gh_release_edit
    patch_release(repo_name, current_tag_name, **attributes)
  File "/usr/local/lib/python2.7/dist-packages/github_release.py", line 344, in patch_release
    dry_run
  File "/usr/local/lib/python2.7/dist-packages/github_release.py", line 314, in _update_release_sha
    dry_run=dry_run)
  File "/usr/local/lib/python2.7/dist-packages/github_release.py", line 374, in patch_release
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/NeurodataWithoutBorders/pynwb/releases/8256394
Exited with code 1
```

Source: https://circleci.com/gh/NeurodataWithoutBorders/pynwb/359

### Steps to Reproduce
```
mkvirtualenv pynwb
cd pynwb
pip install tox
rm -rf dist/*
tox -e py27
tox -e py35
export GITHUB_TOKEN=xxxxxxxxxxxxxxxxxxxxx # Token for nw-bot
ci_addons publish_github_release NeurodataWithoutBorders/pynwb \
  --prerelease-packages "dist/*" \
  --exit-success-if-missing-token \
  --re-upload
```
### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Any
- **Python Version:** Any
- **Operating System:**  NA
- **Pynwb Version:** dev

**Comment by jcfr** [comment]
@dorukozturk I am looking at this

**Comment by jcfr** [comment]
@dorukozturk I am looking at this

**Comment by jcfr** [comment]
There is now a [new release](https://pypi.python.org/pypi/githubrelease/1.5.7) of github-release.

Issues has been identified, script [publish-github-release-py](http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#publish-github-release-py) is being updated, tests added and a release of `scikit-ci-addons` will be out shortly.

**Comment by dorukozturk** [comment]
@jcfr What was the issue?

**Comment by jcfr** [comment]
Two things:

* the Exception was not informative. The new version of scikit-ci-addons will address that by ensuring an informative message is reported. In a nutshell, it was raised because the integration branch was incorrect and the default of `master` is not good. Specifying ``--prerelease-sha dev`` fixes this.

* specifying the `--prerelease-packages-clear-pattern` and `--prerelease-packages-keep-pattern` is also needed to ensure older development packages are deleted.

I will update circleci shortly.

**Comment by dorukozturk** [comment]
@jcfr Should we close this now?

**Comment by jcfr** [comment]
xref #222
