### ISSUE TITLE
 test_write_cache_spec failure on python 3.5 following integration of #242

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#247]
### Steps to Reproduce
```
tox -e py35
```

```
ERROR: test_write_cache_spec (test_io.TestHDF5Writer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jcfr/Projects/pynwb/tests/integration/test_io.py", line 108, in test_write_cache_spec
    HDF5IO.load_namespaces(ns_catalog, self.path, namespaces=['core'])
  File "/home/jcfr/Projects/pynwb/.tox/py35/lib/python3.5/site-packages/pynwb/form/utils.py", line 306, in func_call
    return func(self, **parsed['args'])
  File "/home/jcfr/Projects/pynwb/.tox/py35/lib/python3.5/site-packages/pynwb/form/backends/hdf5/h5tools.py", line 63, in load_namespaces
    namespace_catalog.load_namespaces('namespace', reader=reader)
  File "/home/jcfr/Projects/pynwb/.tox/py35/lib/python3.5/site-packages/pynwb/form/utils.py", line 306, in func_call
    return func(self, **parsed['args'])
  File "/home/jcfr/Projects/pynwb/.tox/py35/lib/python3.5/site-packages/pynwb/form/spec/namespace.py", line 362, in load_namespaces
    namespaces = reader.read_namespace(namespace_path)
  File "/home/jcfr/Projects/pynwb/.tox/py35/lib/python3.5/site-packages/pynwb/form/backends/hdf5/h5tools.py", line 703, in read_namespace
    ret = self.__read(ns_path)
  File "/home/jcfr/Projects/pynwb/.tox/py35/lib/python3.5/site-packages/pynwb/form/backends/hdf5/h5tools.py", line 696, in __read
    d = json.loads(s)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

```

### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Python
- **Python Version:** Python 3.5
- **Operating System:**  Linux
- **Pynwb Version:**  https://github.com/NeurodataWithoutBorders/pynwb/commit/4220402eb6564e9257c0164f9004f42d1449cced

**Comment by nicain** [comment]
I think I know what’s going on here @ajtritt you have this one? I fixed up similar errors with “decode”

**Comment by jcfr** [comment]
I have a fix. Pushing now

**Comment by jcfr** [comment]
xref https://github.com/NeurodataWithoutBorders/pynwb/pull/248

**Comment by jcfr** [comment]
Fixed in https://github.com/NeurodataWithoutBorders/pynwb/commit/50fa07482f2c0d1efaec05338194b3b2d86737ee
