### ISSUE TITLE
ci: Address remaining issue related to wheel publishing on GitHub

### ISSUE THREAD

**Issue by jcfr** [NeurodataWithoutBorders/pynwb#274]
See https://circleci.com/gh/NeurodataWithoutBorders/pynwb/840

```
deleting 'latest' release asset(s) (matched: 2, matched-but-keep: 2, not-matched: 0):

resolved 'dev' to '1a5cb588adf533a504ed8b433339cd7a43e418d8'
deleting reference refs/tags/latest-tmp
Traceback (most recent call last):
  File "/home/circleci/venv/lib/python2.7/site-packages/anyci/publish_github_release.py", line 544, in <module>
    main()
  File "/home/circleci/venv/lib/python2.7/site-packages/anyci/publish_github_release.py", line 537, in main
    _upload_prerelease(args)
  File "/home/circleci/venv/lib/python2.7/site-packages/anyci/publish_github_release.py", line 437, in _upload_prerelease
    target_commitish=sha
  File "/home/circleci/venv/lib/python2.7/site-packages/github_release.py", line 116, in with_check_for_credentials
    return func(*args, **kwargs)
  File "/home/circleci/venv/lib/python2.7/site-packages/github_release.py", line 497, in gh_release_edit
    patch_release(repo_name, current_tag_name, **attributes)
  File "/home/circleci/venv/lib/python2.7/site-packages/github_release.py", line 344, in patch_release
    dry_run
  File "/home/circleci/venv/lib/python2.7/site-packages/github_release.py", line 314, in _update_release_sha
    dry_run=dry_run)
  File "/home/circleci/venv/lib/python2.7/site-packages/github_release.py", line 337, in patch_release
    release = get_release_info(repo_name, current_tag_name)
  File "/home/circleci/venv/lib/python2.7/site-packages/github_release.py", line 272, in get_release_info
    raise Exception('Release with tag_name {0} not found'.format(tag_name))
Exception: Release with tag_name latest not found
Exited with code 1
```

**Comment by jcfr** [comment]
Cc: @dorukozturk

**Comment by dorukozturk** [comment]
@jcfr Yes, I realized that. Did i mess up the tagging?

**Comment by bendichter** [comment]
@dorukozturk I'm going to close this. Please re-open if this is a mistake.
