### ISSUE TITLE
NWBNamespaceBuilder fails

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#33]
Originally reported by: **Loren Frank (Bitbucket: [lmfrnk](https://bitbucket.org/lmfrnk), GitHub: Unknown)**

----------------------------------------

```
#!python

from pynwb.spec import NWBGroupSpec, NWBNamespaceBuilder

# create a builder for the namespace
ns_builder = NWBNamespaceBuilder("Frank Laboratory NWB Extensions", "franklab", version='0.1')
```

fails with the following error:

Users/loren/anaconda3/bin/python /Users/loren/Src/NWB/franklabnwb/fl_extensions.py
Traceback (most recent call last):
  File "/Users/loren/Src/NWB/franklabnwb/fl_extensions.py", line 4, in <module>
    ns_builder = NWBNamespaceBuilder("Frank Laboratory NWB Extensions", "franklab", version='0.1')
  File "/Users/loren/Src/NWB/pynwb/src/form/utils.py", line 231, in func_call
    return func(self, **parsed['args'])
  File "/Users/loren/Src/NWB/pynwb/src/pynwb/spec.py", line 173, in __init__
    args.insert(NWBNamespace)
TypeError: insert() takes exactly 2 arguments (1 given)

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/33

**Comment by ajtritt** [comment]
*Original comment by* **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**:

----------------------------------------

Merged in ns_builder_fix (pull request #62)

Fix Issue #33
