### ISSUE TITLE
writing nwb file with position data fails

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#34]
Originally reported by: **Loren Frank (Bitbucket: [lmfrnk](https://bitbucket.org/lmfrnk), GitHub: Unknown)**

----------------------------------------

Traceback (most recent call last):
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/hdf5/h5tools.py", line 280, in __scalar_fill__
    dset = parent.require_dataset(name, data=data, shape=None, dtype=dtype)
  File "/Users/loren/anaconda3/lib/python3.6/site-packages/h5py/_hl/group.py", line 136, in require_dataset
    raise TypeError("Shapes do not match (existing %s vs new %s)" % (dset.shape, shape))
TypeError: Shapes do not match (existing () vs new None)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/loren/Src/NWB/franklabnwb/convert_nspike.py", line 486, in <module>
    io.write(nwbf)
  File "/Users/loren/Src/NWB/pynwb/src/form/utils.py", line 231, in func_call
    return func(self, **parsed['args'])
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/io.py", line 25, in write
    self.write_builder(f_builder)
  File "/Users/loren/Src/NWB/pynwb/src/form/utils.py", line 231, in func_call
    return func(self, **parsed['args'])
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/hdf5/h5tools.py", line 116, in write_builder
    write_group(self.__file, name, gbldr.groups, gbldr.datasets, gbldr.attributes, gbldr.links)
  File "/Users/loren/Src/NWB/pynwb/src/form/utils.py", line 238, in func_call
    return func(**parsed['args'])
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/hdf5/h5tools.py", line 157, in write_group
    builder.links)
  File "/Users/loren/Src/NWB/pynwb/src/form/utils.py", line 238, in func_call
    return func(**parsed['args'])
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/hdf5/h5tools.py", line 157, in write_group
    builder.links)
  File "/Users/loren/Src/NWB/pynwb/src/form/utils.py", line 238, in func_call
    return func(**parsed['args'])
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/hdf5/h5tools.py", line 157, in write_group
    builder.links)
  File "/Users/loren/Src/NWB/pynwb/src/form/utils.py", line 238, in func_call
    return func(**parsed['args'])
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/hdf5/h5tools.py", line 164, in write_group
    builder.get('attributes'))
  File "/Users/loren/Src/NWB/pynwb/src/form/utils.py", line 238, in func_call
    return func(**parsed['args'])
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/hdf5/h5tools.py", line 251, in write_dataset
    dset = __scalar_fill__(parent, name, data)
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/hdf5/h5tools.py", line 282, in __scalar_fill__
    raise Exception("Could not create scalar dataset %s in %s" % (name, parent.name)) from exc
Exception: Could not create scalar dataset reference_frame in /processing/Behavior Module/Position/Position Data

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/34

**Comment by ajtritt** [comment]
*Original comment by* **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**:

----------------------------------------

Hi Loren,

This looks like a problem when trying to create a file that already exists. I added some logic to deal with this. Please update and let me know if you still get this error.

Andrew

**Comment by ajtritt** [comment]
*Original comment by* **Loren Frank (Bitbucket: [lmfrnk](https://bitbucket.org/lmfrnk), GitHub: Unknown)**:

----------------------------------------

Great; I’ll test it out as soon as I can and get back to you…

Loren
--
Loren M. Frank

Professor  
Howard Hughes Medical Institute
Kavli Institute for Fundamental Neuroscience
Department of Physiology 
University of California, San Francisco
Office Phone: 415-502-7357

>

**Comment by ajtritt** [comment]
*Original comment by* **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**:

----------------------------------------

From Loren:

Traceback (most recent call last):
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/hdf5/h5tools.py", line 327, in __list_fill__
    data_dtype = __get_type(data)
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/hdf5/h5tools.py", line 221, in __get_type
    raise ValueError('cannot determine type for empty data')
ValueError: cannot determine type for empty data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/loren/Src/NWB/franklabnwb/convert_nspike.py", line 492, in <module>
    io.write(nwbf)
  File "/Users/loren/Src/NWB/pynwb/src/form/utils.py", line 231, in func_call
    return func(self, **parsed['args'])
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/io.py", line 25, in write
    self.write_builder(f_builder)
  File "/Users/loren/Src/NWB/pynwb/src/form/utils.py", line 231, in func_call
    return func(self, **parsed['args'])
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/hdf5/h5tools.py", line 120, in write_builder
    write_group(self.__file, name, gbldr.groups, gbldr.datasets, gbldr.attributes, gbldr.links)
  File "/Users/loren/Src/NWB/pynwb/src/form/utils.py", line 238, in func_call
    return func(**parsed['args'])
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/hdf5/h5tools.py", line 161, in write_group
    builder.links)
  File "/Users/loren/Src/NWB/pynwb/src/form/utils.py", line 238, in func_call
    return func(**parsed['args'])
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/hdf5/h5tools.py", line 168, in write_group
    builder.get('attributes'))
  File "/Users/loren/Src/NWB/pynwb/src/form/utils.py", line 238, in func_call
    return func(**parsed['args'])
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/hdf5/h5tools.py", line 261, in write_dataset
    dset = __list_fill__(parent, name, data)
  File "/Users/loren/Src/NWB/pynwb/src/form/backends/hdf5/h5tools.py", line 329, in __list_fill__
    raise Exception('cannot add %s to %s - could not determine type' % (name, parent.name)) from exc
Exception: cannot add tags to /epochs/day 3 - could not determine type

Process finished with exit code 1

**Comment by ajtritt** [comment]
*Original comment by* **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**:

----------------------------------------

Merged in issue_34 (pull request #67)

fixing issue #34 and issue #35
