### ISSUE TITLE
parallel io

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#362]
## Feature Request

The basic necessity is to add arguments to `NWBHDF5IO` and similar utilities to facilitate opening an NWB file with MPI and ensure that data can be read/written in parallel.

In addition, we would like to implement parallel reading/writing tools for NWB. We have developed similar tools in [neuroh5](https://bitbucket.org/ivan_raikov/neuroh5/src).

**Comment by bendichter** [comment]
```python
from mpi4py import MPI
import h5py

from pynwb.form.backends.hdf5.h5tools import HDF5IO
from pynwb import NWBHDF5IO, NWBFile, TimeSeries
from datetime import datetime

fname = 'test_parallel_pynwb.nwb'

rank = MPI.COMM_WORLD.rank  # The process ID (integer 0-3 for 4-process run)

if not rank:
    nwbfile = NWBFile('aa', 'aa', datetime.now().astimezone())
    nwbfile.add_acquisition(TimeSeries('ts_name', description='desc', data=[1, 2, 3, 4], rate=100., unit='m'))
    with NWBHDF5IO(fname, 'w') as io:
        io.write(nwbfile)

MPI.COMM_WORLD.Barrier()

with h5py.File(fname, 'a', driver='mpio', comm=MPI.COMM_WORLD) as f:
    with HDF5IO(fname, 'a', comm=MPI.COMM_WORLD, file=f) as io:
            nwbfile = io.read()
            nwbfile.acquisition['ts_name'].data[rank] = rank
```

```python
/home/users/bdichter/code/pynwb/src/pynwb/form/build/map.py:915: MissingRequiredWarning: dataset 'data' for 'ts_name' of type (TimeSeries)
  warnings.warn(msg, MissingRequiredWarning)
Traceback (most recent call last):
  File "test_parallel_pynwb.py", line 20, in <module>
    with HDF5IO('test_parallel_pynwb.nwb', 'a', comm=MPI.COMM_WORLD, file=f) as io:
  File "/home/users/bdichter/code/pynwb/src/pynwb/form/utils.py", line 379, in func_call
    raise_from(ExceptionType(msg), None)
  File "<string>", line 3, in raise_from
TypeError: incorrect type for 'comm' (got 'Intracomm', expected 'Intracom')
Traceback (most recent call last):
  File "test_parallel_pynwb.py", line 20, in <module>
    with HDF5IO('test_parallel_pynwb.nwb', 'a', comm=MPI.COMM_WORLD, file=f) as io:
  File "/home/users/bdichter/code/pynwb/src/pynwb/form/utils.py", line 379, in func_call
    raise_from(ExceptionType(msg), None)
  File "<string>", line 3, in raise_from
TypeError: incorrect type for 'comm' (got 'Intracomm', expected 'Intracom')
Traceback (most recent call last):
  File "test_parallel_pynwb.py", line 20, in <module>
    with HDF5IO('test_parallel_pynwb.nwb', 'a', comm=MPI.COMM_WORLD, file=f) as io:
  File "/home/users/bdichter/code/pynwb/src/pynwb/form/utils.py", line 379, in func_call
    raise_from(ExceptionType(msg), None)
  File "<string>", line 3, in raise_from
TypeError: incorrect type for 'comm' (got 'Intracomm', expected 'Intracom')
Traceback (most recent call last):
  File "test_parallel_pynwb.py", line 20, in <module>
    with HDF5IO('test_parallel_pynwb.nwb', 'a', comm=MPI.COMM_WORLD, file=f) as io:
  File "/home/users/bdichter/code/pynwb/src/pynwb/form/utils.py", line 379, in func_call
    raise_from(ExceptionType(msg), None)
  File "<string>", line 3, in raise_from
TypeError: incorrect type for 'comm' (got 'Intracomm', expected 'Intracom')
```

**Comment by bendichter** [comment]
Using #831, I get the following error:

```python
Traceback (most recent call last):
  File "test_parallel_pynwb.py", line 21, in <module>
    nwbfile = io.read()
  File "/home/users/bdichter/code/pynwb/src/pynwb/form/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/home/users/bdichter/code/pynwb/src/pynwb/form/backends/io.py", line 33, in read
    container = self.__manager.construct(f_builder)
  File "/home/users/bdichter/code/pynwb/src/pynwb/form/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/home/users/bdichter/code/pynwb/src/pynwb/form/build/map.py", line 195, in construct
    result = self.__type_map.construct(builder, self)
  File "/home/users/bdichter/code/pynwb/src/pynwb/form/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/home/users/bdichter/code/pynwb/src/pynwb/form/build/map.py", line 1557, in construct
    attr_map = self.get_map(builder)
  File "/home/users/bdichter/code/pynwb/src/pynwb/form/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/home/users/bdichter/code/pynwb/src/pynwb/form/build/map.py", line 1486, in get_map
    data_type = self.get_builder_dt(obj)
  File "/home/users/bdichter/code/pynwb/src/pynwb/form/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/home/users/bdichter/code/pynwb/src/pynwb/form/build/map.py", line 1394, in get_builder_dt
    raise ValueError(msg)
ValueError: builder 'root' does not have a data_type
```
