### ISSUE TITLE
NWBHDF5IO "with statement"

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#363]
## Feature Request
I'd like`NWBHDF5IO` to also operate as a python context, i.e. with a "`with` statement." This would ensure that the hdf5 file is properly closed even if there is a exception in `io.write()`, and it's considered better practice when dealing with opening and closing files (`h5py` does this as well the python standard lib).

this:
```python
io = NWBHDF5IO('test.nwb', mode='w')
io.write(nwbfile)
io.close()
```

would turn into this:
```python
with NWBHDF5IO('test.nwb', mode='w') as io:
    io.write(nwbfile)
```

**Comment by bendichter** [comment]
It looks like there was an attempt at this but it's not working:

```python
Traceback (most recent call last):
  File "/Users/bendichter/dev/to_nwb/neuroscope2nwb.py", line 258, in <module>
    io.write(nwbfile)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 129, in write
    call_docval_func(super(HDF5IO, self).write, kwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 230, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/io.py", line 39, in write
    self.write_builder(f_builder)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 274, in write_builder
    self.open()
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 266, in open
    self.__file = File(self.__path, open_flag)
  File "/Users/bendichter/anaconda3/lib/python3.6/site-packages/h5py-2.6.0-py3.6-macosx-10.7-x86_64.egg/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/Users/bendichter/anaconda3/lib/python3.6/site-packages/h5py-2.6.0-py3.6-macosx-10.7-x86_64.egg/h5py/_hl/files.py", line 98, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.create
OSError: Unable to create file (Unable to truncate a file which is already open)
```

**Comment by ajtritt** [comment]
@bendichter can you provide a gist with the code that exposed this bug?

**Comment by bendichter** [comment]
@ajtritt sure:

```python
from datetime import datetime
from pynwb import NWBFile, NWBHDF5IO

fname = 'YutaMouse41-150903'
fpath = '/Users/bendichter/Desktop/Buzsaki/SenzaiBuzsaki2017/YutaMouse41-150903'
session_description = 'simulated MEC and LEC data'
identifier = fname
session_start_time = datetime(2015, 7, 31)
institution = 'NYU'
lab = 'Buzsaki'

source=fname
nwbfile = NWBFile(source, session_description, identifier,
                  session_start_time, datetime.now(),
                  institution=institution, lab=lab)


with NWBHDF5IO('test3.nwb', mode='w') as io:
    io.write(nwbfile)
```
