### ISSUE TITLE
unable to append nwbfile

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#384]
## Bug

I cannot write new data to an nwbfile that already exists.

### Steps to Reproduce
```python
from pynwb import load_namespaces, get_class, NWBHDF5IO, NWBFile, TimeSeries
from datetime import datetime

fname = 'test.nwb'

nwbfile = NWBFile(source='source',
                  session_description='session_description',
                  identifier='identifier',
                  session_start_time=datetime.now(),
                  file_create_date=datetime.now(),
                  institution='institution',
                  lab='lab')

ts = TimeSeries(name='name', source='source', data=[1,2,3],
                unit='na', rate=1.0, starting_time=0.0)
ts2 = TimeSeries(name='name2', source='source', data=[4,5,6],
                unit='na', rate=1.0, starting_time=0.0)

nwbfile.add_acquisition(ts)

with NWBHDF5IO(fname,'w') as io:
    io.write(nwbfile)
with NWBHDF5IO(fname,'a') as io:
    nwbfile = io.read()
    nwbfile.add_acquisition(ts2)
    io.write(nwbfile)
```

error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-179-b921d35e8afd> in <module>()
     24     nwbfile = io.read()
     25     nwbfile.add_acquisition(ts2)
---> 26     io.write(nwbfile)

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    346                     msg = ', '.join(parse_err)
    347                     raise_from(TypeError(msg), None)
--> 348                 return func(self, **parsed['args'])
    349         else:
    350             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in write(self, **kwargs)
    126     def write(self, **kwargs):
    127         cache_spec = getargs('cache_spec', kwargs)
--> 128         call_docval_func(super(HDF5IO, self).write, kwargs)
    129         if cache_spec:
    130             ref = self.__file.attrs.get(SPEC_LOC_ATTR)

~/dev/pynwb/src/pynwb/form/utils.py in call_docval_func(func, kwargs)
    228 def call_docval_func(func, kwargs):
    229     fargs, fkwargs = fmt_docval_args(func, kwargs)
--> 230     return func(*fargs, **fkwargs)
    231 
    232 

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    346                     msg = ', '.join(parse_err)
    347                     raise_from(TypeError(msg), None)
--> 348                 return func(self, **parsed['args'])
    349         else:
    350             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/backends/io.py in write(self, **kwargs)
     38         container = getargs('container', kwargs)
     39         f_builder = self.__manager.build(container, source=self.__source)
---> 40         self.write_builder(f_builder)
     41 
     42     @abstractmethod

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    346                     msg = ', '.join(parse_err)
    347                     raise_from(TypeError(msg), None)
--> 348                 return func(self, **parsed['args'])
    349         else:
    350             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in write_builder(self, **kwargs)
    266         f_builder = getargs('builder', kwargs)
    267         for name, gbldr in f_builder.groups.items():
--> 268             self.write_group(self.__file, gbldr)
    269         for name, dbldr in f_builder.datasets.items():
    270             self.write_dataset(self.__file, dbldr)

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    346                     msg = ', '.join(parse_err)
    347                     raise_from(TypeError(msg), None)
--> 348                 return func(self, **parsed['args'])
    349         else:
    350             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in write_group(self, **kwargs)
    401 
    402         parent, builder = getargs('parent', 'builder', kwargs)
--> 403         group = parent.create_group(builder.name)
    404         # write all groups
    405         subgroups = builder.groups

~/anaconda3/lib/python3.6/site-packages/h5py-2.6.0-py3.6-macosx-10.7-x86_64.egg/h5py/_hl/group.py in create_group(self, name)
     47         with phil:
     48             name, lcpl = self._e(name, lcpl=True)
---> 49             gid = h5g.create(self.id, name, lcpl=lcpl)
     50             return Group(gid)
     51 

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5g.pyx in h5py.h5g.create()

ValueError: Unable to create group (Name already exists)
```

### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda
- **Python Version:**  Python 3.6
- **Operating System:** macOS 
- **Pynwb Version:** latest

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by bendichter** [comment]
I tried making the following adjustment to h5tools line 270, but it didn't work:
```python
for name, gbldr in f_builder.groups.items():
    if gbldr.name not in self.__file:
        self.write_group(self.__file, gbldr)
for name, dbldr in f_builder.datasets.items():
    if dbldr.name not in self.__file:
        self.write_dataset(self.__file, dbldr)
```

**Comment by bendichter** [comment]
@oruebel and @ajtritt any ideas about how to progress on this issue? Having the ability to append new datasets and append data to an existing dataset is going to be very useful for several of the labs I'm working with.

**Comment by ajtritt** [comment]
Builders probably need to be marked as written, so HDF5IO knows what to write.

**Comment by oruebel** [comment]
For datasets I think this can be "hacked" right now because you can **1)** enforce that a dataset gets chunked and can be expanded by wrapping it with H5DataIO and setting the maxshape (and chunking) **2)** you have access to the h5py.Dataset after read. E.g., the following seems to work, although I think this might be more of a hack than an intended function:

```
# Create some example data
from datetime import datetime
from pynwb import NWBFile

start_time = datetime(2017, 4, 3, 11, 0, 0)
create_date = datetime(2017, 4, 15, 12, 0, 0)

nwbfile = NWBFile('PyNWB tutorial', 'demonstrate NWBFile basics', 'NWB123', start_time,
                  file_create_date=create_date)

from pynwb import TimeSeries
from pynwb.form.backends.hdf5.h5_utils import H5DataIO

data = H5DataIO(data=list(range(100, 200, 10)), maxshape=(None,))  # Make sure the HDF5 dataset can be exbanded
timestamps =  H5DataIO(data=list(range(10)), maxshape=(None,))     # Make sure the HDF5 dataset can be exbanded
test_ts = TimeSeries('test_timeseries', 'PyNWB tutorial', data, 'SIunit', timestamps=timestamps)
nwbfile.add_acquisition(test_ts)

# Write the data to file
from pynwb import NWBHDF5IO
io = NWBHDF5IO('basic_example.nwb', 'w')
io.write(nwbfile)
io.close()

# Read teh data back in
io = NWBHDF5IO('basic_example.nwb')
nwbfile = io.read()
ts = nwbfile.get_acquisition('test_timeseries')
print("Current data")
print("Data:" , ts.data[:])
print("Timestamps", ts.timestamps[:])

# Expand the HDF5 datasets
ts.data.resize((20,))
ts.timestamps.resize((20,))
ts.data[10:] = list(range(10))
ts.timestamps[10:] = list(range(10,20,1))
# Close and reopen the file to confirm the data was written
io.close()
del(nwbfile)

# Read the data back in to confirm the expansion worked
io = NWBHDF5IO('basic_example.nwb')
nwbfile = io.read()
ts = nwbfile.get_acquisition('test_timeseries')
print("Data:" , ts.data[:])
print("Timestamps", ts.timestamps[:])
```

**Comment by bendichter** [comment]
Nice! At some point we might want to make a workflow that doesn't interface directly with the HDF5 objects to allow for other backends, but it's nice to know there's a way to hack it currently. That's one down... for now.

Now is there a way to add a dataset to a file? Andrew, was your comment about that issue?

**Comment by ajtritt** [comment]
@bendichter No, my comment was regarding appending whole objects (e.g. a new TimeSeries) to a file.
This requires tracking of what was read and what's been written

I'm working on this on this branch https://github.com/NeurodataWithoutBorders/pynwb/tree/enh/append

**Comment by bendichter** [comment]
Cool, thanks for working on this!

**Comment by ajtritt** [comment]
@oruebel FYI, this is still causing an error: 

```python
Traceback (most recent call last):
  File "bug.py", line 26, in <module>
    io.write(nwbfile)
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 177, in write
    call_docval_func(super(HDF5IO, self).write, kwargs)
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/utils.py", line 229, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/backends/io.py", line 39, in write
    f_builder = self.__manager.build(container, source=self.__source)
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/build/map.py", line 141, in build
    result = self.__type_map.build(container, self, builder=result, source=source)
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/build/map.py", line 1185, in build
    builder = attr_map.build(container, manager, builder=builder, source=getargs('source', kwargs))
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/build/map.py", line 582, in build
    self.__add_groups(builder, self.__spec.groups, container, manager, source)
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/build/map.py", line 705, in __add_groups
    self.__add_groups(sub_builder, spec.groups, container, build_manager, source)
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/build/map.py", line 721, in __add_groups
    self.__add_containers(builder, spec, attr_value, build_manager, source, container)
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/build/map.py", line 751, in __add_containers
    self.__add_containers(builder, spec, container, build_manager, source, parent_container)
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/build/map.py", line 739, in __add_containers
    builder.set_link(LinkBuilder(rendered_obj, parent=builder))
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/build/builders.py", line 282, in set_link
    self.__set_builder(builder, GroupBuilder.__link)
  File "/Users/ajtritt/neuro/nwb/help_desk/append/pynwb/src/pynwb/form/build/builders.py", line 213, in __set_builder
    raise KeyError("'%s' already exists as %s" % (name, self.obj_type[name]))
KeyError: "'name' already exists as groups"
```

**Comment by bendichter** [comment]
It looks like the "append" branch is now gone. What's the status of this?

**Comment by bendichter** [comment]
@ajtritt 

I was visiting the Bouchard lab today and this issue came up. Do you have any ideas for how this might be done? Perhaps a solution to put `container` into the `my_mod` group of  `'test_append.nwb'` might look like this:

```python

container = TimeSeries(...)
with NWBHDF5IO('test_append.nwb','a') as io:
    nwbfile = io.read()
    group = nwbfile.processing['my_mod']
    io.append(group, container)
```
