### ISSUE TITLE
Cannot get PyNWB version using pkg_resources when using conda

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#40]
Originally reported by: **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**

----------------------------------------

```
import pynwb
print(pynwb)
import pkg_resources
print(pkg_resources.get_distribution('pynwb').version)
```

produces the following:

```
/local1/anaconda2/envs/pynwb/bin/python /data/mat/nicholasc/pynwb/nicholasc/sandbox.py
<module 'pynwb' from '/data/mat/nicholasc/pynwb/src/pynwb/__init__.py'>
Traceback (most recent call last):
  File "/data/mat/nicholasc/pynwb/nicholasc/sandbox.py", line 7, in <module>
    print(pkg_resources.get_distribution('pynwb').version)
  File "/local1/anaconda2/envs/pynwb/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 557, in get_distribution
  File "/local1/anaconda2/envs/pynwb/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 431, in get_provider
  File "/local1/anaconda2/envs/pynwb/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 968, in require
  File "/local1/anaconda2/envs/pynwb/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 854, in resolve
pkg_resources.DistributionNotFound: The 'pynwb' distribution was not found and is required by the application

Process finished with exit code 1
```

from Nicholas Cain:

"The pynwb module is definitely in the python path, but pkg_resources can't find it
setuptools v27.2.0, python 3.6.1 (anaconda)"

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/pynwb/issue/40

**Comment by dorukozturk** [comment]
```

**Comment by dorukozturk** [comment]
```
import pynwb
print(pynwb)
import pkg_resources
print(pkg_resources.get_distribution('pynwb').version)
```
This produced:
```
0.2.0
```
When I installed it with:
```
conda install -c conda-forge pynwb
```
@nicain Can you try to install again with the above method?

**Comment by dorukozturk** [comment]
I think this is fixed. Feel free to reopen if problem occurs again.
