### ISSUE TITLE
Fix read the docs builds

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/pynwb#402]
Read the docs is not building again.

**Comment by jcfr** [comment]
While readthedocs doesn't try to [build the latest version of h5py from source](https://readthedocs.org/projects/pynwb/builds/6927062/), it now fails with the [following error](https://readthedocs.org/projects/pynwb/builds/6927653/):

```
Installing collected packages: sphinx, certifi, numpy, h5py, python-dateutil
  Found existing installation: Sphinx 1.7.2
    Uninstalling Sphinx-1.7.2:
      Successfully uninstalled Sphinx-1.7.2
  Found existing installation: certifi 2018.1.18
    Uninstalling certifi-2018.1.18:
      Successfully uninstalled certifi-2018.1.18
  Found existing installation: python-dateutil 2.7.0
    Uninstalling python-dateutil-2.7.0:
      Successfully uninstalled python-dateutil-2.7.0
Successfully installed certifi-2017.11.5 h5py-2.7.1 numpy-1.14.0 python-dateutil-2.6.1 sphinx-1.6.5
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynwb/envs/dev/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynwb/envs/dev/lib/python3.5/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynwb/envs/dev/lib/python3.5/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynwb/envs/dev/lib/python3.5/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynwb/envs/dev/lib/python3.5/site-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynwb/envs/dev/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynwb/envs/dev/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynwb/envs/dev/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynwb/envs/dev/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynwb/envs/dev/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynwb/envs/dev/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynwb/envs/dev/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/pynwb/envs/dev/lib/python3.5/site-packages/python_dateutil-2.7.0-py3.5.egg'
```

**Comment by jcfr** [comment]
We could also try to mock some of the dependencies. See http://read-the-docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by jcfr** [comment]
Updating `python-dateutil` to `2.7.0` addressed this issue, documentation is now generated again.
