### ISSUE TITLE
epoch fails to write

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#407]
```python
import os
from datetime import datetime
from pynwb import NWBFile, NWBHDF5IO, TimeSeries

nwbfile = NWBFile(source='source',
                  session_description='session_description',
                  identifier='identifier',
                  session_start_time=datetime.now(),
                  file_create_date=datetime.now(),
                  institution='institution',
                  lab='lab')

ts = TimeSeries('a', 'b', data=[1, 2, 3], timestamps=[.1, .2, .3], unit=' ')

nwbfile.create_epoch(start_time=0.0, stop_time=1.0,
                     tags=tuple(), description='a',
                     timeseries=ts)

with NWBHDF5IO('temp.nwb', 'w') as io:
    io.write(nwbfile)
```

error:
```python
Traceback (most recent call last):
  File "/Users/bendichter/dev/to_nwb/test2.py", line 38, in <module>
    io.write(nwbfile)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 135, in write
    call_docval_func(super(HDF5IO, self).write, kwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 230, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/io.py", line 39, in write
    f_builder = self.__manager.build(container, source=self.__source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 37, in build
    result = self.__type_map.build(container, self, source=getargs('source', kwargs))
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1030, in build
    builder = attr_map.build(container, manager, source=getargs('source', kwargs))
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 439, in build
    self.__add_groups(builder, self.__spec.groups, container, manager, source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 572, in __add_groups
    self.__add_containers(builder, spec, attr_value, build_manager, source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 576, in __add_containers
    rendered_obj = build_manager.build(value, source=source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 37, in build
    result = self.__type_map.build(container, self, source=getargs('source', kwargs))
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1030, in build
    builder = attr_map.build(container, manager, source=getargs('source', kwargs))
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 438, in build
    self.__add_datasets(builder, self.__spec.datasets, container, manager, source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 534, in __add_datasets
    self.__add_containers(builder, spec, attr_value, build_manager, source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 576, in __add_containers
    rendered_obj = build_manager.build(value, source=source)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 37, in build
    result = self.__type_map.build(container, self, source=getargs('source', kwargs))
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1030, in build
    builder = attr_map.build(container, manager, source=getargs('source', kwargs))
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 456, in build
    tmp[j] = self.__get_ref_builder(subt.dtype, None, row[j], manager)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 472, in __get_ref_builder
    raise ValueError(msg)
ValueError: 'container' must be of type DataRegion if spec represents region reference
```

**Comment by ajtritt** [comment]
I can across and addressed the same error when working on documentation on enh/sphinx_gallery. This should be fixed when I merge that branch.
