### ISSUE TITLE
roundtrip fail for data convert

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#410]
## 1) Bug

I am working on a conversion script for Losonczy Lab's data. I am able to write a file with the following script:

```python
import os

from datetime import datetime
import numpy as np
from scipy.io import loadmat
import h5py


from pynwb import NWBFile, NWBHDF5IO
from pynwb.ecephys import ElectricalSeries, LFP
from pynwb.ophys import OpticalChannel, TwoPhotonSeries
from pynwb.image import ImageSeries


from neuroscope import get_channel_groups, get_lfp_sampling_rate
from general import gzip

NA = 'THIS REQUIRED ATTRIBUTE INTENTIONALLY LEFT BLANK.'
SHORTEN = True


fpath = '/Users/bendichter/Desktop/Losonczy/from_sebi/example_data'
fpath_base, fname = os.path.split(fpath)
session_description = 'Example data from Sebi'
identifier = fname
session_start_time = datetime(2017, 5, 4)
institution = 'Columbia'
lab = 'Losonczy'


source = fname
nwbfile = NWBFile(source, session_description, identifier,
                  session_start_time, datetime.now(),
                  institution=institution, lab=lab)
all_ts = []

lfp_xml_fpath = os.path.join(fpath, 'LFP', 'svr009_Day2_FOV1_170504_131823.xml')
channel_groups = get_channel_groups(lfp_xml_fpath)
lfp_channels = channel_groups[0]
lfp_fs = get_lfp_sampling_rate(lfp_xml_fpath)
nchannels = sum(len(x) for x in channel_groups)

eeg_file = os.path.join(fpath, 'LFP/svr009_Day2_FOV1_170504_131823.eeg')
all_channels = np.fromfile(eeg_file, dtype=np.int16).reshape(-1, nchannels)
lfp_signal = all_channels[:, lfp_channels]

device_name = 'LFP device'
device = nwbfile.create_device(device_name, source=source)
electrode_group = nwbfile.create_electrode_group(
    name=device_name + '_electrodes',
    source=fname + '.xml',
    description=device_name,
    device=device,
    location='unknown')

for channel in channel_groups[0]:
    nwbfile.add_electrode(channel,
                          np.nan, np.nan, np.nan,  # position?
                          imp=np.nan,
                          location='unknown',
                          filtering='unknown',
                          description='lfp electrode {}'.format(channel),
                          group=electrode_group)


lfp_table_region = nwbfile.create_electrode_table_region(list(range(4)),
                                                         'lfp electrodes')

lfp_elec_series = ElectricalSeries('lfp', 'lfp',
                                   gzip(lfp_signal),
                                   lfp_table_region,
                                   conversion=np.nan,
                                   starting_time=0.0,
                                   rate=lfp_fs,
                                   resolution=np.nan)

nwbfile.add_acquisition(LFP(source=source, electrical_series=lfp_elec_series))




optical_channel = OpticalChannel(
    name='Optical Channel',
    source=NA,
    description=NA,
    emission_lambda=NA,
)

imaging_plane = nwbfile.create_imaging_plane('my_imgpln',
                                             'Ca2+ imaging example',
                                             optical_channel,
                                             'a very interesting part of the brain',
                                             'imaging_device_1',
                                             '6.28', '2.718', 'GFP', 'my favorite brain location',
                                             (1, 2, 1, 2, 3), 4.0, 'manifold unit', 'A frame to refer to')

imaging_h5_filepath = '/Users/bendichter/Desktop/Losonczy/from_sebi/example_data/TSeries-05042017-001_Cycle00001_Element00001.h5'


with h5py.File(imaging_h5_filepath, 'r') as f:
    if SHORTEN:
        imaging_data = f['imaging'][:100, ...]
    else:
        imaging_data = f['imaging'][:]

image_series = TwoPhotonSeries(name='test_iS', source='Ca2+ imaging example', dimension=[2],
                               data=imaging_data, imaging_plane=imaging_plane,
                               starting_frame=[0], timestamps=[1,2,3], scan_line_rate=np.nan,
                               pmt_gain=np.nan)
nwbfile.add_acquisition(image_series)




out_fname = 'sebi_data.nwb'
print('writing NWB file...', end='', flush=True)
with NWBHDF5IO(out_fname, mode='w') as io:
    io.write(nwbfile, cache_spec=False)
print('done.')

print('testing read...', end='', flush=True)
# test read
with NWBHDF5IO(out_fname, mode='r') as io:
    io.read()
print('done.')

f.close()
```

The write works without error, but the read gives the following error:
```python
Traceback (most recent call last):
  File "/Users/bendichter/dev/to_nwb/convert_losonczy.py", line 127, in <module>
    f.close()
  File "/Users/bendichter/anaconda3/lib/python3.6/site-packages/h5py-2.6.0-py3.6-macosx-10.7-x86_64.egg/h5py/_hl/files.py", line 288, in close
    id_list = h5f.get_obj_ids(self.id, ~h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 228, in h5py.h5f.get_obj_ids
ValueError: Not a file id (Not a file id)
```

I get this error in the dev branch as well as the sphinx_gallery branch. I'm working on narrowing this down to minimal code to identify the specific issue. I'm just posting in here now in case anyone might already know what the cause is.

### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda
- **Python Version:** Python 3.6
- **Operating System:**  macOS

**Comment by bendichter** [comment]
whoops my mistake
