### ISSUE TITLE
Round trip doesn't work for CurrentClampStimulusSeries

### ISSUE THREAD

**Issue by campagnola** [NeurodataWithoutBorders/pynwb#416]
Using a `dev` commit from today (b3f1034), I am running into an error when loading an NWB file that contains a CurrentClampStimulusSeries:

```
Traceback (most recent call last):
  File "bugtest.py", line 26, in <module>
    nwbfile = io.read()
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/backends/io.py", line 33, in read
    container = self.__manager.construct(f_builder)
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/build/map.py", line 68, in construct
    result = self.__type_map.construct(builder, self)
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/build/map.py", line 1052, in construct
    return attr_map.construct(builder, build_manager)
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/build/map.py", line 649, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/build/map.py", line 635, in __get_subspec_values
    result = self.__get_subspec_values(sub_builder, subspec, manager)
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/build/map.py", line 635, in __get_subspec_values
    result = self.__get_subspec_values(sub_builder, subspec, manager)
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/build/map.py", line 626, in __get_subspec_values
    val = manager.construct(sub_builder)
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/build/map.py", line 68, in construct
    result = self.__type_map.construct(builder, self)
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/build/map.py", line 1052, in construct
    return attr_map.construct(builder, build_manager)
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/home/luke/work/allen_inst/pynwb/src/pynwb/form/build/map.py", line 677, in construct
    raise_from(Exception(msg), ex)
  File "/home/luke/.local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
Exception: Could not construct CurrentClampStimulusSeries object
    incorrect type for 'electrode' (got 'float32', expected 'IntracellularElectrode'), missing argument 'gain': CurrentClampStimulusSeries (ccss)
``` 

Debugging from map.py line 677 in the stack above, I have:
```
args = ['ccss', u'command', <HDF5 dataset "data": shape (50000,), type "<f8">, u'A', 0.02]
kwargs = {'conversion': 1.0, 'description': u'no description', 'starting_time': 123.6, 'comments': u'no comments', 'rate': 50000.0, 'resolution': 0.0}
```
Possibly related to #406.

### Code to reproduce
```
from datetime import datetime
from pynwb import NWBFile, NWBHDF5IO, TimeSeries
from pynwb.icephys import IntracellularElectrode, CurrentClampStimulusSeries

filename = 'test.nwb'

nwbfile = NWBFile(
    source='roundtrip test', session_description='', identifier='', 
    session_start_time=datetime.now(), file_create_date=datetime.now())

elec = IntracellularElectrode(
    name="elec0", source='', slice='', resistance='', seal='', description='', 
    location='', filtering='', initial_access_resistance='', device='')

ccss = CurrentClampStimulusSeries(
    name="ccss", source="command", data=[1,2,3,4,5], unit='A',
    starting_time=123.6, rate=10e3, electrode=elec, gain=0.02)

nwbfile.add_stimulus(ccss)

io = NWBHDF5IO(filename, 'w')
io.write(nwbfile)
io.close()

io = NWBHDF5IO(filename)
nwbfile = io.read()
ccss2 = nwbfile.get_acquisition('ccss')
```
### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda or Python
- **Python Version:** Python 2.7 or Python 3.6
- **Operating System:** Windows, macOS or Linux
- **Pynwb Version:** Version of Pynwb used

**Comment by ajtritt** [comment]
Try registering the IntracellularElectrode with your NWBFile.

You can do this with your example by inserting the following line after you create the IntracellularElectrode:

`nwbfile.add_ic_electrode(elec)`

You could also replace that line with a call to [NWBFile.create_ic_electrode](http://pynwb.readthedocs.io/en/latest/pynwb.file.html#pynwb.file.NWBFile.create_ic_electrode):

```python
nwbfile.create_ic_electrode(
    name="elec0", source='', slice='', resistance='', seal='', description='', 
    location='', filtering='', initial_access_resistance='', device='')
```

**Comment by t-b** [comment]
@ajtritt If I do that I get

```
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    ccss2 = nwbfile.get_acquisition('ccss')
  File "/home/firma/devel/pynwb/src/pynwb/form/utils.py", line 348, in func_call
    return func(self, **parsed['args'])
  File "/home/firma/devel/pynwb/src/pynwb/core.py", line 463, in _func
    raise ValueError(msg)
ValueError: NWBFile 'root' is empty
```

Could `add_stimulus` call `add_ic_electrode` implicitly`?

**Comment by campagnola** [comment]
Thanks @ajtritt, I get the same as @t-b.
Seems like there are a couple of places where the code could be made more robust here:
* Ensuring that dependent objects are either automatically added to the nwb file or generate an error when the file is written
* In `ObjectMapper.construct`, ensure that `args` is constructed in a reasonable way--because the electrode was missing from the NWB file here, `args` got constructed without that argument, which caused the gain value to be interpreted as the electrode.

I can give this a try, but I'm not confident that I understand how everything is supposed to work yet..

**Comment by ajtritt** [comment]
@t-b 
> Could add_stimulus call add_ic_electrode implicitly`?

It's possible. Code would have to make assumptions, and there might be more devils in the details. I'll poke around code and think about this. I think @campagnola's suggestion of checking will be simpler 

@campagnola 
> - Ensuring that dependent objects are either automatically added to the nwb file or generate an error when the file is written

This is less trivial than it may seem, but I agree that this check should happen. I'll have to think about how to best accomplish this.

> - In ObjectMapper.construct, ensure that args is constructed in a reasonable way--because the electrode was missing from the NWB file here, args got constructed without that argument, which caused the gain value to be interpreted as the electrode.

We can just have `ObjectMapper.construct` pass in positional arguments as keyword arguments.

**Comment by ajtritt** [comment]
Working on https://github.com/NeurodataWithoutBorders/pynwb/tree/bug/ic_electrode to fix this.
