### ISSUE TITLE
how do I create custom classes for extensions?

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#531]
here's what I am trying:

```python
from pynwb.spec import NWBDatasetSpec, NWBNamespaceBuilder, NWBGroupSpec

name = 'test'
ns_path = name + '.namespace.yaml'
ext_source = name + '.extensions.yaml'

test_obj = NWBGroupSpec(
    neurodata_type_def='TestObj',
    doc='test object',
    datasets=[NWBDatasetSpec(name='filler_data', doc='data doc', dtype='int',
                             shape=(None, 1))],
    neurodata_type_inc='NWBDataInterface')

ns_builder = NWBNamespaceBuilder(name + ' extensions', name)
ns_builder.add_spec(ext_source, test_obj)
ns_builder.export(ns_path)



from datetime import datetime

from pynwb import load_namespaces, register_class, NWBFile, NWBHDF5IO
from pynwb.core import NWBDataInterface
from pynwb.form.utils import docval, popargs
from collections import Iterable


# load custom classes
load_namespaces(ns_path)


@register_class('TestObj', 'test')
class TestObj(NWBDataInterface):
    __nwbfields__ = ('filler_data',)

    @docval({'name': 'name', 'type': str, 'doc': 'name'},
            {'name': 'source', 'type': str, 'doc': 'source?'},
            {'name': 'filler_data', 'type': Iterable, 'doc': 'data'})
    def __init__(self, **kwargs):
        name, source, filler_data = popargs('name', 'source', 'filler_data',
                                            kwargs)
        super(TestObj, self).__init__(name, source, **kwargs)


nwbfile = NWBFile(source='0',
                  session_description='0',
                  identifier='0',
                  session_start_time=datetime(1900, 1, 1))

nwbfile.add_acquisition(TestObj(name='name', source='source', filler_data=[1]))

with NWBHDF5IO('test_extension.nwb', 'w') as io:
    io.write(nwbfile, cache_spec=True)

with NWBHDF5IO('test_extension.nwb', 'r') as io:
    io.read()
```

I get this error:
```python
/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py:671: UserWarning: missing required attribute 'filler_data' for 'source'
  warnings.warn("missing required attribute '%s' for '%s'" % (spec.name, builder.name))
/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py:654: UserWarning: missing required attribute 'help' for 'source' of type 'TestObj'
  warnings.warn(msg)
Traceback (most recent call last):
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 817, in construct
    obj = cls(**kwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 322, in func_call
    raise_from(TypeError(msg), None)
  File "<string>", line 3, in raise_from
TypeError: missing argument 'filler_data'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bendichter/dev/to_nwb/test_extension.py", line 55, in <module>
    io.read()
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 323, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/io.py", line 33, in read
    container = self.__manager.construct(f_builder)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 323, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 171, in construct
    result = self.__type_map.construct(builder, self)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 323, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1205, in construct
    return attr_map.construct(builder, build_manager)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 323, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 797, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 783, in __get_subspec_values
    result = self.__get_subspec_values(sub_builder, subspec, manager)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 774, in __get_subspec_values
    val = manager.construct(sub_builder)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 323, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 171, in construct
    result = self.__type_map.construct(builder, self)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 323, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 1205, in construct
    return attr_map.construct(builder, build_manager)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 323, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 821, in construct
    raise_from(Exception(msg), ex)
  File "<string>", line 3, in raise_from
Exception: Could not construct TestObj object

Process finished with exit code 1
```

what am I doing wrong?

**Comment by ajtritt** [comment]
The constructor of TestObj is not setting `filler_data`. When you make the custom class, it's on you to set the fields.

**Comment by bendichter** [comment]
ok so I just needed to add `self.filler_data = filler_data` to `__init__`
