### ISSUE TITLE
saving/loading cached spec

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#541]
Maybe I just don't know how to do it, but I am having trouble loading a cached spec in [this file](https://ucsf.box.com/s/po20z1x12rwqus5gl9vehe13ffjcbcjo).

I've tried:
```python
from pynwb import NWBHDF5IO, load_namespaces, get_type_map
fpath='/Users/bendichter/Desktop/Chang/data/EC125/EC125_B22.nwb'

type_map = get_type_map()
NWBHDF5IO.load_namespaces(type_map.namespace_catalog, fpath)
io = NWBHDF5IO(fpath,'r')
nwbfile = io.read()
```

and I get
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-9f170db56d42> in <module>()
      2 
      3 type_map = get_type_map()
----> 4 NWBHDF5IO.load_namespaces(type_map.namespace_catalog, fpath)
      5 io = NWBHDF5IO(fpath,'r')
      6 nwbfile = io.read()

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in load_namespaces(cls, namespace_catalog, path, namespaces)
     76             ns_group = ns_group[latest_version]
     77             reader = H5SpecReader(ns_group)
---> 78             namespace_catalog.load_namespaces('namespace', reader=reader)
     79         f.close()
     80 

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/spec/namespace.py in load_namespaces(self, **kwargs)
    398         for ns in namespaces:
    399             if ns['name'] in self.__namespaces:
--> 400                 raise KeyError("namespace '%s' already exists" % ns['name'])
    401         # now load specs into namespace
    402         for ns in namespaces:

KeyError: "namespace 'core' already exists"
```

But then if I define namespaces:
```python
from pynwb import NWBHDF5IO, load_namespaces, get_type_map
fpath='/Users/bendichter/Desktop/Chang/data/EC125/EC125_B22.nwb'

type_map = get_type_map()
NWBHDF5IO.load_namespaces(type_map.namespace_catalog, fpath, namespaces=['ecog'])
io = NWBHDF5IO(fpath,'r')
nwbfile = io.read()
```

I get this error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-e78b0c3b6dfa> in <module>()
      3 
      4 type_map = get_type_map()
----> 5 NWBHDF5IO.load_namespaces(type_map.namespace_catalog, fpath, namespaces=['ecog'])
      6 io = NWBHDF5IO(fpath,'r')
      7 nwbfile = io.read()

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py in load_namespaces(cls, namespace_catalog, path, namespaces)
     76             ns_group = ns_group[latest_version]
     77             reader = H5SpecReader(ns_group)
---> 78             namespace_catalog.load_namespaces('namespace', reader=reader)
     79         f.close()
     80 

~/dev/pynwb/src/pynwb/form/utils.py in func_call(*args, **kwargs)
    328                     msg = ', '.join(parse_err)
    329                     raise_from(TypeError(msg), None)
--> 330                 return func(self, **parsed['args'])
    331         else:
    332             def func_call(*args, **kwargs):

~/dev/pynwb/src/pynwb/form/spec/namespace.py in load_namespaces(self, **kwargs)
    401         # now load specs into namespace
    402         for ns in namespaces:
--> 403             ret[ns['name']] = self.__load_namespace(ns, reader, types_key, resolve=resolve)
    404         self.__included_specs[namespace_path] = ret
    405         return ret

~/dev/pynwb/src/pynwb/form/spec/namespace.py in __load_namespace(self, namespace, reader, types_key, resolve)
    350                 if types_key in s:
    351                     dtypes = set(s[types_key])
--> 352                 self.__load_spec_file(reader, s['source'], catalog, dtypes=dtypes, resolve=resolve)
    353                 self.__included_sources.setdefault(ns_name, list()).append(s['source'])
    354             elif 'namespace' in s:

~/dev/pynwb/src/pynwb/form/spec/namespace.py in __load_spec_file(self, reader, spec_source, catalog, dtypes, resolve)
    318             specs = d.get('groups', list())
    319             for spec_dict in specs:
--> 320                 ret.extend(__reg_spec(self.__group_spec_cls, spec_dict))
    321             self.__loaded_specs[spec_source] = ret
    322         return ret

~/dev/pynwb/src/pynwb/form/spec/namespace.py in __reg_spec(spec_cls, spec_dict)
    306                 return
    307             if resolve:
--> 308                 self.__resolve_includes(spec_dict, catalog)
    309             spec_obj = spec_cls.build_spec(spec_dict)
    310             return catalog.auto_register(spec_obj, spec_source)

~/dev/pynwb/src/pynwb/form/spec/namespace.py in __resolve_includes(self, spec_dict, catalog)
    332             if parent_spec is None:
    333                 msg = "Cannot resolve include spec '%s' for type '%s'" % (dt_inc, dt_def)
--> 334                 raise ValueError(msg)
    335             spec_dict[self.__group_spec_cls.inc_key()] = parent_spec
    336         it = chain(spec_dict.get('groups', list()), spec_dict.get('datasets', list()))

ValueError: Cannot resolve include spec 'NWBDataInterface' for type 'CorticalSurface'
```

**Comment by bendichter** [comment]
actually there may be an additional problem. nwbfile with cached spec constructed with the dev branch fail to read at all:

```python
from pynwb import NWBFile, NWBHDF5IO
from datetime import datetime

nwbfile = NWBFile('source', ' ', ' ',
                  datetime.now(), datetime.now(),
                  institution='University of California, San Francisco',
                  lab='Chang Lab')

with NWBHDF5IO('test333.nwb', 'w') as io:
    io.write(nwbfile, cache_spec=True)

with NWBHDF5IO('test333.nwb', 'r') as io:
    io.read(nwbfile)
```

```python
Traceback (most recent call last):
  File "/Users/bendichter/dev/to_nwb/chang/test_trials.py", line 13, in <module>
    io.read(nwbfile)
  File "/Users/bendichter/anaconda3/envs/py2/lib/python2.7/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/anaconda3/envs/py2/lib/python2.7/site-packages/pynwb/form/backends/io.py", line 33, in read
    container = self.__manager.construct(f_builder)
  File "/Users/bendichter/anaconda3/envs/py2/lib/python2.7/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/anaconda3/envs/py2/lib/python2.7/site-packages/pynwb/form/build/map.py", line 171, in construct
    result = self.__type_map.construct(builder, self)
  File "/Users/bendichter/anaconda3/envs/py2/lib/python2.7/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/anaconda3/envs/py2/lib/python2.7/site-packages/pynwb/form/build/map.py", line 1199, in construct
    return attr_map.construct(builder, build_manager)
  File "/Users/bendichter/anaconda3/envs/py2/lib/python2.7/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/anaconda3/envs/py2/lib/python2.7/site-packages/pynwb/form/build/map.py", line 797, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/Users/bendichter/anaconda3/envs/py2/lib/python2.7/site-packages/pynwb/form/build/map.py", line 765, in __get_subspec_values
    subspec = manager.get_subspec(spec, sub_builder)
  File "/Users/bendichter/anaconda3/envs/py2/lib/python2.7/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/anaconda3/envs/py2/lib/python2.7/site-packages/pynwb/form/build/map.py", line 227, in get_subspec
    return self.__type_map.get_subspec(spec, builder)
  File "/Users/bendichter/anaconda3/envs/py2/lib/python2.7/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/anaconda3/envs/py2/lib/python2.7/site-packages/pynwb/form/build/map.py", line 1083, in get_subspec
    dt = self.get_builder_dt(builder)
  File "/Users/bendichter/anaconda3/envs/py2/lib/python2.7/site-packages/pynwb/form/build/map.py", line 1037, in get_builder_dt
    raise ValueError(msg)
ValueError: builder 'specifications' does not have a data_type
```
