### ISSUE TITLE
Adding datasets to NWBFile through extensions

### ISSUE THREAD

**Issue by ageorgou** [NeurodataWithoutBorders/pynwb#553]
This is a question rather than a bug report, so apologies in advance if it should be asked elsewhere.

I would like to store some additional information in an NWB file. In version 1.0 of the standard, we did this with custom datasets; from what I understand, in NWB v2.0 and pyNWB these have been removed in favour of extensions. My question is whether an extension can specify additions to the NWBFile schema, to include new fields. 

First of all, is this even meant to be supported, or should I go about it another way? I would prefer the additional metadata to live in `NWBFile` rather than extend e.g. `TimeSeries`, as it refers to the whole contents of the file. There is also some structure to it, so it makes sense (to me) to have it as a separate dataset rather than convert it to plain text and store it in e.g. `/general/notes`.

I can create the spec for the new dataset (and then write the files for the extension and the namespace, not shown):
```python
header_spec = NWBDatasetSpec(
    "An extension to store raw metadata",
    neurodata_type_def="MyHeader",
    dtype=[
        NWBDtypeSpec('field1', 'Field1', 'text'),
        NWBDtypeSpec('field2', 'Field2', 'text')
    ]
)
```

I can load the new dataset (not shown), instantiate it and assign it to the object representing the NWB file:
```python
@register_class("MyHeader", "my_namespace")
class MyHeader(NWBData):
    pass

nwbf = NWBFile("source", "a file with header data", "NB123A", '2018-06-01T00:00:00')
header = MyHeader("testheader", data=[["a1", "a2"], ["b1", "b2"]])
nwbf.header = header
```

But the contents of `header` are not written out when I write this to disk, whether or not I pass the namespace to `NWBHDF5IO`:
```python
with NWBHDF5IO('out.nwb', 'w', extensions="my_namespace.yaml") as io:
    io.write(nwbf)
```

I feel like I'm missing a step.  My initial idea was to extend the `NWBFile` spec, but there is no equivalent to `NWBDatasetSpec` or `NWBGroupSpec` for `NWBFile`, as far as I can see. Do I need to register a custom `ObjectMapper` so that the dataset is written? And, if so, how do I give its spec, since the extension's `NWBDatasetSpec` is not available in this part of the code? Doing this:

```python
@register_map(NWBFile)
class MyMap(NWBFileMap):
    def __init__(self, spec):
        super(MyMap, self).__init__(spec)
        self.map_spec('header', spec.get_dataset('header'))
```

causes an error on writing:
```python
Traceback (most recent call last):
  File "try_header.py", line 26, in <module>
    io.write(nwbf)
[...snip...]
  File ".../lib/python3.5/site-packages/pynwb/form/utils.py", line 346, in func_call
    raise_from(TypeError(msg), None)
  File "<string>", line 2, in raise_from
TypeError: incorrect type for 'spec' (got 'NoneType', expected 'Spec')
```
(EDIT: Or would updating `__nwbfields__` somehow be enough to use the original `NWBFileMap`?)

This all using `pynwb==0.3.0`.

If this turns out to be doable but not obvious, I am very happy to help explain it in the docs.

Thanks in advance!

**Comment by bendichter** [comment]
@ageorgou this is a good place to post your question and it's a good question. It looks like you got pretty far on your own. I've written extensions but never attempted to do exactly what you describe. I'll see if I can help. 

We'd certainly welcome help with the documentation as well!

**Comment by oruebel** [comment]
Could you post your full script for creating your extension and how you read/write the data. It's not clear to me how your extension integrates with the NWBFile schema. My guess is that when you do:

> nwbf.header = header

that this is just a "monkey patch" of the NWBFile object, i.e., you are simply creating a new attribute on the NWBFile object. Without having a place in the spec, ``nwbf.header`` won't map to an object in the file on write, and hence won't be written. I'm wondering whether it may be more appropriate to add this to ``/general`` via an extension or whether you would need to do an extensions of ``NWBFile`` itself.

**Comment by ageorgou** [comment]
@oruebel Extending `NWBFile` itself was my first intention, but I couldn't find how -- as far as I can see, there is no `NWBFileSpec` (or `NWBContainerSpec`, etc), unless I'm missing something. Is it is possible to add fields to the schema directly? I thought this was not possible in pyNWB, but I may have misunderstood the extensions mechanism!

With NWB v1, this is what we were doing to add the extra `labview_header` field under `/general`:
```
{"fs": {"labview": {

"info": {
    "name": "LabView header storage extension",
    "version": "1.0.0",
    "date": "Feb 16, 2017",
    "author": "Jonathan Cooper",
    "contact": "j.p.cooper@ucl.ac.uk",
    "description": ("NWB extension to store raw metadata from LabView header (.ini) files."
        " While some of this information also maps to standard NWB fields,"
        " it is useful to retain the raw fields for provenance.")
},

"schema": {
    "labview_header": {
        "description": ("LabView header fields represented as a 3-column text array."
            " The columns represent 'Section', 'Field name' and 'Field value'."),
        "data_type": "text",
        # TODO: The actual type used by h5py/numpy can be 'object' because these are variable length strings,
        # so this gives a warning. But 'object isn't a valid type for the NWB API, and text is more appropriate anyway!
        "dimensions": ["total_num_fields", "cols"],
        "cols" : {  # definition of dimension "cols"
            "type": "structure",
            "components": [
                { "alias": "Section",     "unit": "N/A" },
                { "alias": "Field name",  "unit": "N/A" },
                { "alias": "Field value", "unit": "N/A" } ] }
    },
    "/general/": {
        "description": "Extension to core general to add labview_header.",
        "include": {  "labview_header": {}},
    },
}
}}}
```

This is what I'm doing with pyNWB to create the extension:

```python
from pynwb.spec import NWBDatasetSpec, NWBDtypeSpec, NWBNamespaceBuilder


ns_builder = NWBNamespaceBuilder("Extension for Silver Lab", "silverlab")

header_spec = NWBDatasetSpec(
    "An extension to store raw metadata from LabView header (.ini)",
    neurodata_type_def="LabViewHeader",
    dtype=[
        NWBDtypeSpec('section', 'Section', 'text'),
        NWBDtypeSpec('field', 'Field', 'text')
    ]
)

ext_source = 'labview_header.yaml'
ns_builder.add_spec(ext_source, header_spec)

ns_path = 'silverlab.namespace.yaml'
ns_builder.export(ns_path)
```

And then to try to use it:
```python
from pynwb import NWBFile, NWBHDF5IO, load_namespaces, register_class, register_map
from pynwb.core import NWBData
from pynwb.io.file import NWBFileMap


load_namespaces('silverlabnwb/extensions/silverlab.namespace.yaml')


@register_class("LabViewHeader", "silverlab")
class LabViewHeader(NWBData):
    pass


# Adding a new map like this leads to the error described in my original comment
# @register_map(NWBFile)
# class MyMap(NWBFileMap):
#     def __init__(self, spec):
#         super(MyMap, self).__init__(spec)
#         self.map_spec('header', spec.get_dataset('header'))


nwbf = NWBFile("source", "file with maybe header data", "NB123A", '2018-06-01T00:00:00')
header = LabViewHeader("testheader", data=[["a1", "a2"], ["b1", "b2"]])
nwbf.header = header

with NWBHDF5IO('test_out.nwb', 'w', extensions="silverlabnwb/extensions/silverlab.namespace.yaml") as io:
    io.write(nwbf)
```

If I try the above, the written file will not have the extra information from `header`. This isn't entirely unexpected, as I haven't specified where it should come from -- I just can't find how!

The closest thing I can find in the docs is [the notebook for the Meister lab example](https://pynwb.readthedocs.io/en/latest/tutorial_source/convert.html). However, the comments there mention that their extension of the NWB schema to add custom metadata under `/general` had not been implemented yet, and there would be some discussion in a coming Hackathon on how best to do that; I don't know if there has been any progress or update on that?

**Comment by ageorgou** [comment]
I've just come across the [Building API classes](http://pynwb.readthedocs.io/en/latest/building_api.html) which I may have missed before. That suggests that I'd need to:

1. define a subclass of `NWBFile` with appropriate `__nwbfields__`
2. define a new `ObjectMapper` (subclassing `NWBFileMap`) to handle the new field
3. register the map with the new subclass
4. register the new subclass with its definition from the namespace?
5. use the new subclass to instantiate customised NWB files that can correctly hold extra fields

It's step 4 that is throwing me a little: I can't see how to mention the new subclass of `NWBFile` in the extension definition, as there is no spec class (e.g. `NWBContainerSpec`) to use for it. Perhaps it is not necessary though?

Thanks again for the help!

**Comment by bendichter** [comment]
I think I'm struggling with the same issue. I do not know how to, for instance, write an extension to add an additional field to `Subject`. I know how to express this in YAML, but the problem occurs when I try to enter in this new data type into the `NWBFile` constructor. I cannot name my new subject class `Subject` because that would collide with `core.Subject` but the constructor requires that the `subject` argument be of type `Subject`.

**Comment by ageorgou** [comment]
@bendichter I imagine that it's not the name "Subject" that is checked, but whether the object has a compatible type. Here's my understanding of it, which maybe can help -- sorry if it's obvious:

Your new group must be declared to be extending `Subject`. I think this has to be done in two places:
- When writing the spec for it, using `neurodata_type_inc="Subject"`
- When loading the extension and registering the class: I think the registered class should itself be a subclass of `Subject`, for example:

```python
from pynwb.file import NWBFile, Subject  # and other things

@register_class("MySubject", "mynamespace")
class MySubject(Subject):
    pass

subj = MySubject(...)  # whatever arguments you want to pass
nwbf = NWBFile(..., subject=subj)
```

I would imagine that since `MySubject` is just a type of `Subject`, the constructor would not complain -- but I haven't tried it!

I'm also not sure whether this will automatically handle the additional field when you write the file to disk.

That said, how do you define the extension to `Subject`? Do you use `NWBGroupSpec`?

**Comment by bendichter** [comment]
oh yeah, I think I got it! I have successfully written the nwb file. I'll post my script here in case any of it is helpful for you

```python
from pynwb.spec import NWBDatasetSpec, NWBNamespaceBuilder, NWBGroupSpec, NWBAttributeSpec
from pynwb.form.spec import RefSpec
from pynwb import register_class, load_namespaces, NWBFile, NWBHDF5IO
from pynwb.form.utils import docval
from pynwb.file import Subject as original_Subject, NWBContainer


name = 'buzsaki_meta'
ns_path = name + ".namespace.yaml"
ext_source = name + ".extensions.yaml"

surgery = NWBGroupSpec(
    neurodata_type_def='Surgery',
    name='surgery', doc='relevant data for surgery', quantity='?',
    datasets=[NWBDatasetSpec(name='devices', quantity='?',
                             doc='links to implanted/explanted devices',
                             dtype=RefSpec('Device', 'object'))],
    attributes=[
        NWBAttributeSpec(name='start_datetime', doc='datetime in ISO 8601', dtype='text', required=False),
        NWBAttributeSpec(name='end_datetime', doc='datetime in ISO 8601', dtype='text', required=False),
        NWBAttributeSpec(name='weight', required=False, dtype='text',
                         doc='Weight at time of experiment, at time of surgery and at other '
                             'important times'),
        NWBAttributeSpec(name='notes', doc='notes and complications', dtype='text', required=False),
        NWBAttributeSpec(name='anesthesia', doc='anesthesia', dtype='text', required=False),
        NWBAttributeSpec(name='analgesics', doc='analgesics', dtype='text', required=False),
        NWBAttributeSpec(name='antibiotics', doc='antibiotics', dtype='text', required=False),
        NWBAttributeSpec(name='target_anatomy', doc='target anatomy', dtype='text', required=False),
        NWBAttributeSpec(name='room', doc='place where the surgery took place', dtype='text',
                         required=False),
        NWBAttributeSpec(name='type', doc='"chronic" or "acute"', dtype='text', required=False)
    ])

# make virus_injection contained in surgery
virus_injection = NWBGroupSpec(
    neurodata_type_inc='Surgery',
    neurodata_type_def='VirusInjection',
    name='VirusInjection', quantity='?',
    doc='notes about surgery that includes virus injection',
    datasets=[NWBDatasetSpec(name='coordinates', doc='(AP, ML, DV) of virus injection',
                             dtype='float', shape=(3,))],
    attributes=[
        NWBAttributeSpec(name='virus', doc='type of virus', dtype='text'),
        NWBAttributeSpec(name='volume', doc='volume of injecting in nL', dtype='float'),
        NWBAttributeSpec(name='rate', doc='rate of injection (nL/s)',
                         dtype='float', required=False),
        NWBAttributeSpec(name='scheme', doc='scheme of injection', dtype='text', required=False)])


histology = NWBGroupSpec(
    neurodata_type_def='Histology',
    name='Histology',
    doc='information about histology of subject',
    quantity='?',
    attributes=[
        NWBAttributeSpec(name='file_name', doc='filename of histology images', dtype='text'),
        NWBAttributeSpec(name='file_name_ext', doc='filename extension', dtype='text'),
        NWBAttributeSpec(name='imaging_technique',
                         doc='histology imaging technique (e.g. widefield, confocal, etc.)',
                         dtype='text'),
        NWBAttributeSpec(name='slice_plane', doc='[Coronal, Sagital, Transverse, Other]',
                         required=False, dtype='text'),
        NWBAttributeSpec(name='slice_thickness', doc='thickness of slice (um)', dtype='float',
                         required=False),
        NWBAttributeSpec(name='location_along_axis', doc='Axis orthogal to SlicePlane (mm)',
                         dtype='float', required=False),
        NWBAttributeSpec(name='brain_region_target', doc='Allen Institute acronym',
                         dtype='text', required=False),
        NWBAttributeSpec(name='stainings', doc='stainings', dtype='text', required=False),
        NWBAttributeSpec(name='light_source', doc='wavelength of light source in nm',
                         dtype='float', required=False),
        NWBAttributeSpec(name='image_scale', doc='scale of image (pixels/100um)', dtype='float',
                         required=False),
        NWBAttributeSpec(name='scale_bar', doc='size of image scale bar (um)', dtype='float',
                         required=False),
        NWBAttributeSpec(name='post_processing', doc='[Z-stacked, Stiched]', dtype='text',
                         required=False),
        NWBAttributeSpec(name='user', doc='person involved', dtype='text', required=False),
        NWBAttributeSpec(name='notes', doc='anything else', dtype='text', required=False)
    ])


subject = NWBGroupSpec(
    neurodata_type_inc='Subject',
    neurodata_type_def='buz_Subject',
    name='subject',
    doc='information about subject',
    groups=[surgery, histology],
    attributes=[
        NWBAttributeSpec(name='subject_id', required=True, dtype='text',
                         doc='ID of subject (lab convention)'),
        NWBAttributeSpec(
            name='sex', required=False, dtype='text',
            doc='Sex of subject. Options: "M": male, "F": female, "O": other, "U": unknown'),
        NWBAttributeSpec(name='species', doc='Species of subject', dtype='text',
                         required=False),
        NWBAttributeSpec(name='strain', dtype='text', doc='strain of animal',
                         required=False),
        NWBAttributeSpec(name='genotype', dtype='text', doc='genetic line of animal',
                         required=False),
        NWBAttributeSpec(name='date_of_birth', dtype='text', doc='in ISO 8601 format',
                         required=False),
        NWBAttributeSpec(name='date_of_death', dtype='text', doc='in ISO 8601 format',
                         required=False),
        NWBAttributeSpec(name='age', doc='age of subject. No specific format enforced.',
                         dtype='text', required=False),
        NWBAttributeSpec(name='gender', dtype='text', required=False,
                         doc='Gender of subject if different from sex.'),
        NWBAttributeSpec(name='earmark', dtype='text', required=False,
                         doc='Earmark of subject'),
        NWBAttributeSpec(name='weight', required=False, dtype='text',
                         doc='Weight at time of experiment, at time of surgery and at other '
                             'important times')])

OpticalFiber = NWBGroupSpec(
    neurodata_type_inc='Device',
    neurodata_type_def='OpticalFiber',
    name='OpticalFiber',
    doc='Meta-data about optical fiber',
    attributes=[
        NWBAttributeSpec(name='type', doc='model', dtype='text', required=False),
        NWBAttributeSpec(name='core_diameter', doc='in um', dtype='float', required=False),
        NWBAttributeSpec(name='outer_diameter', doc='in um', dtype='float', required=False),
        NWBAttributeSpec(name='microdrive', doc='whether a microdrive was used (0: not used, 1: used)',
                         dtype='uint'),
        NWBAttributeSpec(name='microdrive_lead', doc='um/turn', dtype='float', required=False),
        NWBAttributeSpec(name='microdrive_id', doc='id of microdrive', dtype='int', required=False)
    ]
)

ns_builder = NWBNamespaceBuilder(name + ' extensions', name)

specs = (subject, virus_injection, OpticalFiber)
for spec in specs:
    ns_builder.add_spec(ext_source, spec)
ns_builder.export(ns_path)


def obj2docval(spec):

    args_spec = [
                 {'name': 'help', 'type': str, 'doc': 'help', 'default': 'help'},
                 {'name': 'description', 'type': str, 'doc': 'decription', 'default': '?'}]
    for attrib in spec.attributes:
        if attrib.dtype is 'text':
            _type = str
        else:
            _type = attrib.dtype

        arg_spec = {'name': attrib.name, 'type': _type, 'doc': attrib.doc}
        if not attrib.required:
            arg_spec['default'] = None

        args_spec.append(arg_spec)

    for group in spec.groups:
        arg_spec = {'name': group.name, 'type': group.neurodata_type_def, 'doc': group.doc}
        if group.quantity == '?':
            arg_spec['default'] = None

        args_spec.append(arg_spec)

    return tuple(args_spec)


def get_nwbfields(spec):
    vars = [attrib.name for attrib in spec.attributes] + \
           [attrib.name for attrib in spec.groups] + \
           [attrib.name for attrib in spec.datasets]

    return tuple(vars)

####

load_namespaces(ns_path)

@register_class('buz_Subject', name)
class mySubject(original_Subject):

    __nwbfields__ = get_nwbfields(subject)

    @docval(*obj2docval(subject))
    def __init__(self, **kwargs):

        NWBContainer.__init__(self, name='subject', source='source')

        for attr, val in kwargs.items():
            setattr(self, attr, val)

# load custom classes
ns_path = name + '.namespace.yaml'
ext_source = name + '.extensions.yaml'
load_namespaces(ns_path)

subject = mySubject(subject_id='007', genotype='mouse1', species='mouse', sex='U', help='?')

nwbfile = NWBFile("source", "a file with metadata", "NB123A", '2018-06-01T00:00:00', subject=subject)

fname = 'test_ext.nwb'
with NWBHDF5IO(fname, 'w') as io:
    io.write(nwbfile)
```

**Comment by ajtritt** [comment]
@ageorgou *NWBFile* is a neurodata_type, just like *NWBData*, *NWBContainer*, *TimeSeries*, etc, which means you can extend it in the same manner i.e. using the `neurodata_type_inc` argument. 

After you create your new type *MyHeader*, you will need to extend *NWBFile* and add an instance of this new type.  Something like this:

``` python
new_nwbfile_spec = NWBGroupSpec(
    "An NWBFile with a header",
    neurodata_type_inc="NWBFile",
    neurodata_type_def="HeaderedNWBFile",
    datasets=[
        NWBDatasetSpec('An instance of MyHeader', name='header', neurodata_type_inc="MyHeader"),
    ]
)
```

From here, the options for creating the API class are as described in the docs. The same goes for making the mapper. Using your example, the only thing you would have to change is the call to `register_map`. The class you pass in here should be the class that represents *HeaderedNWBFile*. If you don't do anything fancy in the constructor though (i.e. map between things with the same name), you can forgo making custom mapper. 

For future reference, the error you are seeing:
```
Traceback (most recent call last):
  File "try_header.py", line 26, in <module>
    io.write(nwbf)
[...snip...]
  File ".../lib/python3.5/site-packages/pynwb/form/utils.py", line 346, in func_call
    raise_from(TypeError(msg), None)
  File "<string>", line 2, in raise_from
TypeError: incorrect type for 'spec' (got 'NoneType', expected 'Spec')
```
is caused by this line in the constructor for `MyMap`:
```python
        self.map_spec('header', spec.get_dataset('header'))
```

The argument for spec that gets passed in is the *NWBFile* spec, which has no dataset called 'header'

**Comment by ageorgou** [comment]
@bendichter Great, thanks for that, I see how I can do it now.

@ajtritt Thanks for clarifying that. The sticking point was not realising that `NWBGroupSpec` can be used to extend any `NWBContainer`, I thought it had to be a subclass of `NWBGroup` specifically. And yes, I hadn't managed to track down what gets passed to the `ObjectMapper` constructor and `map_spec`.

I will try this out tomorrow and will close if all goes well (as it should!)

If you think this is a common enough scenario to warrant a tutorial or code sample, I'm more than happy to contribute one, or at least to point it out more explicitly in the docs.

**Comment by ageorgou** [comment]
@oruebel @ajtritt I'm running into some errors when extending `NWBFile`, but I think I've tracked down the reason. Here is a sample script, which doesn't do anything interesting (essentially just redefines `NWBFile`) but still causes a problem; for simplicity, I've put the `load_namespace` call in the same file as the spec definition:

```python
from pynwb import load_namespaces
from pynwb.spec import NWBGroupSpec, NWBNamespaceBuilder

ns_builder = NWBNamespaceBuilder("A pointless extension", "foospace")

foofile_spec = NWBGroupSpec(
    "An NWBFile but with a different name",
    neurodata_type_inc="NWBFile",
    neurodata_type_def="FooFile"
)

# Write extension
file_source = 'foofile.yaml'
ns_path = 'foo.namespace.yaml'
ns_builder.add_spec(file_source, foofile_spec)
ns_builder.export(ns_path)

# Error raised here
load_namespaces(ns_path)
```

The generated files look normal:
```
namespaces:
- doc: A pointless extension
  name: foospace
  schema:
  - namespace: core
  - source: foofile.yaml
```

```
groups:
- doc: An NWBFile but with a different name
  neurodata_type_def: FooFile
  neurodata_type_inc: NWBFile
```

The error is raised from `load_namespaces`:
```python
Traceback (most recent call last):
  File "try_nwbfile_extension.py", line 18, in <module>
    load_namespaces(ns_path)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 355, in func_call
    return func(**parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/__init__.py", line 95, in load_namespaces
    return __TYPE_MAP.load_namespaces(namespace_path)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/build/map.py", line 916, in load_namespaces
    deps = self.__ns_catalog.load_namespaces(namespace_path, resolve)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/namespace.py", line 403, in load_namespaces
    ret[ns['name']] = self.__load_namespace(ns, reader, types_key, resolve=resolve)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/namespace.py", line 352, in __load_namespace
    self.__load_spec_file(reader, s['source'], catalog, dtypes=dtypes, resolve=resolve)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/namespace.py", line 320, in __load_spec_file
    ret.extend(__reg_spec(self.__group_spec_cls, spec_dict))
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/namespace.py", line 310, in __reg_spec
    return catalog.auto_register(spec_obj, spec_source)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/catalog.py", line 99, in auto_register
    ret.extend(self.auto_register(group_spec, source_file))
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/catalog.py", line 99, in auto_register
    ret.extend(self.auto_register(group_spec, source_file))
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/catalog.py", line 99, in auto_register
    ret.extend(self.auto_register(group_spec, source_file))
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/catalog.py", line 90, in auto_register
    self.register_spec(spec, source_file)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/catalog.py", line 44, in register_spec
    raise ValueError("'%s' - cannot overwrite existing specification" % type_name)
ValueError: 'Device' - cannot overwrite existing specification
```

Looking at `SpecCatalog`, [`auto_register`](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/src/pynwb/form/spec/catalog.py#L82) tries to register all sub-group specs in the spec, whether or not they are inherited. I suspect that causes the problem with `Device` (which I imagine is already registered in the core namespace). In contrast, dataset specs are only registered if they are not inherited.

Perhaps this would be better placed in a new issue, however...

**Comment by oruebel** [comment]
@ageorgou can this issue be closed?

**Comment by ageorgou** [comment]
@oruebel The underlying issue is described in #559, so happy to close.

**Comment by MarcinAtNovela** [comment]
@ageorgou Hey, I found your post looking for an example of Data Structure like:
Extention of built-in object e.g. ElectrodeGroup which contains List of my own type: ABC(id, name, ....)
I was trying to use RefSpec(similar way as you did with devices) with no luck as at some point there is no such dtype as ABC acceptable for the nwb? Or maybe I am doing sth wrong? Appreciate your thoughts.
