### ISSUE TITLE
FilteredEphys error on read

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#558]
```python
from pynwb import NWBFile, NWBHDF5IO
from pynwb.ecephys import FilteredEphys, ElectricalSeries
import numpy as np

nwbfile = NWBFile("source", "a file with header data", "NB123A", '2018-06-01T00:00:00')

module_lfp = nwbfile.create_processing_module(
    'lfp', source='source', description='source')

filt_ephys = FilteredEphys(source='source', name='name')

device = nwbfile.create_device('device_name', 'source')
electrode_group = nwbfile.create_electrode_group(
    name='electrode_group_name',
    source='source',
    description='desc',
    device=device,
    location='unknown')

nwbfile.add_electrode(0,
                      np.nan, np.nan, np.nan,  # position?
                      imp=np.nan,
                      location='unknown',
                      filtering='unknown',
                      description='desc',
                      group=electrode_group)

etr = nwbfile.create_electrode_table_region([0], 'etr_name')

for passband in ('theta', 'gamma'):
    electrical_series = ElectricalSeries(name=passband + '_phase',
                                         source='ephys_analysis',
                                         data=[1., 2., 3.],
                                         rate=0.0,
                                         electrodes=etr)
    filt_ephys.add_electrical_series(electrical_series)

module_lfp.add_container(filt_ephys)

with NWBHDF5IO('test.nwb', 'w') as io:
    io.write(nwbfile)

with NWBHDF5IO('test.nwb', 'r') as io:
    io.read()
```

error:
```python
Traceback (most recent call last):
  File "/Users/bendichter/dev/to_nwb/test.py", line 48, in <module>
    io.read()
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/io.py", line 33, in read
    container = self.__manager.construct(f_builder)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 178, in construct
    self.__resolve_parents(result)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 188, in __resolve_parents
    tmp.parent = tmp.parent.resolve()
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 60, in resolve
    if self.matches(candidate):
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 50, in matches
    obj = self.__manager.get_proxy(obj)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 99, in get_proxy
    return self.__get_proxy_container(obj)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/build/map.py", line 117, in __get_proxy_container
    stack.append(tmp.name)
AttributeError: 'Proxy' object has no attribute 'name'
```

if you take out `module_lfp.add_container(filt_ephys)` it runs as expected.

**Comment by bendichter** [comment]
@ajtritt I'm trying to fix this but could use some help figuring out what's causing the bug. What's a Proxy object in this context?

**Comment by bendichter** [comment]
@ajtritt I've narrowed this down. The error occurs when I add 2 electrical_series objects to a processing module. If I add only one, no error. I believe this has to do with multiple links to the electrodes table.

This causes an error:
```python
from pynwb import NWBFile, NWBHDF5IO
from pynwb.ecephys import ElectricalSeries

import numpy as np


nwbfile = NWBFile("source", "a file with header data", "NB123A", '2018-06-01T00:00:00')


module_lfp = nwbfile.create_processing_module(
    'lfp', source='source', description='source')

device = nwbfile.create_device('device_name', 'source')
electrode_group = nwbfile.create_electrode_group(
    name='electrode_group_name',
    source='source',
    description='desc',
    device=device,
    location='unknown')

nwbfile.add_electrode(0,
                      np.nan, np.nan, np.nan,  # position?
                      imp=np.nan,
                      location='unknown',
                      filtering='unknown',
                      description='desc',
                      group=electrode_group)

etr = nwbfile.create_electrode_table_region([0], 'etr_name')

for passband in ('theta', 'gamma'):
    electrical_series = ElectricalSeries(name=passband + '_phase',
                                         source='ephys_analysis',
                                         data=[1., 2., 3.],
                                         rate=0.0,
                                         electrodes=etr)

    module_lfp.add_container(electrical_series)

with NWBHDF5IO('test.nwb', 'w') as io:
    io.write(nwbfile)

with NWBHDF5IO('test.nwb', 'r') as io:
    io.read()
```

but if I change it to `for passband in ('theta',):`, no error
