### ISSUE TITLE
Error when extending NWBFile

### ISSUE THREAD

**Issue by ageorgou** [NeurodataWithoutBorders/pynwb#559]
This came out of #553. It seems that `load_namespaces` does not work if the namespace contains an extension of `NWBFile` (or, I am assuming, an extension of anything with pre-existing Groups).

I think this is because of how groups are registered during namespace loading. Looking at `SpecCatalog`, [`auto_register`](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/src/pynwb/form/spec/catalog.py#L82) tries to register all sub-group specs in the spec, whether or not they are inherited. This gives a clash with the group specs that are already in the core namespace. In contrast, dataset specs are only registered if they are not inherited.

Sample script reproducing this:
```python
from pynwb import load_namespaces
from pynwb.spec import NWBGroupSpec, NWBNamespaceBuilder

ns_builder = NWBNamespaceBuilder("A pointless extension", "foospace")

foofile_spec = NWBGroupSpec(
    "An NWBFile but with a different name",
    neurodata_type_inc="NWBFile",
    neurodata_type_def="FooFile"
)

# Write extension
file_source = 'foofile.yaml'
ns_path = 'foo.namespace.yaml'
ns_builder.add_spec(file_source, foofile_spec)
ns_builder.export(ns_path)

# Error raised here
load_namespaces(ns_path)
```

which gives this error:
```python
Traceback (most recent call last):
  File "try_nwbfile_extension.py", line 18, in <module>
    load_namespaces(ns_path)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 355, in func_call
    return func(**parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/__init__.py", line 95, in load_namespaces
    return __TYPE_MAP.load_namespaces(namespace_path)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/build/map.py", line 916, in load_namespaces
    deps = self.__ns_catalog.load_namespaces(namespace_path, resolve)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/namespace.py", line 403, in load_namespaces
    ret[ns['name']] = self.__load_namespace(ns, reader, types_key, resolve=resolve)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/namespace.py", line 352, in __load_namespace
    self.__load_spec_file(reader, s['source'], catalog, dtypes=dtypes, resolve=resolve)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/namespace.py", line 320, in __load_spec_file
    ret.extend(__reg_spec(self.__group_spec_cls, spec_dict))
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/namespace.py", line 310, in __reg_spec
    return catalog.auto_register(spec_obj, spec_source)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/catalog.py", line 99, in auto_register
    ret.extend(self.auto_register(group_spec, source_file))
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/catalog.py", line 99, in auto_register
    ret.extend(self.auto_register(group_spec, source_file))
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/catalog.py", line 99, in auto_register
    ret.extend(self.auto_register(group_spec, source_file))
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/catalog.py", line 90, in auto_register
    self.register_spec(spec, source_file)
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "/Users/ageorgou/anaconda/envs/nwb/lib/python3.5/site-packages/pynwb/form/spec/catalog.py", line 44, in register_spec
    raise ValueError("'%s' - cannot overwrite existing specification" % type_name)
ValueError: 'Device' - cannot overwrite existing specification
```

The namespace files are are expected:
```
namespaces:
- doc: A pointless extension
  name: foospace
  schema:
  - namespace: core
  - source: foofile.yaml
```

```
groups:
- doc: An NWBFile but with a different name
  neurodata_type_def: FooFile
  neurodata_type_inc: NWBFile
```

I have tried this with `pynwb` version 0.3.0, installed on Python 3.5 through `pip` on OS X.

**Comment by bendichter** [comment]
@ageorgou thanks for the report. This will indeed be an issue whenever we need to extend a datatype that contains other datatypes.

Does anyone have ideas for the best way to deal with this?

**Comment by ageorgou** [comment]
@bendichter Thanks for the reply. It seems to me that checking whether the groups are inherited or not (as is done with datasets) would solve this, but I haven't tried it yet. I wanted to wait and see whether I'm missing something. Happy to try, though, and, if it works, submit a PR fixing it that way.

**Comment by bendichter** [comment]
@ageorgou I don't know much about the design decisions for the extensions library, but it sounds like your proposed solution is worth a shot.

**Comment by ajtritt** [comment]
As long as “inherited” is defined as a data_type that came from a nested type definition eg Device, and the containing type eg NWBFile matches appropriately, I think this should be fine. At a high level, this just means not registering nested definitions for extensions of included types.

**Comment by ageorgou** [comment]
A small update: `LabMetaData` will possibly cover the reason why we needed to extend `NWBFile`. That said, the issue (if it is indeed a bug) remains. I have looked at it a bit and, if I remember right, tracked it down to what is considered an inherited type, but didn't manage to resolve it. There may be a simpler way e.g. by avoiding registration at a higher level.

**Comment by bendichter** [comment]
@ageorgou yes I am hoping LabMetaData will cover your need for lab specific data. I think that would be better than extending NWBFile.

**Comment by t-b** [comment]
@bendichter But the bug described here is still present or?

**Comment by bendichter** [comment]
@t-b we created a different solution to the problem with `LabMetaData`, that seemed suitable for @ageorgou. I can't think of a situation where extending `NWBFile` would be preferable to extending `LabMetaData`, but if you have another problem that requires it we could re-open the issue. I tend to think allowing users to extend `NWBFile` gives them a bit too much power to run wild, but I could be convinced otherwise.

**Comment by t-b** [comment]
@bendichter Thanks for the explanation. Now I get it. No need to reopen.
