### ISSUE TITLE
builder 'images' does not have a data_type

### ISSUE THREAD

**Issue by mschachter** [NeurodataWithoutBorders/pynwb#563]
### Steps to Reproduce

I created an hdf5-based .nwb file. It has multi-electrode electrophys data in it, with both LFP and spike trains. I can't read the file I created. This is super depressing.

Download .nwb file from here (~820MB):

https://drive.google.com/file/d/1W0w-7VtHWXv9LEIlYw7meInxvF2sYpv0/view?usp=sharing

Run this code:

```
io = NWBHDF5IO('/path/to/downloaded file')
nwb = io.read()
```

Get this error:

```
ValueError: builder 'images' does not have a data_type
```

### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda 5.2
- **Python Version:** Python 3.6
- **Operating System:** Ubuntu
- **Pynwb Version:**
version_json = '''
{
"date": "2018-04-24T12:53:53-0700",
"dirty": false,
"error": null,
"full-revisionid": "9b52025a9656ccde3f7b4d1f4126d2ef97fdecaf",
"version": "0.3.0"
}

### Stack Trace
```
Traceback (most recent call last):
  File "~/code/zeebeez3/scripts/fix_pynwb.py", line 7, in <module>
    nwb = io.read()
  File "~/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "~/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/backends/io.py", line 33, in read
    container = self.__manager.construct(f_builder)
  File "~/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "~/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/build/map.py", line 171, in construct
    result = self.__type_map.construct(builder, self)
  File "~/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "~/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/build/map.py", line 1199, in construct
    return attr_map.construct(builder, build_manager)
  File "~/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "~/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/build/map.py", line 797, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "~/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/build/map.py", line 783, in __get_subspec_values
    result = self.__get_subspec_values(sub_builder, subspec, manager)
  File "~/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/build/map.py", line 765, in __get_subspec_values
    subspec = manager.get_subspec(spec, sub_builder)
  File "~/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "~/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/build/map.py", line 227, in get_subspec
    return self.__type_map.get_subspec(spec, builder)
  File "~/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/utils.py", line 347, in func_call
    return func(self, **parsed['args'])
  File "~/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/build/map.py", line 1083, in get_subspec
    dt = self.get_builder_dt(builder)
  File "~/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/build/map.py", line 1037, in get_builder_dt
    raise ValueError(msg)
ValueError: builder 'images' does not have a data_type
```

**Comment by bendichter** [comment]
Can you try an earlier version of pynwb? I'll try to fix this but won't
have access for a few hours.

**Comment by bendichter** [comment]
Hey @mschachter I'm looking into this

**Comment by bendichter** [comment]
@mschachter `pynwb` expects `/acquisition/images` and `/acquisition/timeseries` to have attributes and they don't. How did you create this file? Can you send me the script?

**Comment by mschachter** [comment]
Thanks again @bendichter it turns out I was doing some perverse things without knowing it. I was writing the files with python 2.7, an old version of pynwb, and reading them with python 3.6, with a newer version of pynwb. Now that I'm re-running the code that generates the nwb files with python 3.6, there are various keyword argument name changes that are throwing errors. I'm going to work through them, I'll let you know if I continue to have issues after that.

**Comment by mschachter** [comment]
I know this question is not quite related to the issue anymore - but I'm trying to use nwbfile.create_epoch, and it requires a timeseries as an argument. What if there are two electrode arrays, and as such, two timeseries objects that would correspond to an epoch? Should I aggregate the two electrode arrays into one ElectricalSeries object? Or should I have one epoch for each electrode array?

**Comment by bendichter** [comment]
You can input a list of TimeSeries objects

**Comment by mschachter** [comment]
Ok, I'm using the latest from github now, instead of 0.3.0. It fixes many problems I'm having. There are some new problems that I will post in another issue. Basically, this issue arose because I created an .nwb file in January, and a change in NWB between then and the 0.3.0 release broke backwards readability. I'm not sure if that was intentional or not, but regardless I'm moving foward! Any idea when there will be a new push for the latest pynwb to PyPi?

**Comment by bendichter** [comment]
Glad to hear you're moving forward and happy to help with the process! I agree we could use more frequent pynwb releases on pypi but no news when the next one will occur.
