### ISSUE TITLE
AttributeError: 'Proxy' object has no attribute 'name'

### ISSUE THREAD

**Issue by mschachter** [NeurodataWithoutBorders/pynwb#568]
### Steps to Reproduce
There's code to produce the .nwb file at the bottom of this report, but you can download a sample file (~450k) from here:

https://drive.google.com/file/d/1_D6noYK2nBK3tP7rEHvkyHE-7s53UX_M/view?usp=sharing

Here's the code you need to run to reproduce the error:

    nwb_file = os.path.join('/tmp/bird_Site1.nwb')
    io = NWBHDF5IO(nwb_file, mode='r')
    nwb = _io.read()

```
Provide a minimal code snippet here to reproduce this error.
```
### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda
- **Python Version:** Python 3.6
- **Operating System:** Linux
- **Pynwb Version:** version_json = '''
{
 "date": "2018-07-25T18:28:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "17fc799529b14c3bad5f0e0188c37743b678bc4f",
 "version": "0.3.0.post.dev212"
}

### Stack trace
```
Traceback (most recent call last):
  File "/home/mschachter/code/zeebeez3/scripts/fix_pynwb.py", line 154, in <module>
    _nwb = _io.read()
  File "/home/mschachter/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/home/mschachter/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/backends/io.py", line 33, in read
    container = self.__manager.construct(f_builder)
  File "/home/mschachter/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/home/mschachter/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/build/map.py", line 179, in construct
    self.__resolve_parents(result)
  File "/home/mschachter/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/build/map.py", line 189, in __resolve_parents
    tmp.parent = tmp.parent.resolve()
  File "/home/mschachter/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/build/map.py", line 61, in resolve
    if self.matches(candidate):
  File "/home/mschachter/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/home/mschachter/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/build/map.py", line 51, in matches
    obj = self.__manager.get_proxy(obj)
  File "/home/mschachter/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/home/mschachter/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/build/map.py", line 100, in get_proxy
    return self.__get_proxy_container(obj)
  File "/home/mschachter/anaconda3/envs/zeebeez3/lib/python3.6/site-packages/pynwb/form/build/map.py", line 118, in __get_proxy_container
    stack.append(tmp.name)
AttributeError: 'Proxy' object has no attribute 'name'
```

### Reproducing the bug

Here's how to create the file:

```
import os

from dateutil import parser as date_parser
import h5py

import numpy as np

from pynwb import NWBFile, NWBHDF5IO
from pynwb.ecephys import ElectricalSeries, SpikeEventSeries


def write_multiple_nwb_files(root_dir='/tmp'):

    rec_datetime = date_parser.parse('03/22/2018 15:35:22')

    # create an electrode array, electrode groups, and electrode table for the electrodes
    lfp_series = dict()
    spike_series = dict()

    for block in ['Site1', 'Site2']:

        print('*************** Processing block {}'.format(block))

        recording_name = '{}_{}'.format('bird', block)

        nwb_file = os.path.join(root_dir, '{}.nwb'.format(recording_name))

        session_desc = "A single recording session"

        exp_desc = "An experiment."

        nf = NWBFile(recording_name, session_desc,
                     'bird',
                     rec_datetime,
                     experimenter='Experi Menter',
                     lab='The Lab',
                     institution='University of Shaz',
                     experiment_description=exp_desc,
                     session_id='bird')

        # create the electrodes and electrode tables
        for hemi in ['R', 'L']:

            electrode_array_name = '16 electrode microwire array on {} hemisphere'.format(hemi)
            electrode_array = nf.create_device(name=electrode_array_name, source='')

            # create an electrode group
            egrp_desc = """ The (x,y) locations of the electrodes refer to the distance from region midline and distance
                            from L2A, respectively, in mm.            
                        """

            electrode_group = nf.create_electrode_group(hemi,
                                                        source=electrode_array_name,
                                                        description=egrp_desc,
                                                        location='{} Hemisphere, Field L, CM, NCM'.format(hemi),
                                                        device=electrode_array)

            # add electrodes to electrode group
            electrode_start = 0
            if hemi == 'R':
                electrode_start = 16
            electrode_numbers = list(np.arange(electrode_start, electrode_start + 16))
            for electrode_number in electrode_numbers:

                nf.add_electrode(electrode_number-1,
                                 x=np.random.randn(), y=np.random.randn(), z=0.0,
                                 imp=0.0,
                                 location='cortex',
                                 filtering='none',
                                 description='An electrode',
                                 group=electrode_group)

            # create an electrode table region
            etable = nf.create_electrode_table_region(electrode_numbers,
                                                      'All electrodes in array for hemisphere {}'.format(hemi))

            lfp_data = np.random.randn(len(electrode_numbers), 1000)
            sr = 1000.
            t = np.arange(lfp_data.shape[1]) / sr

            # add the raw LFP
            lfp_series_name = 'Multi-electrode LFP on {} hemisphere from block {}'.format(hemi, block)
            lfp = ElectricalSeries(
                lfp_series_name,
                electrode_array_name,
                lfp_data,
                etable,
                timestamps=t,
                resolution=1e-12,
                comments='',
                description='Low-passed LFP recorded from microwire array'
            )

            lfp_series[hemi] = lfp

            # add the spikes and their waveforms
            for electrode_number in electrode_numbers:

                for k in range(3):
                    if k == 0:
                        unit_name = 'Chan{} Code0'.format(electrode_number)
                    else:
                        unit_name = 'RF Sort unit {}'.format(k+1)

                    spike_times = [0.5, 1.5, 3.5]
                    waveforms = np.random.randn(3, 18)

                    if unit_name.startswith('RF Sort'):
                        xarr = unit_name.split(' ')
                        unit_num = xarr[-1]
                        sort_type = 'Spike-sorted unit {}'.format(unit_num)

                    elif unit_name.startswith('Chan'):
                        if 'Code0' not in unit_name:
                            print('Skipping multi-unit channel with non-zero sort code')
                            continue
                        sort_type = 'Multi-unit'
                    else:
                        raise Exception('Unknown unit name: {}'.format(unit_name))

                    full_unit_name = '{} on electrode {}'.format(sort_type, electrode_number)
                    spikes = SpikeEventSeries(full_unit_name, lfp_series_name,
                                              waveforms, spike_times, etable,
                                              resolution=1e-12, conversion=1e6,
                                              comments='',
                                              description='',
                                              )

                    print('\tAdding spikes acquisition: {} ({}), waveforms.shape={}'.format(full_unit_name, sort_type,
                                                                                            str(waveforms.shape)))

                    spike_series[(hemi, electrode_number, unit_name)] = spikes

        all_series = list()
        all_series.extend(lfp_series.values())
        all_series.extend(spike_series.values())
        nf.add_acquisition(all_series)

        print('Writing to {}'.format(nwb_file))
        with NWBHDF5IO(nwb_file, mode='w') as io:
            io.write(nf)

        del nf



if __name__ == '__main__':

    write_multiple_nwb_files('/tmp')

    _nwb_file = os.path.join('/tmp/bird_Site1.nwb')
    _io = NWBHDF5IO(_nwb_file, mode='r')
    _nwb = _io.read()
```

**Comment by bendichter** [comment]
yes I can reproduce the bug. Let me dig into it a little

**Comment by bendichter** [comment]
do you think you could whittle this down to a minimal example that has the same error? Here's a start:

```python
import os

from dateutil import parser as date_parser
import h5py

import numpy as np

from pynwb import NWBFile, NWBHDF5IO
from pynwb.ecephys import ElectricalSeries, SpikeEventSeries

root_dir = os.curdir

rec_datetime = date_parser.parse('03/22/2018 15:35:22')

# create an electrode array, electrode groups, and electrode table for the electrodes
lfp_series = dict()
spike_series = dict()

for block in ['Site1', 'Site2']:


    recording_name = 'test'

    nwb_file = os.path.join(root_dir, '{}.nwb'.format(recording_name))

    session_desc = "A single recording session"

    exp_desc = "An experiment."

    nf = NWBFile(recording_name, session_desc,
                 'bird',
                 rec_datetime,
                 experimenter='Experi Menter',
                 lab='The Lab',
                 institution='University of Shaz',
                 experiment_description=exp_desc,
                 session_id='bird')

    # create the electrodes and electrode tables
    for hemi in ['R', 'L']:

        electrode_array_name = '16 electrode microwire array on {} hemisphere'.format(hemi)
        electrode_array = nf.create_device(name=electrode_array_name, source='')

        # create an electrode group
        egrp_desc = """ The (x,y) locations of the electrodes refer to the distance from region midline and distance
                        from L2A, respectively, in mm.            
                    """

        electrode_group = nf.create_electrode_group(hemi,
                                                    source=electrode_array_name,
                                                    description=egrp_desc,
                                                    location='{} Hemisphere, Field L, CM, NCM'.format(hemi),
                                                    device=electrode_array)

        # add electrodes to electrode group
        electrode_start = 0
        if hemi == 'R':
            electrode_start = 16
        electrode_numbers = list(np.arange(electrode_start, electrode_start + 16))
        for electrode_number in electrode_numbers:

            nf.add_electrode(electrode_number-1,
                             x=np.random.randn(), y=np.random.randn(), z=0.0,
                             imp=0.0,
                             location='cortex',
                             filtering='none',
                             description='An electrode',
                             group=electrode_group)

        # create an electrode table region
        etable = nf.create_electrode_table_region(electrode_numbers,
                                                  'All electrodes in array for hemisphere {}'.format(hemi))

        lfp_data = np.random.randn(len(electrode_numbers), 1000)
        sr = 1000.
        t = np.arange(lfp_data.shape[1]) / sr

        # add the spikes and their waveforms
        for electrode_number in electrode_numbers:

            for k in range(3):
                if k == 0:
                    unit_name = 'Chan{} Code0'.format(electrode_number)
                else:
                    unit_name = 'RF Sort unit {}'.format(k+1)

                spike_times = [0.5, 1.5, 3.5]
                waveforms = np.random.randn(3, 18)

                if unit_name.startswith('RF Sort'):
                    xarr = unit_name.split(' ')
                    unit_num = xarr[-1]
                    sort_type = 'Spike-sorted unit {}'.format(unit_num)

                elif unit_name.startswith('Chan'):
                    if 'Code0' not in unit_name:
                        print('Skipping multi-unit channel with non-zero sort code')
                        continue
                    sort_type = 'Multi-unit'
                else:
                    raise Exception('Unknown unit name: {}'.format(unit_name))

                full_unit_name = '{} on electrode {}'.format(sort_type, electrode_number)
                spikes = SpikeEventSeries(full_unit_name, lfp_series_name,
                                          waveforms, spike_times, etable,
                                          resolution=1e-12, conversion=1e6,
                                          comments='',
                                          description='',
                                          )

                spike_series[(hemi, electrode_number, unit_name)] = spikes

all_series = list()
all_series.extend(spike_series.values())
nf.add_acquisition(all_series)

print('Writing to {}'.format(nwb_file))
with NWBHDF5IO(nwb_file, mode='w') as io:
    io.write(nf)

    del nf
    
import os
from pynwb import NWBHDF5IO

nwb_file = os.path.join('test.nwb')
with NWBHDF5IO(nwb_file, mode='r') as io:
    nwb = io.read()
```

**Comment by mschachter** [comment]
Sure thing @bendichter ! In this simplified example, adding the SpikeEventSeries using nf.add_acquisition is what makes the hdf5 based nwb file unreadable:

```python

import os

from dateutil import parser as date_parser
import h5py

import numpy as np

from pynwb import NWBFile, NWBHDF5IO
from pynwb.ecephys import ElectricalSeries, SpikeEventSeries


def write_multiple_nwb_files(root_dir='/tmp'):

    rec_datetime = date_parser.parse('03/22/2018 15:35:22')

    block = 'Site1'

    recording_name = '{}_{}'.format('bird', block)

    nwb_file = os.path.join(root_dir, '{}.nwb'.format(recording_name))

    session_desc = "A single recording session"

    exp_desc = "An experiment."

    nf = NWBFile(recording_name, session_desc,
                 'bird',
                 rec_datetime,
                 experimenter='Experi Menter',
                 lab='The Lab',
                 institution='University of Shaz',
                 experiment_description=exp_desc,
                 session_id='bird')

    hemi = 'L'

    electrode_array_name = '16 electrode microwire array on {} hemisphere'.format(hemi)
    electrode_array = nf.create_device(name=electrode_array_name, source='')

    # create an electrode group
    electrode_group = nf.create_electrode_group(hemi,
                                                source=electrode_array_name,
                                                description='the electrodes',
                                                location='{} Hemisphere, Field L, CM, NCM'.format(hemi),
                                                device=electrode_array)

    # add electrodes to electrode group
    electrode_numbers = list(np.arange(16))
    for electrode_number in electrode_numbers:

        nf.add_electrode(electrode_number-1,
                         x=np.random.randn(), y=np.random.randn(), z=0.0,
                         imp=0.0,
                         location='cortex',
                         filtering='none',
                         description='An electrode',
                         group=electrode_group)

    # create an electrode table region
    etable = nf.create_electrode_table_region(electrode_numbers,
                                              'All electrodes in array for hemisphere {}'.format(hemi))

    lfp_data = np.random.randn(len(electrode_numbers), 1000)
    sr = 1000.
    t = np.arange(lfp_data.shape[1]) / sr

    # add the raw LFP
    lfp_series_name = 'Multi-electrode LFP on {} hemisphere from block {}'.format(hemi, block)
    lfp = ElectricalSeries(
        lfp_series_name,
        electrode_array_name,
        lfp_data,
        etable,
        timestamps=t,
        resolution=1e-12,
        comments='',
        description='Low-passed LFP recorded from microwire array'
    )

    # add the spikes and their waveforms
    electrode_number = 0
    spike_times = [0.5, 1.5, 3.5]
    waveforms = np.random.randn(3, 18)
    sort_type = 'Multi-unit'

    full_unit_name = '{} on electrode {}'.format(sort_type, electrode_number)
    spikes = SpikeEventSeries(full_unit_name, lfp_series_name,
                              waveforms, spike_times, etable,
                              resolution=1e-12, conversion=1e6,
                              comments='',
                              description='',
                              )

    print('\tAdding spikes acquisition: {} ({}), waveforms.shape={}'.format(full_unit_name, sort_type,
                                                                            str(waveforms.shape)))

    # adding the LFP is fine
    nf.add_acquisition(lfp)

    ########################################################
    # adding even a single spike event series causes the error
    ########################################################
    nf.add_acquisition(spikes)

    print('Writing to {}'.format(nwb_file))
    with NWBHDF5IO(nwb_file, mode='w') as io:
        io.write(nf)

    del nf



if __name__ == '__main__':

    write_multiple_nwb_files('/tmp')

    _nwb_file = os.path.join('/tmp/bird_Site1.nwb')
    _io = NWBHDF5IO(_nwb_file, mode='r')
    _nwb = _io.read()
```

**Comment by mschachter** [comment]
In the code that throws the error, it is calling the BuildManager.__get_proxy_container function, trying to find the 'name' attribute of an NWBFile container (container is the argument to that function), and that object does not have a property called 'name'. When I print out the container object, it looks like this:

{'source': '/tmp/bird_Site1.nwb', 'location': 'root', 'namespace': 'core', 'data_type': 'NWBFile'}

**Comment by bendichter** [comment]
@mschachter Thanks for the detective work. It looks like the object that's causing a problem is the `NWBFile` dtype, the dtype that is the parent group for all the other types. That's odd, I'm still not sure what could be causing it. The smaller you can get that code while still getting the same error, the easier it will be for us to figure out what's causing the error and fix it. 

Also here's a tip: you can use language-specific highlighting in github by starting a code block with "```python", which makes the code in the post easier to read.

**Comment by ajtritt** [comment]
A work-around here is to create another *ElectrodeTableRegion* i.e. don't reuse `etable`. (This workaround applies to #558 )

I haven't figured out exactly why that causes the problem, but since *ElectrodeTableRegion* is a neurodata_type, it will be linked to by the *SpikeEventSeries*.  *Proxy* objects are created for appropriate link resolution. I suspect this problem is caused by an edge case I missed, where I forgot about resolving links to *Data* objects in addition to *Container* objects.

**Comment by bendichter** [comment]
@ajtritt thanks for looking into this, that sounds like a pretty reasonable work-around for now

**Comment by mschachter** [comment]
Thanks @bendichter for the tip! Thanks also @ajtritt , your suggestion to create a new electrode table for the spikes works. If what I was doing was an edge case, then it doesn't bother me much to just create a separate electrode table for the spikes.

**Comment by bendichter** [comment]
@mschachter Andrew fixed this today and I just pushed it up to pypi :-)

**Comment by mschachter** [comment]
Thanks again  @bendichter  and @ajtritt , I can confirm that the latest version of pynwb on pypi fixes the ruamel issue and the proxy name issue.
