### ISSUE TITLE
cannot input list of different lengths in DynamicTable

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#602]
error on `write`

```python
from pynwb import NWBFile, NWBHDF5IO
from datetime import datetime


nwbfile = NWBFile('a', 'b', 'c', datetime.now(), datetime.now())

nwbfile.add_unit_column('excitatory_connections', 'ids of cells that receive excitatory input from cell')

nwbfile.add_unit({'id': 1, 'excitatory_connections': [1, 2]})
nwbfile.add_unit({'id': 2, 'excitatory_connections': [1, 2, 3]})

with NWBHDF5IO('test_unit.nwb', 'w') as io:
    io.write(nwbfile)
```

```
/Users/bendichter/anaconda3/envs/dev_pynwb/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/Users/bendichter/dev/to_nwb/to_nwb/Buzsaki/test_add_unit.py", line 13, in <module>
    io.write(nwbfile)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 186, in write
    call_docval_func(super(HDF5IO, self).write, kwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 230, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/io.py", line 40, in write
    self.write_builder(f_builder, **kwargs)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 367, in write_builder
    self.write_group(self.__file, gbldr)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 509, in write_group
    self.write_dataset(group, sub_builder)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/utils.py", line 330, in func_call
    return func(self, **parsed['args'])
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 697, in write_dataset
    dset = self.__list_fill__(parent, name, data, options)
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 828, in __list_fill__
    raise e
  File "/Users/bendichter/dev/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 826, in __list_fill__
    dset[:] = data
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/bendichter/anaconda3/envs/dev_pynwb/lib/python3.6/site-packages/h5py/_hl/dataset.py", line 632, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 221, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 132, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite
OSError: Can't prepare for writing data (no appropriate function for conversion path)
```
### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda or Python
- **Python Version:** Python 2.7 or Python 3.6
- **Operating System:** Windows, macOS or Linux
- **Pynwb Version:** Version of Pynwb used

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?

**Comment by tjd2002** [comment]
Still an issue. Workarounds: enclose each list in a list; use a vectorData type

**Comment by oruebel** [comment]
I believe units has changed quite a bit since this issue was opened. @bendichter can this issue be closed or is this still a problem?
