### ISSUE TITLE
older yaml. incompatibility with 0.5.1

### ISSUE THREAD

**Issue by yarikoptic** [NeurodataWithoutBorders/pynwb#624]
While building updated debian pkg across debian/ubuntus, on debian stable and similarly aged ubuntus got bombarded with multiple instances of similar error
```
======================================================================
ERROR: test_load_namespace_with_reftype_attribute_check_autoclass_const (tests.unit.pynwb_tests.test_extension.TestExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit/pynwb_tests/test_extension.py", line 72, in test_load_namespace_with_reftype_attribute_check_autoclass_const
    ns_builder.export(self.ns_path, outdir=self.tempdir)
  File "pynwb/form/utils.py", line 337, in func_call
    return func(self, **parsed['args'])
  File "pynwb/form/spec/write.py", line 172, in export
    writer.write_spec(out, path)
  File "pynwb/form/spec/write.py", line 41, in write_spec
    self.reorder_yaml(os.path.join(self.__outdir, path))
  File "pynwb/form/spec/write.py", line 50, in reorder_yaml
    sorted_data = self.sort_keys(data)
  File "pynwb/form/spec/write.py", line 59, in sort_keys
    yaml.RoundTripRepresenter.add_representer(type(None), my_represent_none)
AttributeError: 'module' object has no attribute 'RoundTripRepresenter'

======================================================================
ERROR: test_load_namespace_with_reftype_attribute_check_autoclass_const (tests.unit.pynwb_tests.test_extension.TestExtension)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit/pynwb_tests/test_extension.py", line 31, in tearDown
    os.remove(path)
OSError: [Errno 2] No such file or directory: '/tmp/Z8Q4XV664Y_namespace.yaml'
```
due to recently introduced
```
+
+        # Represent None as null
+        def my_represent_none(self, data):
+            return self.represent_scalar(u'tag:yaml.org,2002:null', u'null')
+        yaml.RoundTripRepresenter.add_representer(type(None), my_represent_none)
```

on those systems python-ruamel.yaml (0.13.4-2), when recent ones have 0.15.34 

I will quickly look into backporting that recent release for neurodebian but just wanted to bring to your attention since you might need to boost you version depends or desire to provide a workaround?

Related -- either I lost my git-mind, or bitbucket is having issues since
```shell
smaug:/tmp
$> git clone https://bitbucket.org/ruamel/yaml     
Cloning into 'yaml'...
fatal: repository 'https://bitbucket.org/ruamel/yaml/' not found
```

**Comment by yarikoptic** [comment]
jesus... it was mercurial (hg) not git! so
```shell
$> git clone hg::https://bitbucket.org/ruamel/yaml
Cloning into 'yaml'...
applying clone bundle from https://api.media.atlassian.com/file/8adc52b2-98a4-4a3e-90d1-fb46db41537a/binary?client=3019f627-4638-46e6-8562-8b9582f3155d&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOjhhZGM1MmIyLTk4YTQtNGEzZS05MGQxLWZiNDZkYjQxNTM3YSI6WyJyZWFkIl19LCJleHAiOjE1Mzc0NTE5ODUsImlzcyI6IjMwMTlmNjI3LTQ2MzgtNDZlNi04NTYyLThiOTU4MmYzMTU1ZCIsIm5iZiI6MTUzNzQ1MTU2NX0.I2TNmgUf6JabBH9efWe7vbu-clZHt34am6MWTrB12ac
adding changesets
adding manifests
...
```

**Comment by bendichter** [comment]
OK so the story here is that "null" was originally used in the schema yamls, then I re-sorted the yamls to be more readable but in the process I accidentally deleted all the "null"s. I didn't notice because the yamls worked as expected, even without the "null"s, and all the tests passed. Still, this was an unplanned change to the schema language, so I added the above code so that the yamls would be written in the readable order AND have "null"s. I don't know if anyone has an attachment to "null", but the non-"null" files worked fine, so we could just go back to those and update the schema language accordingly.
