### ISSUE TITLE
repr fails for many containers after read

### ISSUE THREAD

**Issue by NileGraddis** [NeurodataWithoutBorders/pynwb#734]
Here's a weird one. The `__repr__` method on NWBBaseType frequently fails for containers after round-trip. I ran into this using [this script](https://gist.github.com/NileGraddis/69cff02ab7753de331590ce54726eb10) (python 3.6, pynwb 033d2462b17a49dfcbab929f92717292b00d237d), but it can be seen more generally by inserting calls to `__repr__` [here](https://github.com/NeurodataWithoutBorders/pynwb/blob/033d2462b17a49dfcbab929f92717292b00d237d/tests/integration/ui_write/base.py#L170) like such:
```Python
print(repr(self.container))
print(repr(self.read_container))
```
This produces a lot of prints from the first line, and a lot of ValueErrors from the second. Example:
```
======================================================================
ERROR: test_roundtrip (ui_write.test_icephys.TestSweepTableRoundTripComplicated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nile/Documents/allen_institute/pynwb/pynwb/tests/integration/ui_write/base.py", line 172, in test_roundtrip
    print(repr(self.read_container))
  File "/home/nile/Documents/allen_institute/pynwb/pynwb/src/pynwb/core.py", line 150, in __repr__
    template += "  {}: {} \n".format(k, self.__smart_str(v))
  File "/home/nile/Documents/allen_institute/pynwb/pynwb/src/pynwb/core.py", line 175, in __smart_str
    return str(np.array(v))
  File "/home/nile/Documents/allen_institute/pynwb/pynwb/src/pynwb/core.py", line 388, in __getitem__
    return self.__getitem_helper(arg)
  File "/home/nile/Documents/allen_institute/pynwb/pynwb/src/pynwb/core.py", line 378, in __getitem_helper
    return self.target[start:end]
  File "/home/nile/Documents/allen_institute/pynwb/pynwb/src/pynwb/core.py", line 289, in __getitem__
    return self.data[args]
  File "/home/nile/Documents/allen_institute/pynwb/pynwb/src/pynwb/form/backends/hdf5/h5_utils.py", line 104, in __getitem__
    return self.io.get_container(self.dataset.file[ref])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/nile/Documents/allen_institute/pynwb/pynwb/.tox/py36/lib/python3.6/site-packages/h5py/_hl/group.py", line 167, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "/home/nile/Documents/allen_institute/pynwb/pynwb/.tox/py36/lib/python3.6/site-packages/h5py/_hl/base.py", line 132, in _e
    name = name.encode('ascii')
AttributeError: 'numpy.ndarray' object has no attribute 'encode'
```

This problem is obviously not a blocker, but is super annoying for users who want to look at their/others' data. That this problem occurs after write, but not before reflects that the `NWBFile` object you write is not the same as the one you read.

Also, the [printing test](https://github.com/NeurodataWithoutBorders/pynwb/blob/033d2462b17a49dfcbab929f92717292b00d237d/tests/unit/pynwb_tests/test_core.py#L277) in the unit tests should ideally compare the results of `__repr__` to a cached string, not just print to standard out.

**Comment by bendichter** [comment]
@NileGraddis Thanks for this, I didn't think about how round trips would affect printing. I'll fix it.
