### ISSUE TITLE
Cannot write empty trials table with added column

### ISSUE THREAD

**Issue by VBaratham** [NeurodataWithoutBorders/pynwb#844]
### Steps to Reproduce
```
from datetime import datetime
from pynwb import NWBFile, NWBHDF5IO

nwbfile = NWBFile('aa', 'aa', datetime.now())
nwbfile.add_trial_column('name', 'Description')

with NWBHDF5IO('testfile.nwb', 'w') as io:
    io.write(nwbfile)
```

Produces this error:

```
/Users/vbaratham/src/pynwb/src/pynwb/file.py:612: UserWarning: Date is missing timezone information. Updating to local timezone.
  warn("Date is missing timezone information. Updating to local timezone.")
/Users/vbaratham/src/pynwb/src/pynwb/form/build/map.py:915: MissingRequiredWarning: dataset 'start_time' for 'trials' of type (TimeIntervals)
  warnings.warn(msg, MissingRequiredWarning)
/Users/vbaratham/src/pynwb/src/pynwb/form/build/map.py:915: MissingRequiredWarning: dataset 'stop_time' for 'trials' of type (TimeIntervals)
  warnings.warn(msg, MissingRequiredWarning)
/Users/vbaratham/src/pynwb/src/pynwb/form/build/map.py:915: MissingRequiredWarning: dataset 'id' for 'trials' of type (TimeIntervals)
  warnings.warn(msg, MissingRequiredWarning)
Traceback (most recent call last):
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/build/map.py", line 872, in __add_attributes
    attr_value, attr_dtype = self.convert_dtype(spec, attr_value)
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/build/map.py", line 438, in convert_dtype
    ret_dtype = tmp_dtype
UnboundLocalError: local variable 'tmp_dtype' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mwe.py", line 9, in <module>
    io.write(nwbfile)
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/backends/hdf5/h5tools.py", line 195, in write
    call_docval_func(super(HDF5IO, self).write, kwargs)
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/utils.py", line 274, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/backends/io.py", line 39, in write
    f_builder = self.__manager.build(container, source=self.__source)
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/build/map.py", line 159, in build
    result = self.__type_map.build(container, self, source=source)
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/build/map.py", line 1542, in build
    builder = attr_map.build(container, manager, builder=builder, source=getargs('source', kwargs))
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/build/map.py", line 752, in build
    self.__add_groups(builder, self.__spec.groups, container, manager, source)
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/build/map.py", line 955, in __add_groups
    self.__add_groups(sub_builder, spec.groups, container, build_manager, source)
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/build/map.py", line 971, in __add_groups
    self.__add_containers(builder, spec, attr_value, build_manager, source, container)
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/build/map.py", line 981, in __add_containers
    rendered_obj = build_manager.build(value, source=source)
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/build/map.py", line 159, in build
    result = self.__type_map.build(container, self, source=source)
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/build/map.py", line 1542, in build
    builder = attr_map.build(container, manager, builder=builder, source=getargs('source', kwargs))
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/build/map.py", line 795, in build
    self.__add_attributes(builder, self.__spec.attributes, container, manager, source)
  File "/Users/vbaratham/src/pynwb/src/pynwb/form/build/map.py", line 875, in __add_attributes
    raise_from(Exception(msg), ex)
  File "<string>", line 3, in raise_from
Exception: could not convert colnames for TimeIntervals trials
```

### Environment
- **Python Executable:** Conda 
- **Python Version:** Python 3.5.6
- **Operating System:** macOS
- **Pynwb Version:** 1.0.0

**Comment by stephprince** [comment]
This issue will be addressed in hdmf - https://github.com/hdmf-dev/hdmf/issues/1000
