### ISSUE TITLE
LabMetaData Extension doesn't round-trip

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#861]
## 1) Bug

I am trying to define a custom LabMetaData using the extension system.  Extensions work fine, and I have built my class according to the test example, and I can confirm that the attribute is written to the file.  However, the read_api is not able to find the lab_meta_data attribute on the read object.

### Steps to Reproduce
```
from datetime import datetime
from dateutil.tz import tzlocal
import os
from pynwb import NWBFile, register_class, docval, load_namespaces, popargs, NWBHDF5IO
from pynwb.spec import NWBNamespaceBuilder, NWBGroupSpec, NWBAttributeSpec, NWBDatasetSpec
from pynwb.file import LabMetaData


# Settings:
neurodata_type = 'OphysBehaviorMetaData'
prefix = 'AIBS_ophys_behavior'
outdir = './'
extension_doc = 'AIBS Visual Behavior ophys lab metadata extension'


metadata_ext_group_spec = NWBGroupSpec(
    neurodata_type_def=neurodata_type,
    neurodata_type_inc='LabMetaData',
    doc=extension_doc,
    attributes=[NWBAttributeSpec(name='ophys_experiment_id', dtype='int', doc='HW')])


# Export spec:
ext_source = '%s_extension.yaml' % prefix
ns_path = '%s_namespace.yaml' % prefix
ns_builder = NWBNamespaceBuilder(extension_doc, prefix)
ns_builder.add_spec(ext_source, metadata_ext_group_spec)
ns_builder.export(ns_path, outdir=outdir)


# Read spec and load namespace:
ns_abs_path = os.path.join(outdir, ns_path)
load_namespaces(ns_abs_path)


@register_class(neurodata_type, prefix)
class OphysBehaviorMetaData(LabMetaData):
    __nwbfields__ = ('ophys_experiment_id',)

    @docval({'name': 'name', 'type': str, 'doc': 'name'},
            {'name': 'ophys_experiment_id', 'type': int, 'doc': 'HW'})
    def __init__(self, **kwargs):
        name, ophys_experiment_id = popargs('name', 'ophys_experiment_id', kwargs)
        super(OphysBehaviorMetaData, self).__init__(name=name)
        self.ophys_experiment_id = ophys_experiment_id


ophys_experiment_id = 123
nwbfile = NWBFile("a file with header data", "NB123A", datetime(2017, 5, 1, 12, 0, 0, tzinfo=tzlocal()))
nwbfile.add_lab_meta_data(OphysBehaviorMetaData(name='metadata', ophys_experiment_id=123))

# Works
with NWBHDF5IO('./tmp.nwb', 'w') as write_io:
    write_io.write(nwbfile)
assert nwbfile.lab_meta_data['metadata'].ophys_experiment_id == ophys_experiment_id 

# Doesnt work
io = NWBHDF5IO('./tmp.nwb', 'r')
nwbfile_out = io.read()
assert nwbfile_out.lab_meta_data['metadata'].ophys_experiment_id ==  ophys_experiment_id 
```
Traceback:
```
/home/nicholasc/anaconda2/lib/python2.7/site-packages/hdmf/build/map.py:892: MissingRequiredWarning: attribute 'help' for 'metadata' (OphysBehaviorMetaData)
  warnings.warn(msg, MissingRequiredWarning)
Traceback (most recent call last):
  File "/home/nicholasc/projects/pynwb/issues/lab_meta_data/sandbox.py", line 64, in <module>
    assert nwbfile_out.lab_meta_data['metadata'].ophys_experiment_id ==  ophys_experiment_id 
  File "/home/nicholasc/projects/pynwb/src/pynwb/core.py", line 57, in __getitem__
    return super(LabelledDict, self).__getitem__(key)
KeyError: 'metadata'
```

### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda 
- **Python Version:** Python 3.6
- **Operating System:** Linux (Ubuntu 16.04 lts)
- **Pynwb Version:** rev 10b46514cb2c7fb6b6f591ccca6a7a26506d8e4f, should be dev HEAD as of this report

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by nicain** [comment]
@bendichter @ajtritt 

Also:
```
print(nwbfile_out.get_lab_meta_data('metadata'))
```
returns
```
/home/nicholasc/anaconda2/lib/python2.7/site-packages/hdmf/build/map.py:892: MissingRequiredWarning: attribute 'help' for 'metadata' (OphysBehaviorMetaData)
  warnings.warn(msg, MissingRequiredWarning)
Traceback (most recent call last):
  File "/home/nicholasc/projects/pynwb/issues/lab_meta_data/sandbox.py", line 63, in <module>
    print(nwbfile_out.get_lab_meta_data('metadata'))
  File "/home/nicholasc/anaconda2/lib/python2.7/site-packages/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/home/nicholasc/projects/pynwb/src/pynwb/core.py", line 714, in _func
    raise KeyError(msg)
KeyError: "'metadata' not found in lab_meta_data of NWBFile 'root'"
```

**Comment by bendichter** [comment]
fixed imports for the latest dev. Error still occurs.
```python
from datetime import datetime
from dateutil.tz import tzlocal
import os
from hdmf.utils import docval, popargs
from pynwb import NWBFile, register_class, load_namespaces, NWBHDF5IO
from pynwb.spec import NWBNamespaceBuilder, NWBGroupSpec, NWBAttributeSpec, NWBDatasetSpec
from pynwb.file import LabMetaData


# Settings:
neurodata_type = 'OphysBehaviorMetaData'
prefix = 'AIBS_ophys_behavior'
outdir = './'
extension_doc = 'AIBS Visual Behavior ophys lab metadata extension'


metadata_ext_group_spec = NWBGroupSpec(
    neurodata_type_def=neurodata_type,
    neurodata_type_inc='LabMetaData',
    doc=extension_doc,
    attributes=[NWBAttributeSpec(name='ophys_experiment_id', dtype='int', doc='HW')])


# Export spec:
ext_source = '%s_extension.yaml' % prefix
ns_path = '%s_namespace.yaml' % prefix
ns_builder = NWBNamespaceBuilder(extension_doc, prefix)
ns_builder.add_spec(ext_source, metadata_ext_group_spec)
ns_builder.export(ns_path, outdir=outdir)

# Read spec and load namespace:
ns_abs_path = os.path.join(outdir, ns_path)
load_namespaces(ns_abs_path)


@register_class(neurodata_type, prefix)
class OphysBehaviorMetaData(LabMetaData):
    __nwbfields__ = ('ophys_experiment_id',)

    @docval({'name': 'name', 'type': str, 'doc': 'name'},
            {'name': 'ophys_experiment_id', 'type': int, 'doc': 'HW'})
    def __init__(self, **kwargs):
        name, ophys_experiment_id = popargs('name', 'ophys_experiment_id', kwargs)
        super(OphysBehaviorMetaData, self).__init__(name=name)
        self.ophys_experiment_id = ophys_experiment_id


ophys_experiment_id = 123
nwbfile = NWBFile("a file with header data", "NB123A", datetime(2017, 5, 1, 12, 0, 0, tzinfo=tzlocal()))
nwbfile.add_lab_meta_data(OphysBehaviorMetaData(name='metadata', ophys_experiment_id=123))

# Works
with NWBHDF5IO('./tmp.nwb', 'w') as write_io:
    write_io.write(nwbfile)
assert nwbfile.lab_meta_data['metadata'].ophys_experiment_id == ophys_experiment_id

# Doesnt work
io = NWBHDF5IO('./tmp.nwb', 'r')
nwbfile_out = io.read()
assert nwbfile_out.lab_meta_data['metadata'].ophys_experiment_id ==  ophys_experiment_id
```
error
```python
/Users/bendichter/dev/hdmf/src/hdmf/build/map.py:892: MissingRequiredWarning: attribute 'help' for 'metadata' (OphysBehaviorMetaData)
  warnings.warn(msg, MissingRequiredWarning)
Traceback (most recent call last):
  File "/Users/bendichter/dev/to_nwb/to_nwb/aibs/get_spec.py", line 60, in <module>
    assert nwbfile_out.lab_meta_data['metadata'].ophys_experiment_id ==  ophys_experiment_id
  File "/Users/bendichter/dev/pynwb/src/pynwb/core.py", line 57, in __getitem__
    return super(LabelledDict, self).__getitem__(key)
KeyError: 'metadata'
```

**Comment by bendichter** [comment]
@ajtritt I think this might be an hdmf issue
