### ISSUE TITLE
add_trial_column with empty data

### ISSUE THREAD

**Issue by nicain** [NeurodataWithoutBorders/pynwb#880]
## 1) Bug

```
from datetime import datetime
from dateutil.tz import tzlocal
import os
from pynwb import NWBFile, register_class, docval, load_namespaces, popargs, NWBHDF5IO
from pynwb.spec import NWBNamespaceBuilder, NWBGroupSpec, NWBAttributeSpec, NWBDatasetSpec
from pynwb.file import LabMetaData

nwbfile = NWBFile("a file with header data", "NB123A", datetime(2017, 5, 1, 12, 0, 0, tzinfo=tzlocal()))
data = []
index = [0,0,0]
nwbfile.add_trial(start_time=.1, stop_time=.2)
nwbfile.add_trial(start_time=.3, stop_time=.4)
nwbfile.add_trial(start_time=.5, stop_time=.6)
nwbfile.add_trial_column(name='example', description='Hi', data=data, index=index)

print(nwbfile.trials.to_dataframe())
```

results in:

```
    nwbfile.add_trial_column(name='example', description='Hi', data=data, index=index)
  File "/home/nicholasc/anaconda2/lib/python2.7/site-packages/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/home/nicholasc/projects/pynwb/src/pynwb/file.py", line 530, in add_trial_column
    call_docval_func(self.trials.add_column, kwargs)
  File "/home/nicholasc/anaconda2/lib/python2.7/site-packages/hdmf/utils.py", line 274, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/home/nicholasc/anaconda2/lib/python2.7/site-packages/hdmf/utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "/home/nicholasc/projects/pynwb/src/pynwb/core.py", line 1178, in add_column
    raise ValueError("cannot pass non-empty index with empty data to index")
ValueError: cannot pass non-empty index with empty data to index
```

If you change data = [] to data=[None], you ge the desired behavior:

```
example  start_time  stop_time
id                               
0       []         0.1        0.2
1       []         0.3        0.4
2       []         0.5        0.6
```

However, on write this little hack results in:

```
Could not create dataset lick_times in /intervals/trials with shape (1,), dtype <class 'NoneType'>, and iosettings . Object dtype dtype('O') has no native HDF5 equivalent
```

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by t-b** [comment]
And here is a MWE

```python

from pynwb import NWBHDF5IO
from datetime import datetime
from dateutil.tz import tzlocal
from pynwb import NWBFile
import numpy as np
from pynwb.icephys import CurrentClampStimulusSeries
from pynwb.icephys import VoltageClampSeries
from pynwb.epoch import TimeIntervals

nwbfile = NWBFile('my first synthetic recording', 'EXAMPLE_ID', datetime.now(tzlocal()),
                  experimenter='Dr. Bilbo Baggins',
                  lab='Bag End Laboratory',
                  institution='University of Middle Earth at the Shire',
                  experiment_description='I went on an adventure with thirteen dwarves to reclaim vast treasures.',
                  session_id='LONELYMTN')

device = nwbfile.create_device(name='Heka ITC-1600')
elec = nwbfile.create_ic_electrode(name="elec0",
                                   description='a mock intracellular electrode',
                                   device=device)

ccss = CurrentClampStimulusSeries(
    name="ccss", data=[1, 2, 3, 4, 5], unit='A',
    starting_time=123.6, rate=10e3, electrode=elec, gain=0.02, sweep_number=15)

nwbfile.add_stimulus(ccss)

vcs = VoltageClampSeries(
    name='vcs', data=[0.1, 0.2, 0.3, 0.4, 0.5],
    unit='A', conversion=1e-12, resolution=np.nan, starting_time=123.6, rate=20e3,
    electrode=elec, gain=0.02, capacitance_slow=100e-12, resistance_comp_correction=70.0,
    capacitance_fast=np.nan, resistance_comp_bandwidth=np.nan, resistance_comp_prediction=np.nan,
    whole_cell_capacitance_comp=np.nan, whole_cell_series_resistance_comp=np.nan, sweep_number=15)

nwbfile.add_acquisition(vcs)

nwbfile.add_trial_column(name='stim', description='the visual stimuli during the trial')
nwbfile.add_trial_column(name='ts', description='Matching TimeSeries')

nwbfile.add_trial(start_time=0.0, stop_time=2.0, stim='person', ts=vcs)
nwbfile.add_trial(start_time=3.0, stop_time=5.0, stim='ocean', ts=ccss)

# FIXME fails
nwbfile.add_trial(start_time=6.0, stop_time=8.0, stim='desert', ts=None)

print(nwbfile.trials.to_dataframe())

io = NWBHDF5IO('icephys_example.nwb', 'w')
io.write(nwbfile)
io.close()

```

which gives

```
$ python icephys.py
Traceback (most recent call last):
  File "icephys.py", line 44, in <module>
    nwbfile.add_trial(start_time=6.0, stop_time=8.0, stim='desert', ts=None)
  File "C:\Anaconda2\lib\site-packages\pynwb\form\utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "C:\Anaconda2\lib\site-packages\pynwb\file.py", line 535, in add_trial
    call_docval_func(self.trials.add_interval, kwargs)
  File "C:\Anaconda2\lib\site-packages\pynwb\form\utils.py", line 274, in call_docval_func
    return func(*fargs, **fkwargs)
  File "C:\Anaconda2\lib\site-packages\pynwb\form\utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "C:\Anaconda2\lib\site-packages\pynwb\epoch.py", line 63, in add_interval
    return super(TimeIntervals, self).add_row(**rkwargs)
  File "C:\Anaconda2\lib\site-packages\pynwb\form\utils.py", line 381, in func_call
    return func(self, **parsed['args'])
  File "C:\Anaconda2\lib\site-packages\pynwb\core.py", line 1120, in add_row
    c.add_row(data[colname])
  File "C:\Anaconda2\lib\site-packages\pynwb\form\utils.py", line 379, in func_call
    raise_from(ExceptionType(msg), None)
  File "C:\Anaconda2\lib\site-packages\six.py", line 737, in raise_from
    raise value
TypeError: incorrect type for 'val' (got 'NoneType', expected 'NoneType')
```

python version is 2.7.15 on Windows.

**Comment by ajtritt** [comment]
@t-b Your MWE is a separate issue from the example that @nicain gave. 

However, I think they are both sufficiently simple that they can be addressed together :)

**Comment by t-b** [comment]
@ajtritt Thanks for your input, if there is something I can help with, ping me.

**Comment by rly** [comment]
@nicain What was the purpose of this code? Did you just want to store trial start and stop times without data?
